// Combat intents/results (200..208) and world/entity replication (300..306).
// Field lists: docs/05_network/messages.md § Combat and § Replication
// (ADR-0037, ADR-0038, ADR-0054, ADR-0060, ADR-0069). Positions/velocities are
// integer millimetres (sint32, 04_architecture/physics_geometry_contract.md).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: thinhthan/v1/combat.proto

package protocolv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DamageElement — the skill's damage element
// (07_content/class_skill_catalog.md § damage_element).
type DamageElement int32

const (
	DamageElement_DAMAGE_ELEMENT_UNSPECIFIED DamageElement = 0
	DamageElement_DAMAGE_ELEMENT_KIM         DamageElement = 1
	DamageElement_DAMAGE_ELEMENT_THUY        DamageElement = 2
	DamageElement_DAMAGE_ELEMENT_MOC         DamageElement = 3
	DamageElement_DAMAGE_ELEMENT_HOA         DamageElement = 4
	DamageElement_DAMAGE_ELEMENT_THO         DamageElement = 5
	DamageElement_DAMAGE_ELEMENT_PHYSICAL    DamageElement = 6
)

// Enum value maps for DamageElement.
var (
	DamageElement_name = map[int32]string{
		0: "DAMAGE_ELEMENT_UNSPECIFIED",
		1: "DAMAGE_ELEMENT_KIM",
		2: "DAMAGE_ELEMENT_THUY",
		3: "DAMAGE_ELEMENT_MOC",
		4: "DAMAGE_ELEMENT_HOA",
		5: "DAMAGE_ELEMENT_THO",
		6: "DAMAGE_ELEMENT_PHYSICAL",
	}
	DamageElement_value = map[string]int32{
		"DAMAGE_ELEMENT_UNSPECIFIED": 0,
		"DAMAGE_ELEMENT_KIM":         1,
		"DAMAGE_ELEMENT_THUY":        2,
		"DAMAGE_ELEMENT_MOC":         3,
		"DAMAGE_ELEMENT_HOA":         4,
		"DAMAGE_ELEMENT_THO":         5,
		"DAMAGE_ELEMENT_PHYSICAL":    6,
	}
)

func (x DamageElement) Enum() *DamageElement {
	p := new(DamageElement)
	*p = x
	return p
}

func (x DamageElement) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DamageElement) Descriptor() protoreflect.EnumDescriptor {
	return file_thinhthan_v1_combat_proto_enumTypes[0].Descriptor()
}

func (DamageElement) Type() protoreflect.EnumType {
	return &file_thinhthan_v1_combat_proto_enumTypes[0]
}

func (x DamageElement) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DamageElement.Descriptor instead.
func (DamageElement) EnumDescriptor() ([]byte, []int) {
	return file_thinhthan_v1_combat_proto_rawDescGZIP(), []int{0}
}

// StatusEventKind — one status-effect lifecycle event
// (01_gameplay/status_effects.md).
type StatusEventKind int32

const (
	StatusEventKind_STATUS_EVENT_KIND_UNSPECIFIED   StatusEventKind = 0
	StatusEventKind_STATUS_EVENT_KIND_APPLIED       StatusEventKind = 1
	StatusEventKind_STATUS_EVENT_KIND_REFRESHED     StatusEventKind = 2
	StatusEventKind_STATUS_EVENT_KIND_STACK_CHANGED StatusEventKind = 3
	StatusEventKind_STATUS_EVENT_KIND_EXPIRED       StatusEventKind = 4
	StatusEventKind_STATUS_EVENT_KIND_DISPELLED     StatusEventKind = 5
	StatusEventKind_STATUS_EVENT_KIND_CONSUMED      StatusEventKind = 6
)

// Enum value maps for StatusEventKind.
var (
	StatusEventKind_name = map[int32]string{
		0: "STATUS_EVENT_KIND_UNSPECIFIED",
		1: "STATUS_EVENT_KIND_APPLIED",
		2: "STATUS_EVENT_KIND_REFRESHED",
		3: "STATUS_EVENT_KIND_STACK_CHANGED",
		4: "STATUS_EVENT_KIND_EXPIRED",
		5: "STATUS_EVENT_KIND_DISPELLED",
		6: "STATUS_EVENT_KIND_CONSUMED",
	}
	StatusEventKind_value = map[string]int32{
		"STATUS_EVENT_KIND_UNSPECIFIED":   0,
		"STATUS_EVENT_KIND_APPLIED":       1,
		"STATUS_EVENT_KIND_REFRESHED":     2,
		"STATUS_EVENT_KIND_STACK_CHANGED": 3,
		"STATUS_EVENT_KIND_EXPIRED":       4,
		"STATUS_EVENT_KIND_DISPELLED":     5,
		"STATUS_EVENT_KIND_CONSUMED":      6,
	}
)

func (x StatusEventKind) Enum() *StatusEventKind {
	p := new(StatusEventKind)
	*p = x
	return p
}

func (x StatusEventKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusEventKind) Descriptor() protoreflect.EnumDescriptor {
	return file_thinhthan_v1_combat_proto_enumTypes[1].Descriptor()
}

func (StatusEventKind) Type() protoreflect.EnumType {
	return &file_thinhthan_v1_combat_proto_enumTypes[1]
}

func (x StatusEventKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusEventKind.Descriptor instead.
func (StatusEventKind) EnumDescriptor() ([]byte, []int) {
	return file_thinhthan_v1_combat_proto_rawDescGZIP(), []int{1}
}

// DespawnReason — why an entity left the AOI (302).
type DespawnReason int32

const (
	DespawnReason_DESPAWN_REASON_UNSPECIFIED DespawnReason = 0
	DespawnReason_DESPAWN_REASON_LEFT_AOI    DespawnReason = 1
	DespawnReason_DESPAWN_REASON_DIED        DespawnReason = 2
	DespawnReason_DESPAWN_REASON_REMOVED     DespawnReason = 3
	DespawnReason_DESPAWN_REASON_TRANSFERRED DespawnReason = 4
	DespawnReason_DESPAWN_REASON_SHED        DespawnReason = 5
)

// Enum value maps for DespawnReason.
var (
	DespawnReason_name = map[int32]string{
		0: "DESPAWN_REASON_UNSPECIFIED",
		1: "DESPAWN_REASON_LEFT_AOI",
		2: "DESPAWN_REASON_DIED",
		3: "DESPAWN_REASON_REMOVED",
		4: "DESPAWN_REASON_TRANSFERRED",
		5: "DESPAWN_REASON_SHED",
	}
	DespawnReason_value = map[string]int32{
		"DESPAWN_REASON_UNSPECIFIED": 0,
		"DESPAWN_REASON_LEFT_AOI":    1,
		"DESPAWN_REASON_DIED":        2,
		"DESPAWN_REASON_REMOVED":     3,
		"DESPAWN_REASON_TRANSFERRED": 4,
		"DESPAWN_REASON_SHED":        5,
	}
)

func (x DespawnReason) Enum() *DespawnReason {
	p := new(DespawnReason)
	*p = x
	return p
}

func (x DespawnReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DespawnReason) Descriptor() protoreflect.EnumDescriptor {
	return file_thinhthan_v1_combat_proto_enumTypes[2].Descriptor()
}

func (DespawnReason) Type() protoreflect.EnumType {
	return &file_thinhthan_v1_combat_proto_enumTypes[2]
}

func (x DespawnReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DespawnReason.Descriptor instead.
func (DespawnReason) EnumDescriptor() ([]byte, []int) {
	return file_thinhthan_v1_combat_proto_rawDescGZIP(), []int{2}
}

// CombatResultKind — primary outcome class of a combat event (304).
type CombatResultKind int32

const (
	CombatResultKind_COMBAT_RESULT_KIND_UNSPECIFIED  CombatResultKind = 0
	CombatResultKind_COMBAT_RESULT_KIND_DAMAGE       CombatResultKind = 1
	CombatResultKind_COMBAT_RESULT_KIND_HEAL         CombatResultKind = 2
	CombatResultKind_COMBAT_RESULT_KIND_SHIELD_GRANT CombatResultKind = 3
	CombatResultKind_COMBAT_RESULT_KIND_SHIELD_BREAK CombatResultKind = 4
)

// Enum value maps for CombatResultKind.
var (
	CombatResultKind_name = map[int32]string{
		0: "COMBAT_RESULT_KIND_UNSPECIFIED",
		1: "COMBAT_RESULT_KIND_DAMAGE",
		2: "COMBAT_RESULT_KIND_HEAL",
		3: "COMBAT_RESULT_KIND_SHIELD_GRANT",
		4: "COMBAT_RESULT_KIND_SHIELD_BREAK",
	}
	CombatResultKind_value = map[string]int32{
		"COMBAT_RESULT_KIND_UNSPECIFIED":  0,
		"COMBAT_RESULT_KIND_DAMAGE":       1,
		"COMBAT_RESULT_KIND_HEAL":         2,
		"COMBAT_RESULT_KIND_SHIELD_GRANT": 3,
		"COMBAT_RESULT_KIND_SHIELD_BREAK": 4,
	}
)

func (x CombatResultKind) Enum() *CombatResultKind {
	p := new(CombatResultKind)
	*p = x
	return p
}

func (x CombatResultKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CombatResultKind) Descriptor() protoreflect.EnumDescriptor {
	return file_thinhthan_v1_combat_proto_enumTypes[3].Descriptor()
}

func (CombatResultKind) Type() protoreflect.EnumType {
	return &file_thinhthan_v1_combat_proto_enumTypes[3]
}

func (x CombatResultKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CombatResultKind.Descriptor instead.
func (CombatResultKind) EnumDescriptor() ([]byte, []int) {
	return file_thinhthan_v1_combat_proto_rawDescGZIP(), []int{3}
}

// CombatOutcome — hit-resolution outcome (304).
type CombatOutcome int32

const (
	CombatOutcome_COMBAT_OUTCOME_UNSPECIFIED  CombatOutcome = 0
	CombatOutcome_COMBAT_OUTCOME_HIT          CombatOutcome = 1
	CombatOutcome_COMBAT_OUTCOME_DODGED       CombatOutcome = 2
	CombatOutcome_COMBAT_OUTCOME_INVULNERABLE CombatOutcome = 3 // respawn protection; damage 0
)

// Enum value maps for CombatOutcome.
var (
	CombatOutcome_name = map[int32]string{
		0: "COMBAT_OUTCOME_UNSPECIFIED",
		1: "COMBAT_OUTCOME_HIT",
		2: "COMBAT_OUTCOME_DODGED",
		3: "COMBAT_OUTCOME_INVULNERABLE",
	}
	CombatOutcome_value = map[string]int32{
		"COMBAT_OUTCOME_UNSPECIFIED":  0,
		"COMBAT_OUTCOME_HIT":          1,
		"COMBAT_OUTCOME_DODGED":       2,
		"COMBAT_OUTCOME_INVULNERABLE": 3,
	}
)

func (x CombatOutcome) Enum() *CombatOutcome {
	p := new(CombatOutcome)
	*p = x
	return p
}

func (x CombatOutcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CombatOutcome) Descriptor() protoreflect.EnumDescriptor {
	return file_thinhthan_v1_combat_proto_enumTypes[4].Descriptor()
}

func (CombatOutcome) Type() protoreflect.EnumType {
	return &file_thinhthan_v1_combat_proto_enumTypes[4]
}

func (x CombatOutcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CombatOutcome.Descriptor instead.
func (CombatOutcome) EnumDescriptor() ([]byte, []int) {
	return file_thinhthan_v1_combat_proto_rawDescGZIP(), []int{4}
}

// EncounterEventType — encounter lifecycle event classes (305).
type EncounterEventType int32

const (
	EncounterEventType_ENCOUNTER_EVENT_TYPE_UNSPECIFIED         EncounterEventType = 0
	EncounterEventType_ENCOUNTER_EVENT_TYPE_PHASE_TRANSITION    EncounterEventType = 1
	EncounterEventType_ENCOUNTER_EVENT_TYPE_TELEGRAPH_START     EncounterEventType = 2
	EncounterEventType_ENCOUNTER_EVENT_TYPE_TELEGRAPH_END       EncounterEventType = 3
	EncounterEventType_ENCOUNTER_EVENT_TYPE_MECHANIC_TRIGGERED  EncounterEventType = 4
	EncounterEventType_ENCOUNTER_EVENT_TYPE_MECHANIC_EXPIRED    EncounterEventType = 5
	EncounterEventType_ENCOUNTER_EVENT_TYPE_VULNERABILITY_OPEN  EncounterEventType = 6
	EncounterEventType_ENCOUNTER_EVENT_TYPE_VULNERABILITY_CLOSE EncounterEventType = 7
)

// Enum value maps for EncounterEventType.
var (
	EncounterEventType_name = map[int32]string{
		0: "ENCOUNTER_EVENT_TYPE_UNSPECIFIED",
		1: "ENCOUNTER_EVENT_TYPE_PHASE_TRANSITION",
		2: "ENCOUNTER_EVENT_TYPE_TELEGRAPH_START",
		3: "ENCOUNTER_EVENT_TYPE_TELEGRAPH_END",
		4: "ENCOUNTER_EVENT_TYPE_MECHANIC_TRIGGERED",
		5: "ENCOUNTER_EVENT_TYPE_MECHANIC_EXPIRED",
		6: "ENCOUNTER_EVENT_TYPE_VULNERABILITY_OPEN",
		7: "ENCOUNTER_EVENT_TYPE_VULNERABILITY_CLOSE",
	}
	EncounterEventType_value = map[string]int32{
		"ENCOUNTER_EVENT_TYPE_UNSPECIFIED":         0,
		"ENCOUNTER_EVENT_TYPE_PHASE_TRANSITION":    1,
		"ENCOUNTER_EVENT_TYPE_TELEGRAPH_START":     2,
		"ENCOUNTER_EVENT_TYPE_TELEGRAPH_END":       3,
		"ENCOUNTER_EVENT_TYPE_MECHANIC_TRIGGERED":  4,
		"ENCOUNTER_EVENT_TYPE_MECHANIC_EXPIRED":    5,
		"ENCOUNTER_EVENT_TYPE_VULNERABILITY_OPEN":  6,
		"ENCOUNTER_EVENT_TYPE_VULNERABILITY_CLOSE": 7,
	}
)

func (x EncounterEventType) Enum() *EncounterEventType {
	p := new(EncounterEventType)
	*p = x
	return p
}

func (x EncounterEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EncounterEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_thinhthan_v1_combat_proto_enumTypes[5].Descriptor()
}

func (EncounterEventType) Type() protoreflect.EnumType {
	return &file_thinhthan_v1_combat_proto_enumTypes[5]
}

func (x EncounterEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EncounterEventType.Descriptor instead.
func (EncounterEventType) EnumDescriptor() ([]byte, []int) {
	return file_thinhthan_v1_combat_proto_rawDescGZIP(), []int{5}
}

// C2S_SKILL_USE (200) — active-skill intent.
type C2S_SKILL_USE struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ClientMonoMs   uint64                 `protobuf:"varint,1,opt,name=client_mono_ms,json=clientMonoMs,proto3" json:"client_mono_ms,omitempty"` // advisory only
	SkillId        string                 `protobuf:"bytes,2,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"`                   // content ID
	Facing         Facing                 `protobuf:"varint,3,opt,name=facing,proto3,enum=thinhthan.v1.Facing" json:"facing,omitempty"`
	TargetEntityId uint64                 `protobuf:"varint,4,opt,name=target_entity_id,json=targetEntityId,proto3" json:"target_entity_id,omitempty"`  // 0 = none; SINGLE_TARGET requires it
	AreaCenterXMm  int32                  `protobuf:"zigzag32,5,opt,name=area_center_x_mm,json=areaCenterXMm,proto3" json:"area_center_x_mm,omitempty"` // AREA_POSITION only; ignored otherwise
	AreaCenterYMm  int32                  `protobuf:"zigzag32,6,opt,name=area_center_y_mm,json=areaCenterYMm,proto3" json:"area_center_y_mm,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *C2S_SKILL_USE) Reset() {
	*x = C2S_SKILL_USE{}
	mi := &file_thinhthan_v1_combat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_SKILL_USE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_SKILL_USE) ProtoMessage() {}

func (x *C2S_SKILL_USE) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_combat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_SKILL_USE.ProtoReflect.Descriptor instead.
func (*C2S_SKILL_USE) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_combat_proto_rawDescGZIP(), []int{0}
}

func (x *C2S_SKILL_USE) GetClientMonoMs() uint64 {
	if x != nil {
		return x.ClientMonoMs
	}
	return 0
}

func (x *C2S_SKILL_USE) GetSkillId() string {
	if x != nil {
		return x.SkillId
	}
	return ""
}

func (x *C2S_SKILL_USE) GetFacing() Facing {
	if x != nil {
		return x.Facing
	}
	return Facing_FACING_UNSPECIFIED
}

func (x *C2S_SKILL_USE) GetTargetEntityId() uint64 {
	if x != nil {
		return x.TargetEntityId
	}
	return 0
}

func (x *C2S_SKILL_USE) GetAreaCenterXMm() int32 {
	if x != nil {
		return x.AreaCenterXMm
	}
	return 0
}

func (x *C2S_SKILL_USE) GetAreaCenterYMm() int32 {
	if x != nil {
		return x.AreaCenterYMm
	}
	return 0
}

// C2S_BASIC_ATTACK (201) — the equipped basic attack; the client never names
// a basic skill_id.
type C2S_BASIC_ATTACK struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ClientMonoMs   uint64                 `protobuf:"varint,1,opt,name=client_mono_ms,json=clientMonoMs,proto3" json:"client_mono_ms,omitempty"` // advisory only
	Facing         Facing                 `protobuf:"varint,2,opt,name=facing,proto3,enum=thinhthan.v1.Facing" json:"facing,omitempty"`
	TargetEntityId uint64                 `protobuf:"varint,3,opt,name=target_entity_id,json=targetEntityId,proto3" json:"target_entity_id,omitempty"` // 0 = none
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *C2S_BASIC_ATTACK) Reset() {
	*x = C2S_BASIC_ATTACK{}
	mi := &file_thinhthan_v1_combat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_BASIC_ATTACK) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_BASIC_ATTACK) ProtoMessage() {}

func (x *C2S_BASIC_ATTACK) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_combat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_BASIC_ATTACK.ProtoReflect.Descriptor instead.
func (*C2S_BASIC_ATTACK) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_combat_proto_rawDescGZIP(), []int{1}
}

func (x *C2S_BASIC_ATTACK) GetClientMonoMs() uint64 {
	if x != nil {
		return x.ClientMonoMs
	}
	return 0
}

func (x *C2S_BASIC_ATTACK) GetFacing() Facing {
	if x != nil {
		return x.Facing
	}
	return Facing_FACING_UNSPECIFIED
}

func (x *C2S_BASIC_ATTACK) GetTargetEntityId() uint64 {
	if x != nil {
		return x.TargetEntityId
	}
	return 0
}

// C2S_TARGET_INTENT (202) — the only way to set a target; client-side cycling
// always sends 202 and waits for the stored target in the state push.
type C2S_TARGET_INTENT struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TargetEntityId uint64                 `protobuf:"varint,1,opt,name=target_entity_id,json=targetEntityId,proto3" json:"target_entity_id,omitempty"` // 0 = clear target
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *C2S_TARGET_INTENT) Reset() {
	*x = C2S_TARGET_INTENT{}
	mi := &file_thinhthan_v1_combat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_TARGET_INTENT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_TARGET_INTENT) ProtoMessage() {}

func (x *C2S_TARGET_INTENT) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_combat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_TARGET_INTENT.ProtoReflect.Descriptor instead.
func (*C2S_TARGET_INTENT) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_combat_proto_rawDescGZIP(), []int{2}
}

func (x *C2S_TARGET_INTENT) GetTargetEntityId() uint64 {
	if x != nil {
		return x.TargetEntityId
	}
	return 0
}

// S2C_ACTION_STARTED (203) — the server accepted an action.
type S2C_ACTION_STARTED struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ActionInstanceId uint64                 `protobuf:"varint,1,opt,name=action_instance_id,json=actionInstanceId,proto3" json:"action_instance_id,omitempty"`
	SourceEntityId   uint64                 `protobuf:"varint,2,opt,name=source_entity_id,json=sourceEntityId,proto3" json:"source_entity_id,omitempty"`
	SkillId          string                 `protobuf:"bytes,3,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"`        // content ID
	ClientSeq        uint64                 `protobuf:"varint,4,opt,name=client_seq,json=clientSeq,proto3" json:"client_seq,omitempty"` // echo of the request envelope
	// client_seq; 0 for server-originated
	ServerTick         uint64 `protobuf:"varint,5,opt,name=server_tick,json=serverTick,proto3" json:"server_tick,omitempty"`
	Facing             Facing `protobuf:"varint,6,opt,name=facing,proto3,enum=thinhthan.v1.Facing" json:"facing,omitempty"`
	TargetEntityId     uint64 `protobuf:"varint,7,opt,name=target_entity_id,json=targetEntityId,proto3" json:"target_entity_id,omitempty"`
	AreaCenterXMm      int32  `protobuf:"zigzag32,8,opt,name=area_center_x_mm,json=areaCenterXMm,proto3" json:"area_center_x_mm,omitempty"`
	AreaCenterYMm      int32  `protobuf:"zigzag32,9,opt,name=area_center_y_mm,json=areaCenterYMm,proto3" json:"area_center_y_mm,omitempty"`
	CastMs             uint32 `protobuf:"varint,10,opt,name=cast_ms,json=castMs,proto3" json:"cast_ms,omitempty"`
	CooldownEndsAtTick uint64 `protobuf:"varint,11,opt,name=cooldown_ends_at_tick,json=cooldownEndsAtTick,proto3" json:"cooldown_ends_at_tick,omitempty"`
	MpAfter            int64  `protobuf:"varint,12,opt,name=mp_after,json=mpAfter,proto3" json:"mp_after,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *S2C_ACTION_STARTED) Reset() {
	*x = S2C_ACTION_STARTED{}
	mi := &file_thinhthan_v1_combat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_ACTION_STARTED) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_ACTION_STARTED) ProtoMessage() {}

func (x *S2C_ACTION_STARTED) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_combat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_ACTION_STARTED.ProtoReflect.Descriptor instead.
func (*S2C_ACTION_STARTED) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_combat_proto_rawDescGZIP(), []int{3}
}

func (x *S2C_ACTION_STARTED) GetActionInstanceId() uint64 {
	if x != nil {
		return x.ActionInstanceId
	}
	return 0
}

func (x *S2C_ACTION_STARTED) GetSourceEntityId() uint64 {
	if x != nil {
		return x.SourceEntityId
	}
	return 0
}

func (x *S2C_ACTION_STARTED) GetSkillId() string {
	if x != nil {
		return x.SkillId
	}
	return ""
}

func (x *S2C_ACTION_STARTED) GetClientSeq() uint64 {
	if x != nil {
		return x.ClientSeq
	}
	return 0
}

func (x *S2C_ACTION_STARTED) GetServerTick() uint64 {
	if x != nil {
		return x.ServerTick
	}
	return 0
}

func (x *S2C_ACTION_STARTED) GetFacing() Facing {
	if x != nil {
		return x.Facing
	}
	return Facing_FACING_UNSPECIFIED
}

func (x *S2C_ACTION_STARTED) GetTargetEntityId() uint64 {
	if x != nil {
		return x.TargetEntityId
	}
	return 0
}

func (x *S2C_ACTION_STARTED) GetAreaCenterXMm() int32 {
	if x != nil {
		return x.AreaCenterXMm
	}
	return 0
}

func (x *S2C_ACTION_STARTED) GetAreaCenterYMm() int32 {
	if x != nil {
		return x.AreaCenterYMm
	}
	return 0
}

func (x *S2C_ACTION_STARTED) GetCastMs() uint32 {
	if x != nil {
		return x.CastMs
	}
	return 0
}

func (x *S2C_ACTION_STARTED) GetCooldownEndsAtTick() uint64 {
	if x != nil {
		return x.CooldownEndsAtTick
	}
	return 0
}

func (x *S2C_ACTION_STARTED) GetMpAfter() int64 {
	if x != nil {
		return x.MpAfter
	}
	return 0
}

// S2C_ACTION_REJECTED (204) — echoes the request envelope's client_seq.
type S2C_ACTION_REJECTED struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ClientSeq        uint64                 `protobuf:"varint,1,opt,name=client_seq,json=clientSeq,proto3" json:"client_seq,omitempty"`                             // echo of the request envelope
	RequestMessageId uint32                 `protobuf:"varint,2,opt,name=request_message_id,json=requestMessageId,proto3" json:"request_message_id,omitempty"`      // 200 | 201 | 202 | 208
	OperationId      []byte                 `protobuf:"bytes,3,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`                        // 208 only; UUID, 16 bytes
	SkillId          string                 `protobuf:"bytes,4,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"`                                    // content ID
	ErrorCode        ErrorCode              `protobuf:"varint,5,opt,name=error_code,json=errorCode,proto3,enum=thinhthan.v1.ErrorCode" json:"error_code,omitempty"` // COOLDOWN_ACTIVE | INSUFFICIENT_MP |
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *S2C_ACTION_REJECTED) Reset() {
	*x = S2C_ACTION_REJECTED{}
	mi := &file_thinhthan_v1_combat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_ACTION_REJECTED) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_ACTION_REJECTED) ProtoMessage() {}

func (x *S2C_ACTION_REJECTED) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_combat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_ACTION_REJECTED.ProtoReflect.Descriptor instead.
func (*S2C_ACTION_REJECTED) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_combat_proto_rawDescGZIP(), []int{4}
}

func (x *S2C_ACTION_REJECTED) GetClientSeq() uint64 {
	if x != nil {
		return x.ClientSeq
	}
	return 0
}

func (x *S2C_ACTION_REJECTED) GetRequestMessageId() uint32 {
	if x != nil {
		return x.RequestMessageId
	}
	return 0
}

func (x *S2C_ACTION_REJECTED) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

func (x *S2C_ACTION_REJECTED) GetSkillId() string {
	if x != nil {
		return x.SkillId
	}
	return ""
}

func (x *S2C_ACTION_REJECTED) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

// S2C_STATUS_EVENT (205) — status lifecycle on a target.
type S2C_STATUS_EVENT struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TargetEntityId uint64                 `protobuf:"varint,1,opt,name=target_entity_id,json=targetEntityId,proto3" json:"target_entity_id,omitempty"`
	SourceEntityId uint64                 `protobuf:"varint,2,opt,name=source_entity_id,json=sourceEntityId,proto3" json:"source_entity_id,omitempty"`
	EffectId       string                 `protobuf:"bytes,3,opt,name=effect_id,json=effectId,proto3" json:"effect_id,omitempty"`       // content ID (status_effects.md)
	StatusKind     string                 `protobuf:"bytes,4,opt,name=status_kind,json=statusKind,proto3" json:"status_kind,omitempty"` // status kind (status_effects.md)
	Event          StatusEventKind        `protobuf:"varint,5,opt,name=event,proto3,enum=thinhthan.v1.StatusEventKind" json:"event,omitempty"`
	Stacks         uint32                 `protobuf:"varint,6,opt,name=stacks,proto3" json:"stacks,omitempty"`
	ExpiresAtTick  uint64                 `protobuf:"varint,7,opt,name=expires_at_tick,json=expiresAtTick,proto3" json:"expires_at_tick,omitempty"`
	ServerTick     uint64                 `protobuf:"varint,8,opt,name=server_tick,json=serverTick,proto3" json:"server_tick,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *S2C_STATUS_EVENT) Reset() {
	*x = S2C_STATUS_EVENT{}
	mi := &file_thinhthan_v1_combat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_STATUS_EVENT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_STATUS_EVENT) ProtoMessage() {}

func (x *S2C_STATUS_EVENT) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_combat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_STATUS_EVENT.ProtoReflect.Descriptor instead.
func (*S2C_STATUS_EVENT) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_combat_proto_rawDescGZIP(), []int{5}
}

func (x *S2C_STATUS_EVENT) GetTargetEntityId() uint64 {
	if x != nil {
		return x.TargetEntityId
	}
	return 0
}

func (x *S2C_STATUS_EVENT) GetSourceEntityId() uint64 {
	if x != nil {
		return x.SourceEntityId
	}
	return 0
}

func (x *S2C_STATUS_EVENT) GetEffectId() string {
	if x != nil {
		return x.EffectId
	}
	return ""
}

func (x *S2C_STATUS_EVENT) GetStatusKind() string {
	if x != nil {
		return x.StatusKind
	}
	return ""
}

func (x *S2C_STATUS_EVENT) GetEvent() StatusEventKind {
	if x != nil {
		return x.Event
	}
	return StatusEventKind_STATUS_EVENT_KIND_UNSPECIFIED
}

func (x *S2C_STATUS_EVENT) GetStacks() uint32 {
	if x != nil {
		return x.Stacks
	}
	return 0
}

func (x *S2C_STATUS_EVENT) GetExpiresAtTick() uint64 {
	if x != nil {
		return x.ExpiresAtTick
	}
	return 0
}

func (x *S2C_STATUS_EVENT) GetServerTick() uint64 {
	if x != nil {
		return x.ServerTick
	}
	return 0
}

// S2C_DEATH (206).
type S2C_DEATH struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	EntityId               uint64                 `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	KillerEntityId         uint64                 `protobuf:"varint,2,opt,name=killer_entity_id,json=killerEntityId,proto3" json:"killer_entity_id,omitempty"` // 0 = none
	ServerTick             uint64                 `protobuf:"varint,3,opt,name=server_tick,json=serverTick,proto3" json:"server_tick,omitempty"`
	RespawnAvailableAtTick uint64                 `protobuf:"varint,4,opt,name=respawn_available_at_tick,json=respawnAvailableAtTick,proto3" json:"respawn_available_at_tick,omitempty"` // 0 when server-driven (dungeon/PvP/
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *S2C_DEATH) Reset() {
	*x = S2C_DEATH{}
	mi := &file_thinhthan_v1_combat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_DEATH) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_DEATH) ProtoMessage() {}

func (x *S2C_DEATH) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_combat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_DEATH.ProtoReflect.Descriptor instead.
func (*S2C_DEATH) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_combat_proto_rawDescGZIP(), []int{6}
}

func (x *S2C_DEATH) GetEntityId() uint64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *S2C_DEATH) GetKillerEntityId() uint64 {
	if x != nil {
		return x.KillerEntityId
	}
	return 0
}

func (x *S2C_DEATH) GetServerTick() uint64 {
	if x != nil {
		return x.ServerTick
	}
	return 0
}

func (x *S2C_DEATH) GetRespawnAvailableAtTick() uint64 {
	if x != nil {
		return x.RespawnAvailableAtTick
	}
	return 0
}

// S2C_RESPAWN (207) — also the committed answer to a successful 208.
type S2C_RESPAWN struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	EntityId              uint64                 `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	MapId                 string                 `protobuf:"bytes,2,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`                      // content ID
	CheckpointId          string                 `protobuf:"bytes,3,opt,name=checkpoint_id,json=checkpointId,proto3" json:"checkpoint_id,omitempty"` // content ID
	XMm                   int32                  `protobuf:"zigzag32,4,opt,name=x_mm,json=xMm,proto3" json:"x_mm,omitempty"`
	YMm                   int32                  `protobuf:"zigzag32,5,opt,name=y_mm,json=yMm,proto3" json:"y_mm,omitempty"`
	HpAfter               int64                  `protobuf:"varint,6,opt,name=hp_after,json=hpAfter,proto3" json:"hp_after,omitempty"`
	MpAfter               int64                  `protobuf:"varint,7,opt,name=mp_after,json=mpAfter,proto3" json:"mp_after,omitempty"`
	InvulnerableUntilTick uint64                 `protobuf:"varint,8,opt,name=invulnerable_until_tick,json=invulnerableUntilTick,proto3" json:"invulnerable_until_tick,omitempty"`
	ServerTick            uint64                 `protobuf:"varint,9,opt,name=server_tick,json=serverTick,proto3" json:"server_tick,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *S2C_RESPAWN) Reset() {
	*x = S2C_RESPAWN{}
	mi := &file_thinhthan_v1_combat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_RESPAWN) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_RESPAWN) ProtoMessage() {}

func (x *S2C_RESPAWN) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_combat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_RESPAWN.ProtoReflect.Descriptor instead.
func (*S2C_RESPAWN) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_combat_proto_rawDescGZIP(), []int{7}
}

func (x *S2C_RESPAWN) GetEntityId() uint64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *S2C_RESPAWN) GetMapId() string {
	if x != nil {
		return x.MapId
	}
	return ""
}

func (x *S2C_RESPAWN) GetCheckpointId() string {
	if x != nil {
		return x.CheckpointId
	}
	return ""
}

func (x *S2C_RESPAWN) GetXMm() int32 {
	if x != nil {
		return x.XMm
	}
	return 0
}

func (x *S2C_RESPAWN) GetYMm() int32 {
	if x != nil {
		return x.YMm
	}
	return 0
}

func (x *S2C_RESPAWN) GetHpAfter() int64 {
	if x != nil {
		return x.HpAfter
	}
	return 0
}

func (x *S2C_RESPAWN) GetMpAfter() int64 {
	if x != nil {
		return x.MpAfter
	}
	return 0
}

func (x *S2C_RESPAWN) GetInvulnerableUntilTick() uint64 {
	if x != nil {
		return x.InvulnerableUntilTick
	}
	return 0
}

func (x *S2C_RESPAWN) GetServerTick() uint64 {
	if x != nil {
		return x.ServerTick
	}
	return 0
}

// C2S_RESPAWN_REQUEST (208) — valid only for a DEAD character in the normal
// world once server_tick >= respawn_available_at_tick; rejection is 204,
// forced-placement wait is 15.
type C2S_RESPAWN_REQUEST struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   []byte                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"` // UUID, 16 bytes — retry-safe; re-answer is the
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S_RESPAWN_REQUEST) Reset() {
	*x = C2S_RESPAWN_REQUEST{}
	mi := &file_thinhthan_v1_combat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_RESPAWN_REQUEST) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_RESPAWN_REQUEST) ProtoMessage() {}

func (x *C2S_RESPAWN_REQUEST) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_combat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_RESPAWN_REQUEST.ProtoReflect.Descriptor instead.
func (*C2S_RESPAWN_REQUEST) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_combat_proto_rawDescGZIP(), []int{8}
}

func (x *C2S_RESPAWN_REQUEST) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

// EncounterView — one active encounter inside S2C_WORLD_BASELINE (300).
type EncounterView struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	EncounterId        uint64                 `protobuf:"varint,1,opt,name=encounter_id,json=encounterId,proto3" json:"encounter_id,omitempty"`
	EncounterContentId string                 `protobuf:"bytes,2,opt,name=encounter_content_id,json=encounterContentId,proto3" json:"encounter_content_id,omitempty"` // content ID
	PhaseNumber        uint32                 `protobuf:"varint,3,opt,name=phase_number,json=phaseNumber,proto3" json:"phase_number,omitempty"`
	ActiveMechanicIds  []uint32               `protobuf:"varint,4,rep,packed,name=active_mechanic_ids,json=activeMechanicIds,proto3" json:"active_mechanic_ids,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *EncounterView) Reset() {
	*x = EncounterView{}
	mi := &file_thinhthan_v1_combat_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncounterView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncounterView) ProtoMessage() {}

func (x *EncounterView) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_combat_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncounterView.ProtoReflect.Descriptor instead.
func (*EncounterView) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_combat_proto_rawDescGZIP(), []int{9}
}

func (x *EncounterView) GetEncounterId() uint64 {
	if x != nil {
		return x.EncounterId
	}
	return 0
}

func (x *EncounterView) GetEncounterContentId() string {
	if x != nil {
		return x.EncounterContentId
	}
	return ""
}

func (x *EncounterView) GetPhaseNumber() uint32 {
	if x != nil {
		return x.PhaseNumber
	}
	return 0
}

func (x *EncounterView) GetActiveMechanicIds() []uint32 {
	if x != nil {
		return x.ActiveMechanicIds
	}
	return nil
}

// S2C_WORLD_BASELINE (300) — full AOI baseline (synchronization.md).
type S2C_WORLD_BASELINE struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BaselineId      uint64                 `protobuf:"varint,1,opt,name=baseline_id,json=baselineId,proto3" json:"baseline_id,omitempty"`
	ServerTick      uint64                 `protobuf:"varint,2,opt,name=server_tick,json=serverTick,proto3" json:"server_tick,omitempty"`
	MapId           string                 `protobuf:"bytes,3,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"` // content ID
	ChannelIndex    uint32                 `protobuf:"varint,4,opt,name=channel_index,json=channelIndex,proto3" json:"channel_index,omitempty"`
	InstanceId      []byte                 `protobuf:"bytes,5,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"` // 16 bytes; empty in the normal world
	ContentRevision string                 `protobuf:"bytes,6,opt,name=content_revision,json=contentRevision,proto3" json:"content_revision,omitempty"`
	Self            *EntityState           `protobuf:"bytes,7,opt,name=self,proto3" json:"self,omitempty"`
	Entities        []*EntityState         `protobuf:"bytes,8,rep,name=entities,proto3" json:"entities,omitempty"` // AOI set, <= MAX_ENTITIES_IN_AOI_PER_CLIENT
	Encounters      []*EncounterView       `protobuf:"bytes,9,rep,name=encounters,proto3" json:"encounters,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *S2C_WORLD_BASELINE) Reset() {
	*x = S2C_WORLD_BASELINE{}
	mi := &file_thinhthan_v1_combat_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_WORLD_BASELINE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_WORLD_BASELINE) ProtoMessage() {}

func (x *S2C_WORLD_BASELINE) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_combat_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_WORLD_BASELINE.ProtoReflect.Descriptor instead.
func (*S2C_WORLD_BASELINE) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_combat_proto_rawDescGZIP(), []int{10}
}

func (x *S2C_WORLD_BASELINE) GetBaselineId() uint64 {
	if x != nil {
		return x.BaselineId
	}
	return 0
}

func (x *S2C_WORLD_BASELINE) GetServerTick() uint64 {
	if x != nil {
		return x.ServerTick
	}
	return 0
}

func (x *S2C_WORLD_BASELINE) GetMapId() string {
	if x != nil {
		return x.MapId
	}
	return ""
}

func (x *S2C_WORLD_BASELINE) GetChannelIndex() uint32 {
	if x != nil {
		return x.ChannelIndex
	}
	return 0
}

func (x *S2C_WORLD_BASELINE) GetInstanceId() []byte {
	if x != nil {
		return x.InstanceId
	}
	return nil
}

func (x *S2C_WORLD_BASELINE) GetContentRevision() string {
	if x != nil {
		return x.ContentRevision
	}
	return ""
}

func (x *S2C_WORLD_BASELINE) GetSelf() *EntityState {
	if x != nil {
		return x.Self
	}
	return nil
}

func (x *S2C_WORLD_BASELINE) GetEntities() []*EntityState {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *S2C_WORLD_BASELINE) GetEncounters() []*EncounterView {
	if x != nil {
		return x.Encounters
	}
	return nil
}

// S2C_ENTITY_SPAWN (301).
type S2C_ENTITY_SPAWN struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaselineId    uint64                 `protobuf:"varint,1,opt,name=baseline_id,json=baselineId,proto3" json:"baseline_id,omitempty"`
	ServerTick    uint64                 `protobuf:"varint,2,opt,name=server_tick,json=serverTick,proto3" json:"server_tick,omitempty"`
	Entity        *EntityState           `protobuf:"bytes,3,opt,name=entity,proto3" json:"entity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C_ENTITY_SPAWN) Reset() {
	*x = S2C_ENTITY_SPAWN{}
	mi := &file_thinhthan_v1_combat_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_ENTITY_SPAWN) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_ENTITY_SPAWN) ProtoMessage() {}

func (x *S2C_ENTITY_SPAWN) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_combat_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_ENTITY_SPAWN.ProtoReflect.Descriptor instead.
func (*S2C_ENTITY_SPAWN) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_combat_proto_rawDescGZIP(), []int{11}
}

func (x *S2C_ENTITY_SPAWN) GetBaselineId() uint64 {
	if x != nil {
		return x.BaselineId
	}
	return 0
}

func (x *S2C_ENTITY_SPAWN) GetServerTick() uint64 {
	if x != nil {
		return x.ServerTick
	}
	return 0
}

func (x *S2C_ENTITY_SPAWN) GetEntity() *EntityState {
	if x != nil {
		return x.Entity
	}
	return nil
}

// S2C_ENTITY_DESPAWN (302).
type S2C_ENTITY_DESPAWN struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaselineId    uint64                 `protobuf:"varint,1,opt,name=baseline_id,json=baselineId,proto3" json:"baseline_id,omitempty"`
	ServerTick    uint64                 `protobuf:"varint,2,opt,name=server_tick,json=serverTick,proto3" json:"server_tick,omitempty"`
	EntityId      uint64                 `protobuf:"varint,3,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Reason        DespawnReason          `protobuf:"varint,4,opt,name=reason,proto3,enum=thinhthan.v1.DespawnReason" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C_ENTITY_DESPAWN) Reset() {
	*x = S2C_ENTITY_DESPAWN{}
	mi := &file_thinhthan_v1_combat_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_ENTITY_DESPAWN) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_ENTITY_DESPAWN) ProtoMessage() {}

func (x *S2C_ENTITY_DESPAWN) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_combat_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_ENTITY_DESPAWN.ProtoReflect.Descriptor instead.
func (*S2C_ENTITY_DESPAWN) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_combat_proto_rawDescGZIP(), []int{12}
}

func (x *S2C_ENTITY_DESPAWN) GetBaselineId() uint64 {
	if x != nil {
		return x.BaselineId
	}
	return 0
}

func (x *S2C_ENTITY_DESPAWN) GetServerTick() uint64 {
	if x != nil {
		return x.ServerTick
	}
	return 0
}

func (x *S2C_ENTITY_DESPAWN) GetEntityId() uint64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *S2C_ENTITY_DESPAWN) GetReason() DespawnReason {
	if x != nil {
		return x.Reason
	}
	return DespawnReason_DESPAWN_REASON_UNSPECIFIED
}

// SelfAck — authoritative self state after the last processed input; used by
// client reconciliation (synchronization.md § Local Reconciliation).
type SelfAck struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	LastProcessedClientSeq uint64                 `protobuf:"varint,1,opt,name=last_processed_client_seq,json=lastProcessedClientSeq,proto3" json:"last_processed_client_seq,omitempty"`
	XMm                    int32                  `protobuf:"zigzag32,2,opt,name=x_mm,json=xMm,proto3" json:"x_mm,omitempty"`
	YMm                    int32                  `protobuf:"zigzag32,3,opt,name=y_mm,json=yMm,proto3" json:"y_mm,omitempty"`
	VxMmS                  int32                  `protobuf:"zigzag32,4,opt,name=vx_mm_s,json=vxMmS,proto3" json:"vx_mm_s,omitempty"`
	VyMmS                  int32                  `protobuf:"zigzag32,5,opt,name=vy_mm_s,json=vyMmS,proto3" json:"vy_mm_s,omitempty"`
	MovementState          MovementState          `protobuf:"varint,6,opt,name=movement_state,json=movementState,proto3,enum=thinhthan.v1.MovementState" json:"movement_state,omitempty"`
	PlatformId             string                 `protobuf:"bytes,7,opt,name=platform_id,json=platformId,proto3" json:"platform_id,omitempty"` // empty = none
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SelfAck) Reset() {
	*x = SelfAck{}
	mi := &file_thinhthan_v1_combat_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelfAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelfAck) ProtoMessage() {}

func (x *SelfAck) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_combat_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelfAck.ProtoReflect.Descriptor instead.
func (*SelfAck) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_combat_proto_rawDescGZIP(), []int{13}
}

func (x *SelfAck) GetLastProcessedClientSeq() uint64 {
	if x != nil {
		return x.LastProcessedClientSeq
	}
	return 0
}

func (x *SelfAck) GetXMm() int32 {
	if x != nil {
		return x.XMm
	}
	return 0
}

func (x *SelfAck) GetYMm() int32 {
	if x != nil {
		return x.YMm
	}
	return 0
}

func (x *SelfAck) GetVxMmS() int32 {
	if x != nil {
		return x.VxMmS
	}
	return 0
}

func (x *SelfAck) GetVyMmS() int32 {
	if x != nil {
		return x.VyMmS
	}
	return 0
}

func (x *SelfAck) GetMovementState() MovementState {
	if x != nil {
		return x.MovementState
	}
	return MovementState_MOVEMENT_STATE_UNSPECIFIED
}

func (x *SelfAck) GetPlatformId() string {
	if x != nil {
		return x.PlatformId
	}
	return ""
}

// StatusList / CosmeticList — repeated-field wrappers for EntityDelta
// (ADR-0069): absent = unchanged; present = full replacement (possibly empty).
// `optional repeated` does not exist, so the list is wrapped in a message.
type StatusList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*EntityStatusView    `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusList) Reset() {
	*x = StatusList{}
	mi := &file_thinhthan_v1_combat_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusList) ProtoMessage() {}

func (x *StatusList) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_combat_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusList.ProtoReflect.Descriptor instead.
func (*StatusList) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_combat_proto_rawDescGZIP(), []int{14}
}

func (x *StatusList) GetEntries() []*EntityStatusView {
	if x != nil {
		return x.Entries
	}
	return nil
}

type CosmeticList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*EquippedCosmetic    `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CosmeticList) Reset() {
	*x = CosmeticList{}
	mi := &file_thinhthan_v1_combat_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CosmeticList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CosmeticList) ProtoMessage() {}

func (x *CosmeticList) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_combat_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CosmeticList.ProtoReflect.Descriptor instead.
func (*CosmeticList) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_combat_proto_rawDescGZIP(), []int{15}
}

func (x *CosmeticList) GetEntries() []*EquippedCosmetic {
	if x != nil {
		return x.Entries
	}
	return nil
}

// EntityDelta — per-entity delta inside 303. Every scalar EntityState field
// except entity_id/entity_kind/content_id/character_id is proto3 `optional`
// (absent = unchanged).
type EntityDelta struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	EntityId            uint64                 `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	DisplayName         *string                `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3,oneof" json:"display_name,omitempty"`
	Level               *uint32                `protobuf:"varint,3,opt,name=level,proto3,oneof" json:"level,omitempty"`
	OwnerEntityId       *uint64                `protobuf:"varint,4,opt,name=owner_entity_id,json=ownerEntityId,proto3,oneof" json:"owner_entity_id,omitempty"`
	XMm                 *int32                 `protobuf:"zigzag32,5,opt,name=x_mm,json=xMm,proto3,oneof" json:"x_mm,omitempty"`
	YMm                 *int32                 `protobuf:"zigzag32,6,opt,name=y_mm,json=yMm,proto3,oneof" json:"y_mm,omitempty"`
	VxMmS               *int32                 `protobuf:"zigzag32,7,opt,name=vx_mm_s,json=vxMmS,proto3,oneof" json:"vx_mm_s,omitempty"`
	VyMmS               *int32                 `protobuf:"zigzag32,8,opt,name=vy_mm_s,json=vyMmS,proto3,oneof" json:"vy_mm_s,omitempty"`
	Facing              *Facing                `protobuf:"varint,9,opt,name=facing,proto3,enum=thinhthan.v1.Facing,oneof" json:"facing,omitempty"`
	MovementState       *MovementState         `protobuf:"varint,10,opt,name=movement_state,json=movementState,proto3,enum=thinhthan.v1.MovementState,oneof" json:"movement_state,omitempty"`
	Hp                  *int64                 `protobuf:"varint,11,opt,name=hp,proto3,oneof" json:"hp,omitempty"`
	MaxHp               *int64                 `protobuf:"varint,12,opt,name=max_hp,json=maxHp,proto3,oneof" json:"max_hp,omitempty"`
	Shield              *int64                 `protobuf:"varint,13,opt,name=shield,proto3,oneof" json:"shield,omitempty"`
	Flags               *uint32                `protobuf:"varint,14,opt,name=flags,proto3,oneof" json:"flags,omitempty"`
	Statuses            *StatusList            `protobuf:"bytes,15,opt,name=statuses,proto3" json:"statuses,omitempty"`                                            // absent = unchanged; present = replace
	EquippedCosmetics   *CosmeticList          `protobuf:"bytes,16,opt,name=equipped_cosmetics,json=equippedCosmetics,proto3" json:"equipped_cosmetics,omitempty"` // absent = unchanged; present = replace
	EncounterId         *uint64                `protobuf:"varint,17,opt,name=encounter_id,json=encounterId,proto3,oneof" json:"encounter_id,omitempty"`
	StatLifesteal       *uint32                `protobuf:"varint,18,opt,name=stat_lifesteal,json=statLifesteal,proto3,oneof" json:"stat_lifesteal,omitempty"`
	StatReflect         *uint32                `protobuf:"varint,19,opt,name=stat_reflect,json=statReflect,proto3,oneof" json:"stat_reflect,omitempty"`
	StatAbsorb          *uint32                `protobuf:"varint,20,opt,name=stat_absorb,json=statAbsorb,proto3,oneof" json:"stat_absorb,omitempty"`
	StatHealReduction   *uint32                `protobuf:"varint,21,opt,name=stat_heal_reduction,json=statHealReduction,proto3,oneof" json:"stat_heal_reduction,omitempty"`
	StatHealingReceived *uint32                `protobuf:"varint,22,opt,name=stat_healing_received,json=statHealingReceived,proto3,oneof" json:"stat_healing_received,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *EntityDelta) Reset() {
	*x = EntityDelta{}
	mi := &file_thinhthan_v1_combat_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityDelta) ProtoMessage() {}

func (x *EntityDelta) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_combat_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityDelta.ProtoReflect.Descriptor instead.
func (*EntityDelta) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_combat_proto_rawDescGZIP(), []int{16}
}

func (x *EntityDelta) GetEntityId() uint64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *EntityDelta) GetDisplayName() string {
	if x != nil && x.DisplayName != nil {
		return *x.DisplayName
	}
	return ""
}

func (x *EntityDelta) GetLevel() uint32 {
	if x != nil && x.Level != nil {
		return *x.Level
	}
	return 0
}

func (x *EntityDelta) GetOwnerEntityId() uint64 {
	if x != nil && x.OwnerEntityId != nil {
		return *x.OwnerEntityId
	}
	return 0
}

func (x *EntityDelta) GetXMm() int32 {
	if x != nil && x.XMm != nil {
		return *x.XMm
	}
	return 0
}

func (x *EntityDelta) GetYMm() int32 {
	if x != nil && x.YMm != nil {
		return *x.YMm
	}
	return 0
}

func (x *EntityDelta) GetVxMmS() int32 {
	if x != nil && x.VxMmS != nil {
		return *x.VxMmS
	}
	return 0
}

func (x *EntityDelta) GetVyMmS() int32 {
	if x != nil && x.VyMmS != nil {
		return *x.VyMmS
	}
	return 0
}

func (x *EntityDelta) GetFacing() Facing {
	if x != nil && x.Facing != nil {
		return *x.Facing
	}
	return Facing_FACING_UNSPECIFIED
}

func (x *EntityDelta) GetMovementState() MovementState {
	if x != nil && x.MovementState != nil {
		return *x.MovementState
	}
	return MovementState_MOVEMENT_STATE_UNSPECIFIED
}

func (x *EntityDelta) GetHp() int64 {
	if x != nil && x.Hp != nil {
		return *x.Hp
	}
	return 0
}

func (x *EntityDelta) GetMaxHp() int64 {
	if x != nil && x.MaxHp != nil {
		return *x.MaxHp
	}
	return 0
}

func (x *EntityDelta) GetShield() int64 {
	if x != nil && x.Shield != nil {
		return *x.Shield
	}
	return 0
}

func (x *EntityDelta) GetFlags() uint32 {
	if x != nil && x.Flags != nil {
		return *x.Flags
	}
	return 0
}

func (x *EntityDelta) GetStatuses() *StatusList {
	if x != nil {
		return x.Statuses
	}
	return nil
}

func (x *EntityDelta) GetEquippedCosmetics() *CosmeticList {
	if x != nil {
		return x.EquippedCosmetics
	}
	return nil
}

func (x *EntityDelta) GetEncounterId() uint64 {
	if x != nil && x.EncounterId != nil {
		return *x.EncounterId
	}
	return 0
}

func (x *EntityDelta) GetStatLifesteal() uint32 {
	if x != nil && x.StatLifesteal != nil {
		return *x.StatLifesteal
	}
	return 0
}

func (x *EntityDelta) GetStatReflect() uint32 {
	if x != nil && x.StatReflect != nil {
		return *x.StatReflect
	}
	return 0
}

func (x *EntityDelta) GetStatAbsorb() uint32 {
	if x != nil && x.StatAbsorb != nil {
		return *x.StatAbsorb
	}
	return 0
}

func (x *EntityDelta) GetStatHealReduction() uint32 {
	if x != nil && x.StatHealReduction != nil {
		return *x.StatHealReduction
	}
	return 0
}

func (x *EntityDelta) GetStatHealingReceived() uint32 {
	if x != nil && x.StatHealingReceived != nil {
		return *x.StatHealingReceived
	}
	return 0
}

// S2C_STATE_DELTA (303) — REPLACEABLE_STATE AOI delta.
type S2C_STATE_DELTA struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaselineId    uint64                 `protobuf:"varint,1,opt,name=baseline_id,json=baselineId,proto3" json:"baseline_id,omitempty"`
	ServerTick    uint64                 `protobuf:"varint,2,opt,name=server_tick,json=serverTick,proto3" json:"server_tick,omitempty"`
	SelfAck       *SelfAck               `protobuf:"bytes,3,opt,name=self_ack,json=selfAck,proto3" json:"self_ack,omitempty"` // always present
	Entities      []*EntityDelta         `protobuf:"bytes,4,rep,name=entities,proto3" json:"entities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C_STATE_DELTA) Reset() {
	*x = S2C_STATE_DELTA{}
	mi := &file_thinhthan_v1_combat_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_STATE_DELTA) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_STATE_DELTA) ProtoMessage() {}

func (x *S2C_STATE_DELTA) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_combat_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_STATE_DELTA.ProtoReflect.Descriptor instead.
func (*S2C_STATE_DELTA) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_combat_proto_rawDescGZIP(), []int{17}
}

func (x *S2C_STATE_DELTA) GetBaselineId() uint64 {
	if x != nil {
		return x.BaselineId
	}
	return 0
}

func (x *S2C_STATE_DELTA) GetServerTick() uint64 {
	if x != nil {
		return x.ServerTick
	}
	return 0
}

func (x *S2C_STATE_DELTA) GetSelfAck() *SelfAck {
	if x != nil {
		return x.SelfAck
	}
	return nil
}

func (x *S2C_STATE_DELTA) GetEntities() []*EntityDelta {
	if x != nil {
		return x.Entities
	}
	return nil
}

// S2C_COMBAT_EVENT (304) — combat event; secondary fields are present only
// when the corresponding secondary result occurred (absence = not triggered).
type S2C_COMBAT_EVENT struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	EventId          uint64                 `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"` // unique per partition
	ServerTick       uint64                 `protobuf:"varint,2,opt,name=server_tick,json=serverTick,proto3" json:"server_tick,omitempty"`
	ActionInstanceId uint64                 `protobuf:"varint,3,opt,name=action_instance_id,json=actionInstanceId,proto3" json:"action_instance_id,omitempty"`
	SourceEntityId   uint64                 `protobuf:"varint,4,opt,name=source_entity_id,json=sourceEntityId,proto3" json:"source_entity_id,omitempty"`
	TargetEntityId   uint64                 `protobuf:"varint,5,opt,name=target_entity_id,json=targetEntityId,proto3" json:"target_entity_id,omitempty"`
	SkillId          string                 `protobuf:"bytes,6,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"`    // empty for effect ticks
	EffectId         string                 `protobuf:"bytes,7,opt,name=effect_id,json=effectId,proto3" json:"effect_id,omitempty"` // DoT/HoT/shield/reflect source; empty
	// for direct hits
	ResultKind           CombatResultKind `protobuf:"varint,8,opt,name=result_kind,json=resultKind,proto3,enum=thinhthan.v1.CombatResultKind" json:"result_kind,omitempty"`
	Outcome              CombatOutcome    `protobuf:"varint,9,opt,name=outcome,proto3,enum=thinhthan.v1.CombatOutcome" json:"outcome,omitempty"`
	IsCrit               bool             `protobuf:"varint,10,opt,name=is_crit,json=isCrit,proto3" json:"is_crit,omitempty"`
	DamageElement        DamageElement    `protobuf:"varint,11,opt,name=damage_element,json=damageElement,proto3,enum=thinhthan.v1.DamageElement" json:"damage_element,omitempty"`
	PostMitigationDamage int64            `protobuf:"varint,12,opt,name=post_mitigation_damage,json=postMitigationDamage,proto3" json:"post_mitigation_damage,omitempty"` // >= 0 (combat.md § Damage terms)
	ShieldAbsorbed       int64            `protobuf:"varint,13,opt,name=shield_absorbed,json=shieldAbsorbed,proto3" json:"shield_absorbed,omitempty"`                     // >= 0
	HpDamage             int64            `protobuf:"varint,14,opt,name=hp_damage,json=hpDamage,proto3" json:"hp_damage,omitempty"`                                       // >= 0
	HealAmount           int64            `protobuf:"varint,15,opt,name=heal_amount,json=healAmount,proto3" json:"heal_amount,omitempty"`                                 // >= 0
	ShieldAmount         int64            `protobuf:"varint,16,opt,name=shield_amount,json=shieldAmount,proto3" json:"shield_amount,omitempty"`                           // >= 0
	TargetHpAfter        int64            `protobuf:"varint,17,opt,name=target_hp_after,json=targetHpAfter,proto3" json:"target_hp_after,omitempty"`
	TargetShieldAfter    int64            `protobuf:"varint,18,opt,name=target_shield_after,json=targetShieldAfter,proto3" json:"target_shield_after,omitempty"`
	Killed               bool             `protobuf:"varint,19,opt,name=killed,proto3" json:"killed,omitempty"`
	JustGuardWindow      bool             `protobuf:"varint,20,opt,name=just_guard_window,json=justGuardWindow,proto3" json:"just_guard_window,omitempty"`          // server-detected only; the client
	JustGuardTriggered   bool             `protobuf:"varint,21,opt,name=just_guard_triggered,json=justGuardTriggered,proto3" json:"just_guard_triggered,omitempty"` // never sends a presentation flag
	JustGuardHint        bool             `protobuf:"varint,22,opt,name=just_guard_hint,json=justGuardHint,proto3" json:"just_guard_hint,omitempty"`
	BeastPassive2Success bool             `protobuf:"varint,23,opt,name=beast_passive2_success,json=beastPassive2Success,proto3" json:"beast_passive2_success,omitempty"`
	// Secondary results (Global Effect Resolution Order stage 7, ADR-0037);
	// absent = the secondary result did not occur.
	ReflectDamageInstance *int64 `protobuf:"varint,24,opt,name=reflect_damage_instance,json=reflectDamageInstance,proto3,oneof" json:"reflect_damage_instance,omitempty"` // post-mitigation HP damage to
	// the attacker; NO_CRIT |
	// NO_REFLECT | NO_LIFESTEAL |
	// NO_PROC
	LifestealHealAmount *int64 `protobuf:"varint,25,opt,name=lifesteal_heal_amount,json=lifestealHealAmount,proto3,oneof" json:"lifesteal_heal_amount,omitempty"` // HP healed on the caster after
	// LIFESTEAL_HPS_CAP
	AbsorbShieldAmount *int64 `protobuf:"varint,26,opt,name=absorb_shield_amount,json=absorbShieldAmount,proto3,oneof" json:"absorb_shield_amount,omitempty"` // shield granted to the caster
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *S2C_COMBAT_EVENT) Reset() {
	*x = S2C_COMBAT_EVENT{}
	mi := &file_thinhthan_v1_combat_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_COMBAT_EVENT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_COMBAT_EVENT) ProtoMessage() {}

func (x *S2C_COMBAT_EVENT) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_combat_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_COMBAT_EVENT.ProtoReflect.Descriptor instead.
func (*S2C_COMBAT_EVENT) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_combat_proto_rawDescGZIP(), []int{18}
}

func (x *S2C_COMBAT_EVENT) GetEventId() uint64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *S2C_COMBAT_EVENT) GetServerTick() uint64 {
	if x != nil {
		return x.ServerTick
	}
	return 0
}

func (x *S2C_COMBAT_EVENT) GetActionInstanceId() uint64 {
	if x != nil {
		return x.ActionInstanceId
	}
	return 0
}

func (x *S2C_COMBAT_EVENT) GetSourceEntityId() uint64 {
	if x != nil {
		return x.SourceEntityId
	}
	return 0
}

func (x *S2C_COMBAT_EVENT) GetTargetEntityId() uint64 {
	if x != nil {
		return x.TargetEntityId
	}
	return 0
}

func (x *S2C_COMBAT_EVENT) GetSkillId() string {
	if x != nil {
		return x.SkillId
	}
	return ""
}

func (x *S2C_COMBAT_EVENT) GetEffectId() string {
	if x != nil {
		return x.EffectId
	}
	return ""
}

func (x *S2C_COMBAT_EVENT) GetResultKind() CombatResultKind {
	if x != nil {
		return x.ResultKind
	}
	return CombatResultKind_COMBAT_RESULT_KIND_UNSPECIFIED
}

func (x *S2C_COMBAT_EVENT) GetOutcome() CombatOutcome {
	if x != nil {
		return x.Outcome
	}
	return CombatOutcome_COMBAT_OUTCOME_UNSPECIFIED
}

func (x *S2C_COMBAT_EVENT) GetIsCrit() bool {
	if x != nil {
		return x.IsCrit
	}
	return false
}

func (x *S2C_COMBAT_EVENT) GetDamageElement() DamageElement {
	if x != nil {
		return x.DamageElement
	}
	return DamageElement_DAMAGE_ELEMENT_UNSPECIFIED
}

func (x *S2C_COMBAT_EVENT) GetPostMitigationDamage() int64 {
	if x != nil {
		return x.PostMitigationDamage
	}
	return 0
}

func (x *S2C_COMBAT_EVENT) GetShieldAbsorbed() int64 {
	if x != nil {
		return x.ShieldAbsorbed
	}
	return 0
}

func (x *S2C_COMBAT_EVENT) GetHpDamage() int64 {
	if x != nil {
		return x.HpDamage
	}
	return 0
}

func (x *S2C_COMBAT_EVENT) GetHealAmount() int64 {
	if x != nil {
		return x.HealAmount
	}
	return 0
}

func (x *S2C_COMBAT_EVENT) GetShieldAmount() int64 {
	if x != nil {
		return x.ShieldAmount
	}
	return 0
}

func (x *S2C_COMBAT_EVENT) GetTargetHpAfter() int64 {
	if x != nil {
		return x.TargetHpAfter
	}
	return 0
}

func (x *S2C_COMBAT_EVENT) GetTargetShieldAfter() int64 {
	if x != nil {
		return x.TargetShieldAfter
	}
	return 0
}

func (x *S2C_COMBAT_EVENT) GetKilled() bool {
	if x != nil {
		return x.Killed
	}
	return false
}

func (x *S2C_COMBAT_EVENT) GetJustGuardWindow() bool {
	if x != nil {
		return x.JustGuardWindow
	}
	return false
}

func (x *S2C_COMBAT_EVENT) GetJustGuardTriggered() bool {
	if x != nil {
		return x.JustGuardTriggered
	}
	return false
}

func (x *S2C_COMBAT_EVENT) GetJustGuardHint() bool {
	if x != nil {
		return x.JustGuardHint
	}
	return false
}

func (x *S2C_COMBAT_EVENT) GetBeastPassive2Success() bool {
	if x != nil {
		return x.BeastPassive2Success
	}
	return false
}

func (x *S2C_COMBAT_EVENT) GetReflectDamageInstance() int64 {
	if x != nil && x.ReflectDamageInstance != nil {
		return *x.ReflectDamageInstance
	}
	return 0
}

func (x *S2C_COMBAT_EVENT) GetLifestealHealAmount() int64 {
	if x != nil && x.LifestealHealAmount != nil {
		return *x.LifestealHealAmount
	}
	return 0
}

func (x *S2C_COMBAT_EVENT) GetAbsorbShieldAmount() int64 {
	if x != nil && x.AbsorbShieldAmount != nil {
		return *x.AbsorbShieldAmount
	}
	return 0
}

// S2C_ENCOUNTER_EVENT (305) — AUTHORITATIVE_EVENT: boss phase transitions,
// telegraphed mechanics, per-mechanic lifecycle.
type S2C_ENCOUNTER_EVENT struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	EncounterId uint64                 `protobuf:"varint,1,opt,name=encounter_id,json=encounterId,proto3" json:"encounter_id,omitempty"` // stable for the encounter lifetime
	ServerTick  uint64                 `protobuf:"varint,2,opt,name=server_tick,json=serverTick,proto3" json:"server_tick,omitempty"`
	EventType   EncounterEventType     `protobuf:"varint,3,opt,name=event_type,json=eventType,proto3,enum=thinhthan.v1.EncounterEventType" json:"event_type,omitempty"`
	MechanicId  uint32                 `protobuf:"varint,4,opt,name=mechanic_id,json=mechanicId,proto3" json:"mechanic_id,omitempty"` // stable content-registered ID; 0 when
	// PHASE_TRANSITION
	SourceEntityId    uint64   `protobuf:"varint,5,opt,name=source_entity_id,json=sourceEntityId,proto3" json:"source_entity_id,omitempty"`                 // the entity generating the event
	AffectedEntityIds []uint64 `protobuf:"varint,6,rep,packed,name=affected_entity_ids,json=affectedEntityIds,proto3" json:"affected_entity_ids,omitempty"` // empty = all in AOI
	PhaseNumber       uint32   `protobuf:"varint,7,opt,name=phase_number,json=phaseNumber,proto3" json:"phase_number,omitempty"`                            // PHASE_TRANSITION only; else 0
	MechanicPayload   []byte   `protobuf:"bytes,8,opt,name=mechanic_payload,json=mechanicPayload,proto3" json:"mechanic_payload,omitempty"`                 // mechanic-specific sub-message;
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *S2C_ENCOUNTER_EVENT) Reset() {
	*x = S2C_ENCOUNTER_EVENT{}
	mi := &file_thinhthan_v1_combat_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_ENCOUNTER_EVENT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_ENCOUNTER_EVENT) ProtoMessage() {}

func (x *S2C_ENCOUNTER_EVENT) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_combat_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_ENCOUNTER_EVENT.ProtoReflect.Descriptor instead.
func (*S2C_ENCOUNTER_EVENT) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_combat_proto_rawDescGZIP(), []int{19}
}

func (x *S2C_ENCOUNTER_EVENT) GetEncounterId() uint64 {
	if x != nil {
		return x.EncounterId
	}
	return 0
}

func (x *S2C_ENCOUNTER_EVENT) GetServerTick() uint64 {
	if x != nil {
		return x.ServerTick
	}
	return 0
}

func (x *S2C_ENCOUNTER_EVENT) GetEventType() EncounterEventType {
	if x != nil {
		return x.EventType
	}
	return EncounterEventType_ENCOUNTER_EVENT_TYPE_UNSPECIFIED
}

func (x *S2C_ENCOUNTER_EVENT) GetMechanicId() uint32 {
	if x != nil {
		return x.MechanicId
	}
	return 0
}

func (x *S2C_ENCOUNTER_EVENT) GetSourceEntityId() uint64 {
	if x != nil {
		return x.SourceEntityId
	}
	return 0
}

func (x *S2C_ENCOUNTER_EVENT) GetAffectedEntityIds() []uint64 {
	if x != nil {
		return x.AffectedEntityIds
	}
	return nil
}

func (x *S2C_ENCOUNTER_EVENT) GetPhaseNumber() uint32 {
	if x != nil {
		return x.PhaseNumber
	}
	return 0
}

func (x *S2C_ENCOUNTER_EVENT) GetMechanicPayload() []byte {
	if x != nil {
		return x.MechanicPayload
	}
	return nil
}

// C2S_BASELINE_ACK (306) — acknowledges a world baseline.
type C2S_BASELINE_ACK struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaselineId    uint64                 `protobuf:"varint,1,opt,name=baseline_id,json=baselineId,proto3" json:"baseline_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S_BASELINE_ACK) Reset() {
	*x = C2S_BASELINE_ACK{}
	mi := &file_thinhthan_v1_combat_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_BASELINE_ACK) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_BASELINE_ACK) ProtoMessage() {}

func (x *C2S_BASELINE_ACK) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_combat_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_BASELINE_ACK.ProtoReflect.Descriptor instead.
func (*C2S_BASELINE_ACK) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_combat_proto_rawDescGZIP(), []int{20}
}

func (x *C2S_BASELINE_ACK) GetBaselineId() uint64 {
	if x != nil {
		return x.BaselineId
	}
	return 0
}

var File_thinhthan_v1_combat_proto protoreflect.FileDescriptor

const file_thinhthan_v1_combat_proto_rawDesc = "" +
	"\n" +
	"\x19thinhthan/v1/combat.proto\x12\fthinhthan.v1\x1a\x19thinhthan/v1/common.proto\"\xfa\x01\n" +
	"\rC2S_SKILL_USE\x12$\n" +
	"\x0eclient_mono_ms\x18\x01 \x01(\x04R\fclientMonoMs\x12\x19\n" +
	"\bskill_id\x18\x02 \x01(\tR\askillId\x12,\n" +
	"\x06facing\x18\x03 \x01(\x0e2\x14.thinhthan.v1.FacingR\x06facing\x12(\n" +
	"\x10target_entity_id\x18\x04 \x01(\x04R\x0etargetEntityId\x12'\n" +
	"\x10area_center_x_mm\x18\x05 \x01(\x11R\rareaCenterXMm\x12'\n" +
	"\x10area_center_y_mm\x18\x06 \x01(\x11R\rareaCenterYMm\"\x90\x01\n" +
	"\x10C2S_BASIC_ATTACK\x12$\n" +
	"\x0eclient_mono_ms\x18\x01 \x01(\x04R\fclientMonoMs\x12,\n" +
	"\x06facing\x18\x02 \x01(\x0e2\x14.thinhthan.v1.FacingR\x06facing\x12(\n" +
	"\x10target_entity_id\x18\x03 \x01(\x04R\x0etargetEntityId\"=\n" +
	"\x11C2S_TARGET_INTENT\x12(\n" +
	"\x10target_entity_id\x18\x01 \x01(\x04R\x0etargetEntityId\"\xd8\x03\n" +
	"\x12S2C_ACTION_STARTED\x12,\n" +
	"\x12action_instance_id\x18\x01 \x01(\x04R\x10actionInstanceId\x12(\n" +
	"\x10source_entity_id\x18\x02 \x01(\x04R\x0esourceEntityId\x12\x19\n" +
	"\bskill_id\x18\x03 \x01(\tR\askillId\x12\x1d\n" +
	"\n" +
	"client_seq\x18\x04 \x01(\x04R\tclientSeq\x12\x1f\n" +
	"\vserver_tick\x18\x05 \x01(\x04R\n" +
	"serverTick\x12,\n" +
	"\x06facing\x18\x06 \x01(\x0e2\x14.thinhthan.v1.FacingR\x06facing\x12(\n" +
	"\x10target_entity_id\x18\a \x01(\x04R\x0etargetEntityId\x12'\n" +
	"\x10area_center_x_mm\x18\b \x01(\x11R\rareaCenterXMm\x12'\n" +
	"\x10area_center_y_mm\x18\t \x01(\x11R\rareaCenterYMm\x12\x17\n" +
	"\acast_ms\x18\n" +
	" \x01(\rR\x06castMs\x121\n" +
	"\x15cooldown_ends_at_tick\x18\v \x01(\x04R\x12cooldownEndsAtTick\x12\x19\n" +
	"\bmp_after\x18\f \x01(\x03R\ampAfter\"\xd8\x01\n" +
	"\x13S2C_ACTION_REJECTED\x12\x1d\n" +
	"\n" +
	"client_seq\x18\x01 \x01(\x04R\tclientSeq\x12,\n" +
	"\x12request_message_id\x18\x02 \x01(\rR\x10requestMessageId\x12!\n" +
	"\foperation_id\x18\x03 \x01(\fR\voperationId\x12\x19\n" +
	"\bskill_id\x18\x04 \x01(\tR\askillId\x126\n" +
	"\n" +
	"error_code\x18\x05 \x01(\x0e2\x17.thinhthan.v1.ErrorCodeR\terrorCode\"\xba\x02\n" +
	"\x10S2C_STATUS_EVENT\x12(\n" +
	"\x10target_entity_id\x18\x01 \x01(\x04R\x0etargetEntityId\x12(\n" +
	"\x10source_entity_id\x18\x02 \x01(\x04R\x0esourceEntityId\x12\x1b\n" +
	"\teffect_id\x18\x03 \x01(\tR\beffectId\x12\x1f\n" +
	"\vstatus_kind\x18\x04 \x01(\tR\n" +
	"statusKind\x123\n" +
	"\x05event\x18\x05 \x01(\x0e2\x1d.thinhthan.v1.StatusEventKindR\x05event\x12\x16\n" +
	"\x06stacks\x18\x06 \x01(\rR\x06stacks\x12&\n" +
	"\x0fexpires_at_tick\x18\a \x01(\x04R\rexpiresAtTick\x12\x1f\n" +
	"\vserver_tick\x18\b \x01(\x04R\n" +
	"serverTick\"\xae\x01\n" +
	"\tS2C_DEATH\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\x04R\bentityId\x12(\n" +
	"\x10killer_entity_id\x18\x02 \x01(\x04R\x0ekillerEntityId\x12\x1f\n" +
	"\vserver_tick\x18\x03 \x01(\x04R\n" +
	"serverTick\x129\n" +
	"\x19respawn_available_at_tick\x18\x04 \x01(\x04R\x16respawnAvailableAtTick\"\x9b\x02\n" +
	"\vS2C_RESPAWN\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\x04R\bentityId\x12\x15\n" +
	"\x06map_id\x18\x02 \x01(\tR\x05mapId\x12#\n" +
	"\rcheckpoint_id\x18\x03 \x01(\tR\fcheckpointId\x12\x11\n" +
	"\x04x_mm\x18\x04 \x01(\x11R\x03xMm\x12\x11\n" +
	"\x04y_mm\x18\x05 \x01(\x11R\x03yMm\x12\x19\n" +
	"\bhp_after\x18\x06 \x01(\x03R\ahpAfter\x12\x19\n" +
	"\bmp_after\x18\a \x01(\x03R\ampAfter\x126\n" +
	"\x17invulnerable_until_tick\x18\b \x01(\x04R\x15invulnerableUntilTick\x12\x1f\n" +
	"\vserver_tick\x18\t \x01(\x04R\n" +
	"serverTick\"8\n" +
	"\x13C2S_RESPAWN_REQUEST\x12!\n" +
	"\foperation_id\x18\x01 \x01(\fR\voperationId\"\xb7\x01\n" +
	"\rEncounterView\x12!\n" +
	"\fencounter_id\x18\x01 \x01(\x04R\vencounterId\x120\n" +
	"\x14encounter_content_id\x18\x02 \x01(\tR\x12encounterContentId\x12!\n" +
	"\fphase_number\x18\x03 \x01(\rR\vphaseNumber\x12.\n" +
	"\x13active_mechanic_ids\x18\x04 \x03(\rR\x11activeMechanicIds\"\x81\x03\n" +
	"\x12S2C_WORLD_BASELINE\x12\x1f\n" +
	"\vbaseline_id\x18\x01 \x01(\x04R\n" +
	"baselineId\x12\x1f\n" +
	"\vserver_tick\x18\x02 \x01(\x04R\n" +
	"serverTick\x12\x15\n" +
	"\x06map_id\x18\x03 \x01(\tR\x05mapId\x12#\n" +
	"\rchannel_index\x18\x04 \x01(\rR\fchannelIndex\x12\x1f\n" +
	"\vinstance_id\x18\x05 \x01(\fR\n" +
	"instanceId\x12)\n" +
	"\x10content_revision\x18\x06 \x01(\tR\x0fcontentRevision\x12-\n" +
	"\x04self\x18\a \x01(\v2\x19.thinhthan.v1.EntityStateR\x04self\x125\n" +
	"\bentities\x18\b \x03(\v2\x19.thinhthan.v1.EntityStateR\bentities\x12;\n" +
	"\n" +
	"encounters\x18\t \x03(\v2\x1b.thinhthan.v1.EncounterViewR\n" +
	"encounters\"\x87\x01\n" +
	"\x10S2C_ENTITY_SPAWN\x12\x1f\n" +
	"\vbaseline_id\x18\x01 \x01(\x04R\n" +
	"baselineId\x12\x1f\n" +
	"\vserver_tick\x18\x02 \x01(\x04R\n" +
	"serverTick\x121\n" +
	"\x06entity\x18\x03 \x01(\v2\x19.thinhthan.v1.EntityStateR\x06entity\"\xa8\x01\n" +
	"\x12S2C_ENTITY_DESPAWN\x12\x1f\n" +
	"\vbaseline_id\x18\x01 \x01(\x04R\n" +
	"baselineId\x12\x1f\n" +
	"\vserver_tick\x18\x02 \x01(\x04R\n" +
	"serverTick\x12\x1b\n" +
	"\tentity_id\x18\x03 \x01(\x04R\bentityId\x123\n" +
	"\x06reason\x18\x04 \x01(\x0e2\x1b.thinhthan.v1.DespawnReasonR\x06reason\"\xff\x01\n" +
	"\aSelfAck\x129\n" +
	"\x19last_processed_client_seq\x18\x01 \x01(\x04R\x16lastProcessedClientSeq\x12\x11\n" +
	"\x04x_mm\x18\x02 \x01(\x11R\x03xMm\x12\x11\n" +
	"\x04y_mm\x18\x03 \x01(\x11R\x03yMm\x12\x16\n" +
	"\avx_mm_s\x18\x04 \x01(\x11R\x05vxMmS\x12\x16\n" +
	"\avy_mm_s\x18\x05 \x01(\x11R\x05vyMmS\x12B\n" +
	"\x0emovement_state\x18\x06 \x01(\x0e2\x1b.thinhthan.v1.MovementStateR\rmovementState\x12\x1f\n" +
	"\vplatform_id\x18\a \x01(\tR\n" +
	"platformId\"F\n" +
	"\n" +
	"StatusList\x128\n" +
	"\aentries\x18\x01 \x03(\v2\x1e.thinhthan.v1.EntityStatusViewR\aentries\"H\n" +
	"\fCosmeticList\x128\n" +
	"\aentries\x18\x01 \x03(\v2\x1e.thinhthan.v1.EquippedCosmeticR\aentries\"\x8f\t\n" +
	"\vEntityDelta\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\x04R\bentityId\x12&\n" +
	"\fdisplay_name\x18\x02 \x01(\tH\x00R\vdisplayName\x88\x01\x01\x12\x19\n" +
	"\x05level\x18\x03 \x01(\rH\x01R\x05level\x88\x01\x01\x12+\n" +
	"\x0fowner_entity_id\x18\x04 \x01(\x04H\x02R\rownerEntityId\x88\x01\x01\x12\x16\n" +
	"\x04x_mm\x18\x05 \x01(\x11H\x03R\x03xMm\x88\x01\x01\x12\x16\n" +
	"\x04y_mm\x18\x06 \x01(\x11H\x04R\x03yMm\x88\x01\x01\x12\x1b\n" +
	"\avx_mm_s\x18\a \x01(\x11H\x05R\x05vxMmS\x88\x01\x01\x12\x1b\n" +
	"\avy_mm_s\x18\b \x01(\x11H\x06R\x05vyMmS\x88\x01\x01\x121\n" +
	"\x06facing\x18\t \x01(\x0e2\x14.thinhthan.v1.FacingH\aR\x06facing\x88\x01\x01\x12G\n" +
	"\x0emovement_state\x18\n" +
	" \x01(\x0e2\x1b.thinhthan.v1.MovementStateH\bR\rmovementState\x88\x01\x01\x12\x13\n" +
	"\x02hp\x18\v \x01(\x03H\tR\x02hp\x88\x01\x01\x12\x1a\n" +
	"\x06max_hp\x18\f \x01(\x03H\n" +
	"R\x05maxHp\x88\x01\x01\x12\x1b\n" +
	"\x06shield\x18\r \x01(\x03H\vR\x06shield\x88\x01\x01\x12\x19\n" +
	"\x05flags\x18\x0e \x01(\rH\fR\x05flags\x88\x01\x01\x124\n" +
	"\bstatuses\x18\x0f \x01(\v2\x18.thinhthan.v1.StatusListR\bstatuses\x12I\n" +
	"\x12equipped_cosmetics\x18\x10 \x01(\v2\x1a.thinhthan.v1.CosmeticListR\x11equippedCosmetics\x12&\n" +
	"\fencounter_id\x18\x11 \x01(\x04H\rR\vencounterId\x88\x01\x01\x12*\n" +
	"\x0estat_lifesteal\x18\x12 \x01(\rH\x0eR\rstatLifesteal\x88\x01\x01\x12&\n" +
	"\fstat_reflect\x18\x13 \x01(\rH\x0fR\vstatReflect\x88\x01\x01\x12$\n" +
	"\vstat_absorb\x18\x14 \x01(\rH\x10R\n" +
	"statAbsorb\x88\x01\x01\x123\n" +
	"\x13stat_heal_reduction\x18\x15 \x01(\rH\x11R\x11statHealReduction\x88\x01\x01\x127\n" +
	"\x15stat_healing_received\x18\x16 \x01(\rH\x12R\x13statHealingReceived\x88\x01\x01B\x0f\n" +
	"\r_display_nameB\b\n" +
	"\x06_levelB\x12\n" +
	"\x10_owner_entity_idB\a\n" +
	"\x05_x_mmB\a\n" +
	"\x05_y_mmB\n" +
	"\n" +
	"\b_vx_mm_sB\n" +
	"\n" +
	"\b_vy_mm_sB\t\n" +
	"\a_facingB\x11\n" +
	"\x0f_movement_stateB\x05\n" +
	"\x03_hpB\t\n" +
	"\a_max_hpB\t\n" +
	"\a_shieldB\b\n" +
	"\x06_flagsB\x0f\n" +
	"\r_encounter_idB\x11\n" +
	"\x0f_stat_lifestealB\x0f\n" +
	"\r_stat_reflectB\x0e\n" +
	"\f_stat_absorbB\x16\n" +
	"\x14_stat_heal_reductionB\x18\n" +
	"\x16_stat_healing_received\"\xbc\x01\n" +
	"\x0fS2C_STATE_DELTA\x12\x1f\n" +
	"\vbaseline_id\x18\x01 \x01(\x04R\n" +
	"baselineId\x12\x1f\n" +
	"\vserver_tick\x18\x02 \x01(\x04R\n" +
	"serverTick\x120\n" +
	"\bself_ack\x18\x03 \x01(\v2\x15.thinhthan.v1.SelfAckR\aselfAck\x125\n" +
	"\bentities\x18\x04 \x03(\v2\x19.thinhthan.v1.EntityDeltaR\bentities\"\xc7\t\n" +
	"\x10S2C_COMBAT_EVENT\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\x04R\aeventId\x12\x1f\n" +
	"\vserver_tick\x18\x02 \x01(\x04R\n" +
	"serverTick\x12,\n" +
	"\x12action_instance_id\x18\x03 \x01(\x04R\x10actionInstanceId\x12(\n" +
	"\x10source_entity_id\x18\x04 \x01(\x04R\x0esourceEntityId\x12(\n" +
	"\x10target_entity_id\x18\x05 \x01(\x04R\x0etargetEntityId\x12\x19\n" +
	"\bskill_id\x18\x06 \x01(\tR\askillId\x12\x1b\n" +
	"\teffect_id\x18\a \x01(\tR\beffectId\x12?\n" +
	"\vresult_kind\x18\b \x01(\x0e2\x1e.thinhthan.v1.CombatResultKindR\n" +
	"resultKind\x125\n" +
	"\aoutcome\x18\t \x01(\x0e2\x1b.thinhthan.v1.CombatOutcomeR\aoutcome\x12\x17\n" +
	"\ais_crit\x18\n" +
	" \x01(\bR\x06isCrit\x12B\n" +
	"\x0edamage_element\x18\v \x01(\x0e2\x1b.thinhthan.v1.DamageElementR\rdamageElement\x124\n" +
	"\x16post_mitigation_damage\x18\f \x01(\x03R\x14postMitigationDamage\x12'\n" +
	"\x0fshield_absorbed\x18\r \x01(\x03R\x0eshieldAbsorbed\x12\x1b\n" +
	"\thp_damage\x18\x0e \x01(\x03R\bhpDamage\x12\x1f\n" +
	"\vheal_amount\x18\x0f \x01(\x03R\n" +
	"healAmount\x12#\n" +
	"\rshield_amount\x18\x10 \x01(\x03R\fshieldAmount\x12&\n" +
	"\x0ftarget_hp_after\x18\x11 \x01(\x03R\rtargetHpAfter\x12.\n" +
	"\x13target_shield_after\x18\x12 \x01(\x03R\x11targetShieldAfter\x12\x16\n" +
	"\x06killed\x18\x13 \x01(\bR\x06killed\x12*\n" +
	"\x11just_guard_window\x18\x14 \x01(\bR\x0fjustGuardWindow\x120\n" +
	"\x14just_guard_triggered\x18\x15 \x01(\bR\x12justGuardTriggered\x12&\n" +
	"\x0fjust_guard_hint\x18\x16 \x01(\bR\rjustGuardHint\x124\n" +
	"\x16beast_passive2_success\x18\x17 \x01(\bR\x14beastPassive2Success\x12;\n" +
	"\x17reflect_damage_instance\x18\x18 \x01(\x03H\x00R\x15reflectDamageInstance\x88\x01\x01\x127\n" +
	"\x15lifesteal_heal_amount\x18\x19 \x01(\x03H\x01R\x13lifestealHealAmount\x88\x01\x01\x125\n" +
	"\x14absorb_shield_amount\x18\x1a \x01(\x03H\x02R\x12absorbShieldAmount\x88\x01\x01B\x1a\n" +
	"\x18_reflect_damage_instanceB\x18\n" +
	"\x16_lifesteal_heal_amountB\x17\n" +
	"\x15_absorb_shield_amount\"\xe3\x02\n" +
	"\x13S2C_ENCOUNTER_EVENT\x12!\n" +
	"\fencounter_id\x18\x01 \x01(\x04R\vencounterId\x12\x1f\n" +
	"\vserver_tick\x18\x02 \x01(\x04R\n" +
	"serverTick\x12?\n" +
	"\n" +
	"event_type\x18\x03 \x01(\x0e2 .thinhthan.v1.EncounterEventTypeR\teventType\x12\x1f\n" +
	"\vmechanic_id\x18\x04 \x01(\rR\n" +
	"mechanicId\x12(\n" +
	"\x10source_entity_id\x18\x05 \x01(\x04R\x0esourceEntityId\x12.\n" +
	"\x13affected_entity_ids\x18\x06 \x03(\x04R\x11affectedEntityIds\x12!\n" +
	"\fphase_number\x18\a \x01(\rR\vphaseNumber\x12)\n" +
	"\x10mechanic_payload\x18\b \x01(\fR\x0fmechanicPayload\"3\n" +
	"\x10C2S_BASELINE_ACK\x12\x1f\n" +
	"\vbaseline_id\x18\x01 \x01(\x04R\n" +
	"baselineId*\xc5\x01\n" +
	"\rDamageElement\x12\x1e\n" +
	"\x1aDAMAGE_ELEMENT_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12DAMAGE_ELEMENT_KIM\x10\x01\x12\x17\n" +
	"\x13DAMAGE_ELEMENT_THUY\x10\x02\x12\x16\n" +
	"\x12DAMAGE_ELEMENT_MOC\x10\x03\x12\x16\n" +
	"\x12DAMAGE_ELEMENT_HOA\x10\x04\x12\x16\n" +
	"\x12DAMAGE_ELEMENT_THO\x10\x05\x12\x1b\n" +
	"\x17DAMAGE_ELEMENT_PHYSICAL\x10\x06*\xf9\x01\n" +
	"\x0fStatusEventKind\x12!\n" +
	"\x1dSTATUS_EVENT_KIND_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19STATUS_EVENT_KIND_APPLIED\x10\x01\x12\x1f\n" +
	"\x1bSTATUS_EVENT_KIND_REFRESHED\x10\x02\x12#\n" +
	"\x1fSTATUS_EVENT_KIND_STACK_CHANGED\x10\x03\x12\x1d\n" +
	"\x19STATUS_EVENT_KIND_EXPIRED\x10\x04\x12\x1f\n" +
	"\x1bSTATUS_EVENT_KIND_DISPELLED\x10\x05\x12\x1e\n" +
	"\x1aSTATUS_EVENT_KIND_CONSUMED\x10\x06*\xba\x01\n" +
	"\rDespawnReason\x12\x1e\n" +
	"\x1aDESPAWN_REASON_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17DESPAWN_REASON_LEFT_AOI\x10\x01\x12\x17\n" +
	"\x13DESPAWN_REASON_DIED\x10\x02\x12\x1a\n" +
	"\x16DESPAWN_REASON_REMOVED\x10\x03\x12\x1e\n" +
	"\x1aDESPAWN_REASON_TRANSFERRED\x10\x04\x12\x17\n" +
	"\x13DESPAWN_REASON_SHED\x10\x05*\xbc\x01\n" +
	"\x10CombatResultKind\x12\"\n" +
	"\x1eCOMBAT_RESULT_KIND_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19COMBAT_RESULT_KIND_DAMAGE\x10\x01\x12\x1b\n" +
	"\x17COMBAT_RESULT_KIND_HEAL\x10\x02\x12#\n" +
	"\x1fCOMBAT_RESULT_KIND_SHIELD_GRANT\x10\x03\x12#\n" +
	"\x1fCOMBAT_RESULT_KIND_SHIELD_BREAK\x10\x04*\x83\x01\n" +
	"\rCombatOutcome\x12\x1e\n" +
	"\x1aCOMBAT_OUTCOME_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12COMBAT_OUTCOME_HIT\x10\x01\x12\x19\n" +
	"\x15COMBAT_OUTCOME_DODGED\x10\x02\x12\x1f\n" +
	"\x1bCOMBAT_OUTCOME_INVULNERABLE\x10\x03*\xea\x02\n" +
	"\x12EncounterEventType\x12$\n" +
	" ENCOUNTER_EVENT_TYPE_UNSPECIFIED\x10\x00\x12)\n" +
	"%ENCOUNTER_EVENT_TYPE_PHASE_TRANSITION\x10\x01\x12(\n" +
	"$ENCOUNTER_EVENT_TYPE_TELEGRAPH_START\x10\x02\x12&\n" +
	"\"ENCOUNTER_EVENT_TYPE_TELEGRAPH_END\x10\x03\x12+\n" +
	"'ENCOUNTER_EVENT_TYPE_MECHANIC_TRIGGERED\x10\x04\x12)\n" +
	"%ENCOUNTER_EVENT_TYPE_MECHANIC_EXPIRED\x10\x05\x12+\n" +
	"'ENCOUNTER_EVENT_TYPE_VULNERABILITY_OPEN\x10\x06\x12,\n" +
	"(ENCOUNTER_EVENT_TYPE_VULNERABILITY_CLOSE\x10\aBCZ)thinhthan/internal/protocol/v1;protocolv1\xaa\x02\x15ThinhThan.Protocol.V1b\x06proto3"

var (
	file_thinhthan_v1_combat_proto_rawDescOnce sync.Once
	file_thinhthan_v1_combat_proto_rawDescData []byte
)

func file_thinhthan_v1_combat_proto_rawDescGZIP() []byte {
	file_thinhthan_v1_combat_proto_rawDescOnce.Do(func() {
		file_thinhthan_v1_combat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_thinhthan_v1_combat_proto_rawDesc), len(file_thinhthan_v1_combat_proto_rawDesc)))
	})
	return file_thinhthan_v1_combat_proto_rawDescData
}

var file_thinhthan_v1_combat_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_thinhthan_v1_combat_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_thinhthan_v1_combat_proto_goTypes = []any{
	(DamageElement)(0),          // 0: thinhthan.v1.DamageElement
	(StatusEventKind)(0),        // 1: thinhthan.v1.StatusEventKind
	(DespawnReason)(0),          // 2: thinhthan.v1.DespawnReason
	(CombatResultKind)(0),       // 3: thinhthan.v1.CombatResultKind
	(CombatOutcome)(0),          // 4: thinhthan.v1.CombatOutcome
	(EncounterEventType)(0),     // 5: thinhthan.v1.EncounterEventType
	(*C2S_SKILL_USE)(nil),       // 6: thinhthan.v1.C2S_SKILL_USE
	(*C2S_BASIC_ATTACK)(nil),    // 7: thinhthan.v1.C2S_BASIC_ATTACK
	(*C2S_TARGET_INTENT)(nil),   // 8: thinhthan.v1.C2S_TARGET_INTENT
	(*S2C_ACTION_STARTED)(nil),  // 9: thinhthan.v1.S2C_ACTION_STARTED
	(*S2C_ACTION_REJECTED)(nil), // 10: thinhthan.v1.S2C_ACTION_REJECTED
	(*S2C_STATUS_EVENT)(nil),    // 11: thinhthan.v1.S2C_STATUS_EVENT
	(*S2C_DEATH)(nil),           // 12: thinhthan.v1.S2C_DEATH
	(*S2C_RESPAWN)(nil),         // 13: thinhthan.v1.S2C_RESPAWN
	(*C2S_RESPAWN_REQUEST)(nil), // 14: thinhthan.v1.C2S_RESPAWN_REQUEST
	(*EncounterView)(nil),       // 15: thinhthan.v1.EncounterView
	(*S2C_WORLD_BASELINE)(nil),  // 16: thinhthan.v1.S2C_WORLD_BASELINE
	(*S2C_ENTITY_SPAWN)(nil),    // 17: thinhthan.v1.S2C_ENTITY_SPAWN
	(*S2C_ENTITY_DESPAWN)(nil),  // 18: thinhthan.v1.S2C_ENTITY_DESPAWN
	(*SelfAck)(nil),             // 19: thinhthan.v1.SelfAck
	(*StatusList)(nil),          // 20: thinhthan.v1.StatusList
	(*CosmeticList)(nil),        // 21: thinhthan.v1.CosmeticList
	(*EntityDelta)(nil),         // 22: thinhthan.v1.EntityDelta
	(*S2C_STATE_DELTA)(nil),     // 23: thinhthan.v1.S2C_STATE_DELTA
	(*S2C_COMBAT_EVENT)(nil),    // 24: thinhthan.v1.S2C_COMBAT_EVENT
	(*S2C_ENCOUNTER_EVENT)(nil), // 25: thinhthan.v1.S2C_ENCOUNTER_EVENT
	(*C2S_BASELINE_ACK)(nil),    // 26: thinhthan.v1.C2S_BASELINE_ACK
	(Facing)(0),                 // 27: thinhthan.v1.Facing
	(ErrorCode)(0),              // 28: thinhthan.v1.ErrorCode
	(*EntityState)(nil),         // 29: thinhthan.v1.EntityState
	(MovementState)(0),          // 30: thinhthan.v1.MovementState
	(*EntityStatusView)(nil),    // 31: thinhthan.v1.EntityStatusView
	(*EquippedCosmetic)(nil),    // 32: thinhthan.v1.EquippedCosmetic
}
var file_thinhthan_v1_combat_proto_depIdxs = []int32{
	27, // 0: thinhthan.v1.C2S_SKILL_USE.facing:type_name -> thinhthan.v1.Facing
	27, // 1: thinhthan.v1.C2S_BASIC_ATTACK.facing:type_name -> thinhthan.v1.Facing
	27, // 2: thinhthan.v1.S2C_ACTION_STARTED.facing:type_name -> thinhthan.v1.Facing
	28, // 3: thinhthan.v1.S2C_ACTION_REJECTED.error_code:type_name -> thinhthan.v1.ErrorCode
	1,  // 4: thinhthan.v1.S2C_STATUS_EVENT.event:type_name -> thinhthan.v1.StatusEventKind
	29, // 5: thinhthan.v1.S2C_WORLD_BASELINE.self:type_name -> thinhthan.v1.EntityState
	29, // 6: thinhthan.v1.S2C_WORLD_BASELINE.entities:type_name -> thinhthan.v1.EntityState
	15, // 7: thinhthan.v1.S2C_WORLD_BASELINE.encounters:type_name -> thinhthan.v1.EncounterView
	29, // 8: thinhthan.v1.S2C_ENTITY_SPAWN.entity:type_name -> thinhthan.v1.EntityState
	2,  // 9: thinhthan.v1.S2C_ENTITY_DESPAWN.reason:type_name -> thinhthan.v1.DespawnReason
	30, // 10: thinhthan.v1.SelfAck.movement_state:type_name -> thinhthan.v1.MovementState
	31, // 11: thinhthan.v1.StatusList.entries:type_name -> thinhthan.v1.EntityStatusView
	32, // 12: thinhthan.v1.CosmeticList.entries:type_name -> thinhthan.v1.EquippedCosmetic
	27, // 13: thinhthan.v1.EntityDelta.facing:type_name -> thinhthan.v1.Facing
	30, // 14: thinhthan.v1.EntityDelta.movement_state:type_name -> thinhthan.v1.MovementState
	20, // 15: thinhthan.v1.EntityDelta.statuses:type_name -> thinhthan.v1.StatusList
	21, // 16: thinhthan.v1.EntityDelta.equipped_cosmetics:type_name -> thinhthan.v1.CosmeticList
	19, // 17: thinhthan.v1.S2C_STATE_DELTA.self_ack:type_name -> thinhthan.v1.SelfAck
	22, // 18: thinhthan.v1.S2C_STATE_DELTA.entities:type_name -> thinhthan.v1.EntityDelta
	3,  // 19: thinhthan.v1.S2C_COMBAT_EVENT.result_kind:type_name -> thinhthan.v1.CombatResultKind
	4,  // 20: thinhthan.v1.S2C_COMBAT_EVENT.outcome:type_name -> thinhthan.v1.CombatOutcome
	0,  // 21: thinhthan.v1.S2C_COMBAT_EVENT.damage_element:type_name -> thinhthan.v1.DamageElement
	5,  // 22: thinhthan.v1.S2C_ENCOUNTER_EVENT.event_type:type_name -> thinhthan.v1.EncounterEventType
	23, // [23:23] is the sub-list for method output_type
	23, // [23:23] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_thinhthan_v1_combat_proto_init() }
func file_thinhthan_v1_combat_proto_init() {
	if File_thinhthan_v1_combat_proto != nil {
		return
	}
	file_thinhthan_v1_common_proto_init()
	file_thinhthan_v1_combat_proto_msgTypes[16].OneofWrappers = []any{}
	file_thinhthan_v1_combat_proto_msgTypes[18].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_thinhthan_v1_combat_proto_rawDesc), len(file_thinhthan_v1_combat_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_thinhthan_v1_combat_proto_goTypes,
		DependencyIndexes: file_thinhthan_v1_combat_proto_depIdxs,
		EnumInfos:         file_thinhthan_v1_combat_proto_enumTypes,
		MessageInfos:      file_thinhthan_v1_combat_proto_msgTypes,
	}.Build()
	File_thinhthan_v1_combat_proto = out.File
	file_thinhthan_v1_combat_proto_goTypes = nil
	file_thinhthan_v1_combat_proto_depIdxs = nil
}
