// Direct trade (700..710) and FIXED_PRICE auction house (730..744) family.
// Field lists: docs/05_network/messages.md § Trade and § Auction
// (ADR-0041, ADR-0049, ADR-0060). Offered trade items stay in the owner's
// CHARACTER_INVENTORY locked by the session until settlement; there is no
// trade escrow row.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: thinhthan/v1/market.proto

package protocolv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TradeCancelReason — why a trade session ended (704).
type TradeCancelReason int32

const (
	TradeCancelReason_TRADE_CANCEL_REASON_UNSPECIFIED          TradeCancelReason = 0
	TradeCancelReason_TRADE_CANCEL_REASON_DECLINED             TradeCancelReason = 1
	TradeCancelReason_TRADE_CANCEL_REASON_CANCELLED            TradeCancelReason = 2
	TradeCancelReason_TRADE_CANCEL_REASON_EXPIRED              TradeCancelReason = 3
	TradeCancelReason_TRADE_CANCEL_REASON_INACTIVE_TIMEOUT     TradeCancelReason = 4
	TradeCancelReason_TRADE_CANCEL_REASON_PARTNER_DISCONNECTED TradeCancelReason = 5
	TradeCancelReason_TRADE_CANCEL_REASON_VALIDATION_FAILED    TradeCancelReason = 6
)

// Enum value maps for TradeCancelReason.
var (
	TradeCancelReason_name = map[int32]string{
		0: "TRADE_CANCEL_REASON_UNSPECIFIED",
		1: "TRADE_CANCEL_REASON_DECLINED",
		2: "TRADE_CANCEL_REASON_CANCELLED",
		3: "TRADE_CANCEL_REASON_EXPIRED",
		4: "TRADE_CANCEL_REASON_INACTIVE_TIMEOUT",
		5: "TRADE_CANCEL_REASON_PARTNER_DISCONNECTED",
		6: "TRADE_CANCEL_REASON_VALIDATION_FAILED",
	}
	TradeCancelReason_value = map[string]int32{
		"TRADE_CANCEL_REASON_UNSPECIFIED":          0,
		"TRADE_CANCEL_REASON_DECLINED":             1,
		"TRADE_CANCEL_REASON_CANCELLED":            2,
		"TRADE_CANCEL_REASON_EXPIRED":              3,
		"TRADE_CANCEL_REASON_INACTIVE_TIMEOUT":     4,
		"TRADE_CANCEL_REASON_PARTNER_DISCONNECTED": 5,
		"TRADE_CANCEL_REASON_VALIDATION_FAILED":    6,
	}
)

func (x TradeCancelReason) Enum() *TradeCancelReason {
	p := new(TradeCancelReason)
	*p = x
	return p
}

func (x TradeCancelReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TradeCancelReason) Descriptor() protoreflect.EnumDescriptor {
	return file_thinhthan_v1_market_proto_enumTypes[0].Descriptor()
}

func (TradeCancelReason) Type() protoreflect.EnumType {
	return &file_thinhthan_v1_market_proto_enumTypes[0]
}

func (x TradeCancelReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TradeCancelReason.Descriptor instead.
func (TradeCancelReason) EnumDescriptor() ([]byte, []int) {
	return file_thinhthan_v1_market_proto_rawDescGZIP(), []int{0}
}

// TradeOfferPhase — trade session offer phase (706).
type TradeOfferPhase int32

const (
	TradeOfferPhase_TRADE_OFFER_PHASE_UNSPECIFIED TradeOfferPhase = 0
	TradeOfferPhase_TRADE_OFFER_PHASE_OPEN        TradeOfferPhase = 1
	TradeOfferPhase_TRADE_OFFER_PHASE_LOCKED      TradeOfferPhase = 2
	TradeOfferPhase_TRADE_OFFER_PHASE_COMMITTING  TradeOfferPhase = 3
)

// Enum value maps for TradeOfferPhase.
var (
	TradeOfferPhase_name = map[int32]string{
		0: "TRADE_OFFER_PHASE_UNSPECIFIED",
		1: "TRADE_OFFER_PHASE_OPEN",
		2: "TRADE_OFFER_PHASE_LOCKED",
		3: "TRADE_OFFER_PHASE_COMMITTING",
	}
	TradeOfferPhase_value = map[string]int32{
		"TRADE_OFFER_PHASE_UNSPECIFIED": 0,
		"TRADE_OFFER_PHASE_OPEN":        1,
		"TRADE_OFFER_PHASE_LOCKED":      2,
		"TRADE_OFFER_PHASE_COMMITTING":  3,
	}
)

func (x TradeOfferPhase) Enum() *TradeOfferPhase {
	p := new(TradeOfferPhase)
	*p = x
	return p
}

func (x TradeOfferPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TradeOfferPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_thinhthan_v1_market_proto_enumTypes[1].Descriptor()
}

func (TradeOfferPhase) Type() protoreflect.EnumType {
	return &file_thinhthan_v1_market_proto_enumTypes[1]
}

func (x TradeOfferPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TradeOfferPhase.Descriptor instead.
func (TradeOfferPhase) EnumDescriptor() ([]byte, []int) {
	return file_thinhthan_v1_market_proto_rawDescGZIP(), []int{1}
}

// AuctionSortOrder — search result ordering (738).
type AuctionSortOrder int32

const (
	AuctionSortOrder_AUCTION_SORT_ORDER_UNSPECIFIED AuctionSortOrder = 0
	AuctionSortOrder_AUCTION_SORT_ORDER_PRICE_ASC   AuctionSortOrder = 1
	AuctionSortOrder_AUCTION_SORT_ORDER_PRICE_DESC  AuctionSortOrder = 2
	AuctionSortOrder_AUCTION_SORT_ORDER_NEWEST      AuctionSortOrder = 3
)

// Enum value maps for AuctionSortOrder.
var (
	AuctionSortOrder_name = map[int32]string{
		0: "AUCTION_SORT_ORDER_UNSPECIFIED",
		1: "AUCTION_SORT_ORDER_PRICE_ASC",
		2: "AUCTION_SORT_ORDER_PRICE_DESC",
		3: "AUCTION_SORT_ORDER_NEWEST",
	}
	AuctionSortOrder_value = map[string]int32{
		"AUCTION_SORT_ORDER_UNSPECIFIED": 0,
		"AUCTION_SORT_ORDER_PRICE_ASC":   1,
		"AUCTION_SORT_ORDER_PRICE_DESC":  2,
		"AUCTION_SORT_ORDER_NEWEST":      3,
	}
)

func (x AuctionSortOrder) Enum() *AuctionSortOrder {
	p := new(AuctionSortOrder)
	*p = x
	return p
}

func (x AuctionSortOrder) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuctionSortOrder) Descriptor() protoreflect.EnumDescriptor {
	return file_thinhthan_v1_market_proto_enumTypes[2].Descriptor()
}

func (AuctionSortOrder) Type() protoreflect.EnumType {
	return &file_thinhthan_v1_market_proto_enumTypes[2]
}

func (x AuctionSortOrder) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuctionSortOrder.Descriptor instead.
func (AuctionSortOrder) EnumDescriptor() ([]byte, []int) {
	return file_thinhthan_v1_market_proto_rawDescGZIP(), []int{2}
}

// AuctionListingState — listing lifecycle inside 744
// (trading_auction.md § Auction House).
type AuctionListingState int32

const (
	AuctionListingState_AUCTION_LISTING_STATE_UNSPECIFIED AuctionListingState = 0
	AuctionListingState_AUCTION_LISTING_STATE_ACTIVE      AuctionListingState = 1
	AuctionListingState_AUCTION_LISTING_STATE_SETTLING    AuctionListingState = 2
	AuctionListingState_AUCTION_LISTING_STATE_SOLD        AuctionListingState = 3
	AuctionListingState_AUCTION_LISTING_STATE_CANCELLED   AuctionListingState = 4 // awaiting escrow reclaim
	AuctionListingState_AUCTION_LISTING_STATE_EXPIRED     AuctionListingState = 5 // awaiting escrow reclaim
)

// Enum value maps for AuctionListingState.
var (
	AuctionListingState_name = map[int32]string{
		0: "AUCTION_LISTING_STATE_UNSPECIFIED",
		1: "AUCTION_LISTING_STATE_ACTIVE",
		2: "AUCTION_LISTING_STATE_SETTLING",
		3: "AUCTION_LISTING_STATE_SOLD",
		4: "AUCTION_LISTING_STATE_CANCELLED",
		5: "AUCTION_LISTING_STATE_EXPIRED",
	}
	AuctionListingState_value = map[string]int32{
		"AUCTION_LISTING_STATE_UNSPECIFIED": 0,
		"AUCTION_LISTING_STATE_ACTIVE":      1,
		"AUCTION_LISTING_STATE_SETTLING":    2,
		"AUCTION_LISTING_STATE_SOLD":        3,
		"AUCTION_LISTING_STATE_CANCELLED":   4,
		"AUCTION_LISTING_STATE_EXPIRED":     5,
	}
)

func (x AuctionListingState) Enum() *AuctionListingState {
	p := new(AuctionListingState)
	*p = x
	return p
}

func (x AuctionListingState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuctionListingState) Descriptor() protoreflect.EnumDescriptor {
	return file_thinhthan_v1_market_proto_enumTypes[3].Descriptor()
}

func (AuctionListingState) Type() protoreflect.EnumType {
	return &file_thinhthan_v1_market_proto_enumTypes[3]
}

func (x AuctionListingState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuctionListingState.Descriptor instead.
func (AuctionListingState) EnumDescriptor() ([]byte, []int) {
	return file_thinhthan_v1_market_proto_rawDescGZIP(), []int{3}
}

// AuctionEscrowReason — why an asset sits in escrow (744).
type AuctionEscrowReason int32

const (
	AuctionEscrowReason_AUCTION_ESCROW_REASON_UNSPECIFIED AuctionEscrowReason = 0
	AuctionEscrowReason_AUCTION_ESCROW_REASON_CANCELLED   AuctionEscrowReason = 1
	AuctionEscrowReason_AUCTION_ESCROW_REASON_EXPIRED     AuctionEscrowReason = 2
)

// Enum value maps for AuctionEscrowReason.
var (
	AuctionEscrowReason_name = map[int32]string{
		0: "AUCTION_ESCROW_REASON_UNSPECIFIED",
		1: "AUCTION_ESCROW_REASON_CANCELLED",
		2: "AUCTION_ESCROW_REASON_EXPIRED",
	}
	AuctionEscrowReason_value = map[string]int32{
		"AUCTION_ESCROW_REASON_UNSPECIFIED": 0,
		"AUCTION_ESCROW_REASON_CANCELLED":   1,
		"AUCTION_ESCROW_REASON_EXPIRED":     2,
	}
)

func (x AuctionEscrowReason) Enum() *AuctionEscrowReason {
	p := new(AuctionEscrowReason)
	*p = x
	return p
}

func (x AuctionEscrowReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuctionEscrowReason) Descriptor() protoreflect.EnumDescriptor {
	return file_thinhthan_v1_market_proto_enumTypes[4].Descriptor()
}

func (AuctionEscrowReason) Type() protoreflect.EnumType {
	return &file_thinhthan_v1_market_proto_enumTypes[4]
}

func (x AuctionEscrowReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuctionEscrowReason.Descriptor instead.
func (AuctionEscrowReason) EnumDescriptor() ([]byte, []int) {
	return file_thinhthan_v1_market_proto_rawDescGZIP(), []int{4}
}

// AuctionProceedsState — proceeds row state (744).
type AuctionProceedsState int32

const (
	AuctionProceedsState_AUCTION_PROCEEDS_STATE_UNSPECIFIED AuctionProceedsState = 0
	AuctionProceedsState_AUCTION_PROCEEDS_STATE_PENDING     AuctionProceedsState = 1
	AuctionProceedsState_AUCTION_PROCEEDS_STATE_CLAIMED     AuctionProceedsState = 2
)

// Enum value maps for AuctionProceedsState.
var (
	AuctionProceedsState_name = map[int32]string{
		0: "AUCTION_PROCEEDS_STATE_UNSPECIFIED",
		1: "AUCTION_PROCEEDS_STATE_PENDING",
		2: "AUCTION_PROCEEDS_STATE_CLAIMED",
	}
	AuctionProceedsState_value = map[string]int32{
		"AUCTION_PROCEEDS_STATE_UNSPECIFIED": 0,
		"AUCTION_PROCEEDS_STATE_PENDING":     1,
		"AUCTION_PROCEEDS_STATE_CLAIMED":     2,
	}
)

func (x AuctionProceedsState) Enum() *AuctionProceedsState {
	p := new(AuctionProceedsState)
	*p = x
	return p
}

func (x AuctionProceedsState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuctionProceedsState) Descriptor() protoreflect.EnumDescriptor {
	return file_thinhthan_v1_market_proto_enumTypes[5].Descriptor()
}

func (AuctionProceedsState) Type() protoreflect.EnumType {
	return &file_thinhthan_v1_market_proto_enumTypes[5]
}

func (x AuctionProceedsState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuctionProceedsState.Descriptor instead.
func (AuctionProceedsState) EnumDescriptor() ([]byte, []int) {
	return file_thinhthan_v1_market_proto_rawDescGZIP(), []int{5}
}

// C2S_TRADE_INVITE (700) — direct trade invitation; social-invite
// eligibility gates apply (trading_auction.md § Direct Trade).
type C2S_TRADE_INVITE struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OperationId       []byte                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`                     // UUID, 16 bytes
	TargetCharacterId []byte                 `protobuf:"bytes,2,opt,name=target_character_id,json=targetCharacterId,proto3" json:"target_character_id,omitempty"` // UUID
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *C2S_TRADE_INVITE) Reset() {
	*x = C2S_TRADE_INVITE{}
	mi := &file_thinhthan_v1_market_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_TRADE_INVITE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_TRADE_INVITE) ProtoMessage() {}

func (x *C2S_TRADE_INVITE) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_market_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_TRADE_INVITE.ProtoReflect.Descriptor instead.
func (*C2S_TRADE_INVITE) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_market_proto_rawDescGZIP(), []int{0}
}

func (x *C2S_TRADE_INVITE) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

func (x *C2S_TRADE_INVITE) GetTargetCharacterId() []byte {
	if x != nil {
		return x.TargetCharacterId
	}
	return nil
}

// S2C_TRADE_INVITE (701) — invitation delivered to the target.
type S2C_TRADE_INVITE struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TradeId            []byte                 `protobuf:"bytes,1,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`                                    // UUID
	InviterCharacterId []byte                 `protobuf:"bytes,2,opt,name=inviter_character_id,json=inviterCharacterId,proto3" json:"inviter_character_id,omitempty"` // UUID
	InviterName        string                 `protobuf:"bytes,3,opt,name=inviter_name,json=inviterName,proto3" json:"inviter_name,omitempty"`
	ExpiresInSeconds   uint32                 `protobuf:"varint,4,opt,name=expires_in_seconds,json=expiresInSeconds,proto3" json:"expires_in_seconds,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *S2C_TRADE_INVITE) Reset() {
	*x = S2C_TRADE_INVITE{}
	mi := &file_thinhthan_v1_market_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_TRADE_INVITE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_TRADE_INVITE) ProtoMessage() {}

func (x *S2C_TRADE_INVITE) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_market_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_TRADE_INVITE.ProtoReflect.Descriptor instead.
func (*S2C_TRADE_INVITE) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_market_proto_rawDescGZIP(), []int{1}
}

func (x *S2C_TRADE_INVITE) GetTradeId() []byte {
	if x != nil {
		return x.TradeId
	}
	return nil
}

func (x *S2C_TRADE_INVITE) GetInviterCharacterId() []byte {
	if x != nil {
		return x.InviterCharacterId
	}
	return nil
}

func (x *S2C_TRADE_INVITE) GetInviterName() string {
	if x != nil {
		return x.InviterName
	}
	return ""
}

func (x *S2C_TRADE_INVITE) GetExpiresInSeconds() uint32 {
	if x != nil {
		return x.ExpiresInSeconds
	}
	return 0
}

// C2S_TRADE_ACCEPT (702).
type C2S_TRADE_ACCEPT struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   []byte                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"` // UUID, 16 bytes
	TradeId       []byte                 `protobuf:"bytes,2,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`             // UUID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S_TRADE_ACCEPT) Reset() {
	*x = C2S_TRADE_ACCEPT{}
	mi := &file_thinhthan_v1_market_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_TRADE_ACCEPT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_TRADE_ACCEPT) ProtoMessage() {}

func (x *C2S_TRADE_ACCEPT) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_market_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_TRADE_ACCEPT.ProtoReflect.Descriptor instead.
func (*C2S_TRADE_ACCEPT) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_market_proto_rawDescGZIP(), []int{2}
}

func (x *C2S_TRADE_ACCEPT) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

func (x *C2S_TRADE_ACCEPT) GetTradeId() []byte {
	if x != nil {
		return x.TradeId
	}
	return nil
}

// C2S_TRADE_CANCEL (703) — decline before accept = cancel; legal at any
// stage.
type C2S_TRADE_CANCEL struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   []byte                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"` // UUID, 16 bytes
	TradeId       []byte                 `protobuf:"bytes,2,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`             // UUID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S_TRADE_CANCEL) Reset() {
	*x = C2S_TRADE_CANCEL{}
	mi := &file_thinhthan_v1_market_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_TRADE_CANCEL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_TRADE_CANCEL) ProtoMessage() {}

func (x *C2S_TRADE_CANCEL) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_market_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_TRADE_CANCEL.ProtoReflect.Descriptor instead.
func (*C2S_TRADE_CANCEL) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_market_proto_rawDescGZIP(), []int{3}
}

func (x *C2S_TRADE_CANCEL) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

func (x *C2S_TRADE_CANCEL) GetTradeId() []byte {
	if x != nil {
		return x.TradeId
	}
	return nil
}

// S2C_TRADE_CANCELLED (704) — AUTHORITATIVE_EVENT.
type S2C_TRADE_CANCELLED struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TradeId       []byte                 `protobuf:"bytes,1,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"` // UUID
	Reason        TradeCancelReason      `protobuf:"varint,2,opt,name=reason,proto3,enum=thinhthan.v1.TradeCancelReason" json:"reason,omitempty"`
	ErrorCode     ErrorCode              `protobuf:"varint,3,opt,name=error_code,json=errorCode,proto3,enum=thinhthan.v1.ErrorCode" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C_TRADE_CANCELLED) Reset() {
	*x = S2C_TRADE_CANCELLED{}
	mi := &file_thinhthan_v1_market_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_TRADE_CANCELLED) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_TRADE_CANCELLED) ProtoMessage() {}

func (x *S2C_TRADE_CANCELLED) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_market_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_TRADE_CANCELLED.ProtoReflect.Descriptor instead.
func (*S2C_TRADE_CANCELLED) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_market_proto_rawDescGZIP(), []int{4}
}

func (x *S2C_TRADE_CANCELLED) GetTradeId() []byte {
	if x != nil {
		return x.TradeId
	}
	return nil
}

func (x *S2C_TRADE_CANCELLED) GetReason() TradeCancelReason {
	if x != nil {
		return x.Reason
	}
	return TradeCancelReason_TRADE_CANCEL_REASON_UNSPECIFIED
}

func (x *S2C_TRADE_CANCELLED) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

// TradeOfferItem — one offered item inside a trade offer.
type TradeOfferItem struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ItemInstanceId []byte                 `protobuf:"bytes,1,opt,name=item_instance_id,json=itemInstanceId,proto3" json:"item_instance_id,omitempty"` // UUID
	Quantity       uint32                 `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TradeOfferItem) Reset() {
	*x = TradeOfferItem{}
	mi := &file_thinhthan_v1_market_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradeOfferItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeOfferItem) ProtoMessage() {}

func (x *TradeOfferItem) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_market_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeOfferItem.ProtoReflect.Descriptor instead.
func (*TradeOfferItem) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_market_proto_rawDescGZIP(), []int{5}
}

func (x *TradeOfferItem) GetItemInstanceId() []byte {
	if x != nil {
		return x.ItemInstanceId
	}
	return nil
}

func (x *TradeOfferItem) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

// C2S_TRADE_OFFER_UPDATE (705) — full replacement of own offer; any change
// clears both sides' confirmation.
type C2S_TRADE_OFFER_UPDATE struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OperationId      []byte                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"` // UUID, 16 bytes
	TradeId          []byte                 `protobuf:"bytes,2,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`             // UUID
	ExpectedRevision uint64                 `protobuf:"varint,3,opt,name=expected_revision,json=expectedRevision,proto3" json:"expected_revision,omitempty"`
	Items            []*TradeOfferItem      `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`                                    // max entries per trading_auction.md
	CommonAmount     int64                  `protobuf:"varint,5,opt,name=common_amount,json=commonAmount,proto3" json:"common_amount,omitempty"` // >= 0
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *C2S_TRADE_OFFER_UPDATE) Reset() {
	*x = C2S_TRADE_OFFER_UPDATE{}
	mi := &file_thinhthan_v1_market_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_TRADE_OFFER_UPDATE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_TRADE_OFFER_UPDATE) ProtoMessage() {}

func (x *C2S_TRADE_OFFER_UPDATE) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_market_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_TRADE_OFFER_UPDATE.ProtoReflect.Descriptor instead.
func (*C2S_TRADE_OFFER_UPDATE) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_market_proto_rawDescGZIP(), []int{6}
}

func (x *C2S_TRADE_OFFER_UPDATE) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

func (x *C2S_TRADE_OFFER_UPDATE) GetTradeId() []byte {
	if x != nil {
		return x.TradeId
	}
	return nil
}

func (x *C2S_TRADE_OFFER_UPDATE) GetExpectedRevision() uint64 {
	if x != nil {
		return x.ExpectedRevision
	}
	return 0
}

func (x *C2S_TRADE_OFFER_UPDATE) GetItems() []*TradeOfferItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *C2S_TRADE_OFFER_UPDATE) GetCommonAmount() int64 {
	if x != nil {
		return x.CommonAmount
	}
	return 0
}

// TradeOfferItemView — one offered item inside 706 (server view adds the
// resolved item_id and enhancement_level).
type TradeOfferItemView struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ItemInstanceId   []byte                 `protobuf:"bytes,1,opt,name=item_instance_id,json=itemInstanceId,proto3" json:"item_instance_id,omitempty"` // UUID
	ItemId           string                 `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`                           // content ID
	Quantity         uint32                 `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	EnhancementLevel uint32                 `protobuf:"varint,4,opt,name=enhancement_level,json=enhancementLevel,proto3" json:"enhancement_level,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TradeOfferItemView) Reset() {
	*x = TradeOfferItemView{}
	mi := &file_thinhthan_v1_market_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradeOfferItemView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeOfferItemView) ProtoMessage() {}

func (x *TradeOfferItemView) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_market_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeOfferItemView.ProtoReflect.Descriptor instead.
func (*TradeOfferItemView) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_market_proto_rawDescGZIP(), []int{7}
}

func (x *TradeOfferItemView) GetItemInstanceId() []byte {
	if x != nil {
		return x.ItemInstanceId
	}
	return nil
}

func (x *TradeOfferItemView) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *TradeOfferItemView) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *TradeOfferItemView) GetEnhancementLevel() uint32 {
	if x != nil {
		return x.EnhancementLevel
	}
	return 0
}

// TradeSide — one side's offer state inside 706.
type TradeSide struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   []byte                 `protobuf:"bytes,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"` // UUID
	Items         []*TradeOfferItemView  `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	CommonAmount  int64                  `protobuf:"varint,3,opt,name=common_amount,json=commonAmount,proto3" json:"common_amount,omitempty"`
	Confirmed     bool                   `protobuf:"varint,4,opt,name=confirmed,proto3" json:"confirmed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TradeSide) Reset() {
	*x = TradeSide{}
	mi := &file_thinhthan_v1_market_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradeSide) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeSide) ProtoMessage() {}

func (x *TradeSide) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_market_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeSide.ProtoReflect.Descriptor instead.
func (*TradeSide) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_market_proto_rawDescGZIP(), []int{8}
}

func (x *TradeSide) GetCharacterId() []byte {
	if x != nil {
		return x.CharacterId
	}
	return nil
}

func (x *TradeSide) GetItems() []*TradeOfferItemView {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *TradeSide) GetCommonAmount() int64 {
	if x != nil {
		return x.CommonAmount
	}
	return 0
}

func (x *TradeSide) GetConfirmed() bool {
	if x != nil {
		return x.Confirmed
	}
	return false
}

// S2C_TRADE_OFFER_STATE (706) — both sides' offer state after any change.
type S2C_TRADE_OFFER_STATE struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TradeId       []byte                 `protobuf:"bytes,1,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"` // UUID
	Revision      uint64                 `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	State         TradeOfferPhase        `protobuf:"varint,3,opt,name=state,proto3,enum=thinhthan.v1.TradeOfferPhase" json:"state,omitempty"`
	Sides         []*TradeSide           `protobuf:"bytes,4,rep,name=sides,proto3" json:"sides,omitempty"` // exactly 2
	FeePreview    int64                  `protobuf:"varint,5,opt,name=fee_preview,json=feePreview,proto3" json:"fee_preview,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C_TRADE_OFFER_STATE) Reset() {
	*x = S2C_TRADE_OFFER_STATE{}
	mi := &file_thinhthan_v1_market_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_TRADE_OFFER_STATE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_TRADE_OFFER_STATE) ProtoMessage() {}

func (x *S2C_TRADE_OFFER_STATE) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_market_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_TRADE_OFFER_STATE.ProtoReflect.Descriptor instead.
func (*S2C_TRADE_OFFER_STATE) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_market_proto_rawDescGZIP(), []int{9}
}

func (x *S2C_TRADE_OFFER_STATE) GetTradeId() []byte {
	if x != nil {
		return x.TradeId
	}
	return nil
}

func (x *S2C_TRADE_OFFER_STATE) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *S2C_TRADE_OFFER_STATE) GetState() TradeOfferPhase {
	if x != nil {
		return x.State
	}
	return TradeOfferPhase_TRADE_OFFER_PHASE_UNSPECIFIED
}

func (x *S2C_TRADE_OFFER_STATE) GetSides() []*TradeSide {
	if x != nil {
		return x.Sides
	}
	return nil
}

func (x *S2C_TRADE_OFFER_STATE) GetFeePreview() int64 {
	if x != nil {
		return x.FeePreview
	}
	return 0
}

// C2S_TRADE_CONFIRM (707) — locks own side; any offer change clears both.
type C2S_TRADE_CONFIRM struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OperationId      []byte                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"` // UUID, 16 bytes
	TradeId          []byte                 `protobuf:"bytes,2,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`             // UUID
	ExpectedRevision uint64                 `protobuf:"varint,3,opt,name=expected_revision,json=expectedRevision,proto3" json:"expected_revision,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *C2S_TRADE_CONFIRM) Reset() {
	*x = C2S_TRADE_CONFIRM{}
	mi := &file_thinhthan_v1_market_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_TRADE_CONFIRM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_TRADE_CONFIRM) ProtoMessage() {}

func (x *C2S_TRADE_CONFIRM) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_market_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_TRADE_CONFIRM.ProtoReflect.Descriptor instead.
func (*C2S_TRADE_CONFIRM) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_market_proto_rawDescGZIP(), []int{10}
}

func (x *C2S_TRADE_CONFIRM) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

func (x *C2S_TRADE_CONFIRM) GetTradeId() []byte {
	if x != nil {
		return x.TradeId
	}
	return nil
}

func (x *C2S_TRADE_CONFIRM) GetExpectedRevision() uint64 {
	if x != nil {
		return x.ExpectedRevision
	}
	return 0
}

// C2S_TRADE_FINALISE (708) — both confirmed; commits the exchange.
type C2S_TRADE_FINALISE struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OperationId      []byte                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"` // UUID, 16 bytes
	TradeId          []byte                 `protobuf:"bytes,2,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`             // UUID
	ExpectedRevision uint64                 `protobuf:"varint,3,opt,name=expected_revision,json=expectedRevision,proto3" json:"expected_revision,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *C2S_TRADE_FINALISE) Reset() {
	*x = C2S_TRADE_FINALISE{}
	mi := &file_thinhthan_v1_market_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_TRADE_FINALISE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_TRADE_FINALISE) ProtoMessage() {}

func (x *C2S_TRADE_FINALISE) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_market_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_TRADE_FINALISE.ProtoReflect.Descriptor instead.
func (*C2S_TRADE_FINALISE) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_market_proto_rawDescGZIP(), []int{11}
}

func (x *C2S_TRADE_FINALISE) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

func (x *C2S_TRADE_FINALISE) GetTradeId() []byte {
	if x != nil {
		return x.TradeId
	}
	return nil
}

func (x *C2S_TRADE_FINALISE) GetExpectedRevision() uint64 {
	if x != nil {
		return x.ExpectedRevision
	}
	return 0
}

// S2C_TRADE_RESULT (709) — authoritative outcome; operation_id echoes the
// 708 that committed or failed (empty when settlement was triggered by the
// partner).
type S2C_TRADE_RESULT struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Result *OperationResult       `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"` // operation_id = the 708 that committed or
	// failed; empty when settlement was triggered
	// by the partner
	TradeId        []byte       `protobuf:"bytes,2,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`                // UUID
	SettlementId   []byte       `protobuf:"bytes,3,opt,name=settlement_id,json=settlementId,proto3" json:"settlement_id,omitempty"` // UUID
	Received       []*ItemGrant `protobuf:"bytes,4,rep,name=received,proto3" json:"received,omitempty"`
	CommonReceived int64        `protobuf:"varint,5,opt,name=common_received,json=commonReceived,proto3" json:"common_received,omitempty"`
	Fee            int64        `protobuf:"varint,6,opt,name=fee,proto3" json:"fee,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *S2C_TRADE_RESULT) Reset() {
	*x = S2C_TRADE_RESULT{}
	mi := &file_thinhthan_v1_market_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_TRADE_RESULT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_TRADE_RESULT) ProtoMessage() {}

func (x *S2C_TRADE_RESULT) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_market_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_TRADE_RESULT.ProtoReflect.Descriptor instead.
func (*S2C_TRADE_RESULT) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_market_proto_rawDescGZIP(), []int{12}
}

func (x *S2C_TRADE_RESULT) GetResult() *OperationResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *S2C_TRADE_RESULT) GetTradeId() []byte {
	if x != nil {
		return x.TradeId
	}
	return nil
}

func (x *S2C_TRADE_RESULT) GetSettlementId() []byte {
	if x != nil {
		return x.SettlementId
	}
	return nil
}

func (x *S2C_TRADE_RESULT) GetReceived() []*ItemGrant {
	if x != nil {
		return x.Received
	}
	return nil
}

func (x *S2C_TRADE_RESULT) GetCommonReceived() int64 {
	if x != nil {
		return x.CommonReceived
	}
	return 0
}

func (x *S2C_TRADE_RESULT) GetFee() int64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

// S2C_TRADE_REQUEST_RESULT (710) — typed result for 700 | 702 | 703 | 705 |
// 707.
type S2C_TRADE_REQUEST_RESULT struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Result *OperationResult       `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"` // TRADE_ELIGIBILITY_LEVEL_REQUIRED |
	// TRADE_ELIGIBILITY_AGE_REQUIRED |
	// SAME_ACCOUNT_FORBIDDEN | TARGET_BLOCKED |
	// OUT_OF_RANGE | IN_COMBAT | ITEM_LOCKED |
	// STATE_CONFLICT | TRADE_COMMON_BOTH_SIDES
	// | TRADE_PRICE_FLOOR_NOT_MET |
	// CURRENCY_CAP_EXCEEDED | INVENTORY_FULL |
	// TRADE_PARTNER_DISCONNECTED
	RequestMessageId uint32 `protobuf:"varint,2,opt,name=request_message_id,json=requestMessageId,proto3" json:"request_message_id,omitempty"` // 700 | 702 | 703 | 705 | 707
	TradeId          []byte `protobuf:"bytes,3,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`                               // UUID; empty when none
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *S2C_TRADE_REQUEST_RESULT) Reset() {
	*x = S2C_TRADE_REQUEST_RESULT{}
	mi := &file_thinhthan_v1_market_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_TRADE_REQUEST_RESULT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_TRADE_REQUEST_RESULT) ProtoMessage() {}

func (x *S2C_TRADE_REQUEST_RESULT) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_market_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_TRADE_REQUEST_RESULT.ProtoReflect.Descriptor instead.
func (*S2C_TRADE_REQUEST_RESULT) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_market_proto_rawDescGZIP(), []int{13}
}

func (x *S2C_TRADE_REQUEST_RESULT) GetResult() *OperationResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *S2C_TRADE_REQUEST_RESULT) GetRequestMessageId() uint32 {
	if x != nil {
		return x.RequestMessageId
	}
	return 0
}

func (x *S2C_TRADE_REQUEST_RESULT) GetTradeId() []byte {
	if x != nil {
		return x.TradeId
	}
	return nil
}

// C2S_AUCTION_LIST (730) — create a FIXED_PRICE listing; price_common is the
// total lot price.
type C2S_AUCTION_LIST struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OperationId    []byte                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`            // UUID, 16 bytes
	ItemInstanceId []byte                 `protobuf:"bytes,2,opt,name=item_instance_id,json=itemInstanceId,proto3" json:"item_instance_id,omitempty"` // UUID
	Quantity       uint32                 `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`                                    // whole lot
	PriceCommon    int64                  `protobuf:"varint,4,opt,name=price_common,json=priceCommon,proto3" json:"price_common,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *C2S_AUCTION_LIST) Reset() {
	*x = C2S_AUCTION_LIST{}
	mi := &file_thinhthan_v1_market_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_AUCTION_LIST) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_AUCTION_LIST) ProtoMessage() {}

func (x *C2S_AUCTION_LIST) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_market_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_AUCTION_LIST.ProtoReflect.Descriptor instead.
func (*C2S_AUCTION_LIST) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_market_proto_rawDescGZIP(), []int{14}
}

func (x *C2S_AUCTION_LIST) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

func (x *C2S_AUCTION_LIST) GetItemInstanceId() []byte {
	if x != nil {
		return x.ItemInstanceId
	}
	return nil
}

func (x *C2S_AUCTION_LIST) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *C2S_AUCTION_LIST) GetPriceCommon() int64 {
	if x != nil {
		return x.PriceCommon
	}
	return 0
}

// S2C_AUCTION_LIST_RESULT (731).
type S2C_AUCTION_LIST_RESULT struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Result *OperationResult       `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"` // AH_ELIGIBILITY_LEVEL_REQUIRED |
	// AH_ELIGIBILITY_AGE_REQUIRED |
	// AH_PRICE_FLOOR_NOT_MET | ITEM_LOCKED |
	// CAPACITY_FULL | ...
	ListingId     []byte `protobuf:"bytes,2,opt,name=listing_id,json=listingId,proto3" json:"listing_id,omitempty"` // UUID
	ListingFee    int64  `protobuf:"varint,3,opt,name=listing_fee,json=listingFee,proto3" json:"listing_fee,omitempty"`
	ExpiresAt     int64  `protobuf:"varint,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // Unix ms
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C_AUCTION_LIST_RESULT) Reset() {
	*x = S2C_AUCTION_LIST_RESULT{}
	mi := &file_thinhthan_v1_market_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_AUCTION_LIST_RESULT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_AUCTION_LIST_RESULT) ProtoMessage() {}

func (x *S2C_AUCTION_LIST_RESULT) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_market_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_AUCTION_LIST_RESULT.ProtoReflect.Descriptor instead.
func (*S2C_AUCTION_LIST_RESULT) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_market_proto_rawDescGZIP(), []int{15}
}

func (x *S2C_AUCTION_LIST_RESULT) GetResult() *OperationResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *S2C_AUCTION_LIST_RESULT) GetListingId() []byte {
	if x != nil {
		return x.ListingId
	}
	return nil
}

func (x *S2C_AUCTION_LIST_RESULT) GetListingFee() int64 {
	if x != nil {
		return x.ListingFee
	}
	return 0
}

func (x *S2C_AUCTION_LIST_RESULT) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

// C2S_AUCTION_BUY (732) — purchase a FIXED_PRICE listing; the expected price
// guards against stale UI (STATE_CONFLICT on mismatch).
type C2S_AUCTION_BUY struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	OperationId         []byte                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"` // UUID, 16 bytes
	ListingId           []byte                 `protobuf:"bytes,2,opt,name=listing_id,json=listingId,proto3" json:"listing_id,omitempty"`       // UUID
	ExpectedPriceCommon int64                  `protobuf:"varint,3,opt,name=expected_price_common,json=expectedPriceCommon,proto3" json:"expected_price_common,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *C2S_AUCTION_BUY) Reset() {
	*x = C2S_AUCTION_BUY{}
	mi := &file_thinhthan_v1_market_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_AUCTION_BUY) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_AUCTION_BUY) ProtoMessage() {}

func (x *C2S_AUCTION_BUY) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_market_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_AUCTION_BUY.ProtoReflect.Descriptor instead.
func (*C2S_AUCTION_BUY) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_market_proto_rawDescGZIP(), []int{16}
}

func (x *C2S_AUCTION_BUY) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

func (x *C2S_AUCTION_BUY) GetListingId() []byte {
	if x != nil {
		return x.ListingId
	}
	return nil
}

func (x *C2S_AUCTION_BUY) GetExpectedPriceCommon() int64 {
	if x != nil {
		return x.ExpectedPriceCommon
	}
	return 0
}

// S2C_AUCTION_BUY_RESULT (733).
type S2C_AUCTION_BUY_RESULT struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Result *OperationResult       `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"` // AUCTION_LISTING_NOT_ACTIVE | STATE_CONFLICT |
	// INSUFFICIENT_CURRENCY | INVENTORY_FULL |
	// SAME_ACCOUNT_FORBIDDEN
	ListingId     []byte     `protobuf:"bytes,2,opt,name=listing_id,json=listingId,proto3" json:"listing_id,omitempty"` // UUID
	PriceCommon   int64      `protobuf:"varint,3,opt,name=price_common,json=priceCommon,proto3" json:"price_common,omitempty"`
	Received      *ItemGrant `protobuf:"bytes,4,opt,name=received,proto3" json:"received,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C_AUCTION_BUY_RESULT) Reset() {
	*x = S2C_AUCTION_BUY_RESULT{}
	mi := &file_thinhthan_v1_market_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_AUCTION_BUY_RESULT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_AUCTION_BUY_RESULT) ProtoMessage() {}

func (x *S2C_AUCTION_BUY_RESULT) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_market_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_AUCTION_BUY_RESULT.ProtoReflect.Descriptor instead.
func (*S2C_AUCTION_BUY_RESULT) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_market_proto_rawDescGZIP(), []int{17}
}

func (x *S2C_AUCTION_BUY_RESULT) GetResult() *OperationResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *S2C_AUCTION_BUY_RESULT) GetListingId() []byte {
	if x != nil {
		return x.ListingId
	}
	return nil
}

func (x *S2C_AUCTION_BUY_RESULT) GetPriceCommon() int64 {
	if x != nil {
		return x.PriceCommon
	}
	return 0
}

func (x *S2C_AUCTION_BUY_RESULT) GetReceived() *ItemGrant {
	if x != nil {
		return x.Received
	}
	return nil
}

// C2S_AUCTION_CANCEL_LISTING (734) — the item stays in escrow pending
// explicit reclaim.
type C2S_AUCTION_CANCEL_LISTING struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   []byte                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"` // UUID, 16 bytes
	ListingId     []byte                 `protobuf:"bytes,2,opt,name=listing_id,json=listingId,proto3" json:"listing_id,omitempty"`       // UUID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S_AUCTION_CANCEL_LISTING) Reset() {
	*x = C2S_AUCTION_CANCEL_LISTING{}
	mi := &file_thinhthan_v1_market_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_AUCTION_CANCEL_LISTING) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_AUCTION_CANCEL_LISTING) ProtoMessage() {}

func (x *C2S_AUCTION_CANCEL_LISTING) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_market_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_AUCTION_CANCEL_LISTING.ProtoReflect.Descriptor instead.
func (*C2S_AUCTION_CANCEL_LISTING) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_market_proto_rawDescGZIP(), []int{18}
}

func (x *C2S_AUCTION_CANCEL_LISTING) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

func (x *C2S_AUCTION_CANCEL_LISTING) GetListingId() []byte {
	if x != nil {
		return x.ListingId
	}
	return nil
}

// S2C_AUCTION_CANCEL_RESULT (735).
type S2C_AUCTION_CANCEL_RESULT struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *OperationResult       `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`                                      // AUCTION_LISTING_NOT_ACTIVE | NOT_OWNER
	ListingId     []byte                 `protobuf:"bytes,2,opt,name=listing_id,json=listingId,proto3" json:"listing_id,omitempty"`               // UUID
	EscrowAssetId []byte                 `protobuf:"bytes,3,opt,name=escrow_asset_id,json=escrowAssetId,proto3" json:"escrow_asset_id,omitempty"` // UUID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C_AUCTION_CANCEL_RESULT) Reset() {
	*x = S2C_AUCTION_CANCEL_RESULT{}
	mi := &file_thinhthan_v1_market_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_AUCTION_CANCEL_RESULT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_AUCTION_CANCEL_RESULT) ProtoMessage() {}

func (x *S2C_AUCTION_CANCEL_RESULT) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_market_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_AUCTION_CANCEL_RESULT.ProtoReflect.Descriptor instead.
func (*S2C_AUCTION_CANCEL_RESULT) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_market_proto_rawDescGZIP(), []int{19}
}

func (x *S2C_AUCTION_CANCEL_RESULT) GetResult() *OperationResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *S2C_AUCTION_CANCEL_RESULT) GetListingId() []byte {
	if x != nil {
		return x.ListingId
	}
	return nil
}

func (x *S2C_AUCTION_CANCEL_RESULT) GetEscrowAssetId() []byte {
	if x != nil {
		return x.EscrowAssetId
	}
	return nil
}

// S2C_AUCTION_SOLD (736) — seller notification.
type S2C_AUCTION_SOLD struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ListingId      []byte                 `protobuf:"bytes,1,opt,name=listing_id,json=listingId,proto3" json:"listing_id,omitempty"` // UUID
	ItemId         string                 `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`          // content ID
	Quantity       uint32                 `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	PriceCommon    int64                  `protobuf:"varint,4,opt,name=price_common,json=priceCommon,proto3" json:"price_common,omitempty"`
	Tax            int64                  `protobuf:"varint,5,opt,name=tax,proto3" json:"tax,omitempty"`
	ProceedsId     []byte                 `protobuf:"bytes,6,opt,name=proceeds_id,json=proceedsId,proto3" json:"proceeds_id,omitempty"` // UUID
	ProceedsAmount int64                  `protobuf:"varint,7,opt,name=proceeds_amount,json=proceedsAmount,proto3" json:"proceeds_amount,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *S2C_AUCTION_SOLD) Reset() {
	*x = S2C_AUCTION_SOLD{}
	mi := &file_thinhthan_v1_market_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_AUCTION_SOLD) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_AUCTION_SOLD) ProtoMessage() {}

func (x *S2C_AUCTION_SOLD) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_market_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_AUCTION_SOLD.ProtoReflect.Descriptor instead.
func (*S2C_AUCTION_SOLD) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_market_proto_rawDescGZIP(), []int{20}
}

func (x *S2C_AUCTION_SOLD) GetListingId() []byte {
	if x != nil {
		return x.ListingId
	}
	return nil
}

func (x *S2C_AUCTION_SOLD) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *S2C_AUCTION_SOLD) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *S2C_AUCTION_SOLD) GetPriceCommon() int64 {
	if x != nil {
		return x.PriceCommon
	}
	return 0
}

func (x *S2C_AUCTION_SOLD) GetTax() int64 {
	if x != nil {
		return x.Tax
	}
	return 0
}

func (x *S2C_AUCTION_SOLD) GetProceedsId() []byte {
	if x != nil {
		return x.ProceedsId
	}
	return nil
}

func (x *S2C_AUCTION_SOLD) GetProceedsAmount() int64 {
	if x != nil {
		return x.ProceedsAmount
	}
	return 0
}

// C2S_AUCTION_SEARCH (738) — read-only; operation_id is echo only and never
// idempotency-stored.
type C2S_AUCTION_SEARCH struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   []byte                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"` // UUID, 16 bytes
	ItemId        string                 `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`                // content ID; empty = any
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`                          // item category content ID; empty = any
	Tier          string                 `protobuf:"bytes,4,opt,name=tier,proto3" json:"tier,omitempty"`                                  // item tier; empty = any
	MinPrice      int64                  `protobuf:"varint,5,opt,name=min_price,json=minPrice,proto3" json:"min_price,omitempty"`
	MaxPrice      int64                  `protobuf:"varint,6,opt,name=max_price,json=maxPrice,proto3" json:"max_price,omitempty"`
	Sort          AuctionSortOrder       `protobuf:"varint,7,opt,name=sort,proto3,enum=thinhthan.v1.AuctionSortOrder" json:"sort,omitempty"`
	PageCursor    string                 `protobuf:"bytes,8,opt,name=page_cursor,json=pageCursor,proto3" json:"page_cursor,omitempty"` // opaque; empty = first page
	PageSize      uint32                 `protobuf:"varint,9,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`      // 1..50
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S_AUCTION_SEARCH) Reset() {
	*x = C2S_AUCTION_SEARCH{}
	mi := &file_thinhthan_v1_market_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_AUCTION_SEARCH) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_AUCTION_SEARCH) ProtoMessage() {}

func (x *C2S_AUCTION_SEARCH) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_market_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_AUCTION_SEARCH.ProtoReflect.Descriptor instead.
func (*C2S_AUCTION_SEARCH) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_market_proto_rawDescGZIP(), []int{21}
}

func (x *C2S_AUCTION_SEARCH) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

func (x *C2S_AUCTION_SEARCH) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *C2S_AUCTION_SEARCH) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *C2S_AUCTION_SEARCH) GetTier() string {
	if x != nil {
		return x.Tier
	}
	return ""
}

func (x *C2S_AUCTION_SEARCH) GetMinPrice() int64 {
	if x != nil {
		return x.MinPrice
	}
	return 0
}

func (x *C2S_AUCTION_SEARCH) GetMaxPrice() int64 {
	if x != nil {
		return x.MaxPrice
	}
	return 0
}

func (x *C2S_AUCTION_SEARCH) GetSort() AuctionSortOrder {
	if x != nil {
		return x.Sort
	}
	return AuctionSortOrder_AUCTION_SORT_ORDER_UNSPECIFIED
}

func (x *C2S_AUCTION_SEARCH) GetPageCursor() string {
	if x != nil {
		return x.PageCursor
	}
	return ""
}

func (x *C2S_AUCTION_SEARCH) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// AuctionListingRow — one search row inside 739.
type AuctionListingRow struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ListingId         []byte                 `protobuf:"bytes,1,opt,name=listing_id,json=listingId,proto3" json:"listing_id,omitempty"` // UUID
	ItemId            string                 `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`          // content ID
	Quantity          uint32                 `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	EnhancementLevel  uint32                 `protobuf:"varint,4,opt,name=enhancement_level,json=enhancementLevel,proto3" json:"enhancement_level,omitempty"`
	PriceCommon       int64                  `protobuf:"varint,5,opt,name=price_common,json=priceCommon,proto3" json:"price_common,omitempty"`
	SellerDisplayName string                 `protobuf:"bytes,6,opt,name=seller_display_name,json=sellerDisplayName,proto3" json:"seller_display_name,omitempty"`
	ExpiresAt         int64                  `protobuf:"varint,7,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // Unix ms
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AuctionListingRow) Reset() {
	*x = AuctionListingRow{}
	mi := &file_thinhthan_v1_market_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuctionListingRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuctionListingRow) ProtoMessage() {}

func (x *AuctionListingRow) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_market_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuctionListingRow.ProtoReflect.Descriptor instead.
func (*AuctionListingRow) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_market_proto_rawDescGZIP(), []int{22}
}

func (x *AuctionListingRow) GetListingId() []byte {
	if x != nil {
		return x.ListingId
	}
	return nil
}

func (x *AuctionListingRow) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *AuctionListingRow) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *AuctionListingRow) GetEnhancementLevel() uint32 {
	if x != nil {
		return x.EnhancementLevel
	}
	return 0
}

func (x *AuctionListingRow) GetPriceCommon() int64 {
	if x != nil {
		return x.PriceCommon
	}
	return 0
}

func (x *AuctionListingRow) GetSellerDisplayName() string {
	if x != nil {
		return x.SellerDisplayName
	}
	return ""
}

func (x *AuctionListingRow) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

// S2C_AUCTION_SEARCH_RESULT (739).
type S2C_AUCTION_SEARCH_RESULT struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Result *OperationResult       `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"` // RATE_LIMITED | AH_ELIGIBILITY_LEVEL_REQUIRED |
	// OUT_OF_RANGE
	Rows           []*AuctionListingRow `protobuf:"bytes,2,rep,name=rows,proto3" json:"rows,omitempty"`
	NextPageCursor string               `protobuf:"bytes,3,opt,name=next_page_cursor,json=nextPageCursor,proto3" json:"next_page_cursor,omitempty"` // opaque; empty = last page
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *S2C_AUCTION_SEARCH_RESULT) Reset() {
	*x = S2C_AUCTION_SEARCH_RESULT{}
	mi := &file_thinhthan_v1_market_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_AUCTION_SEARCH_RESULT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_AUCTION_SEARCH_RESULT) ProtoMessage() {}

func (x *S2C_AUCTION_SEARCH_RESULT) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_market_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_AUCTION_SEARCH_RESULT.ProtoReflect.Descriptor instead.
func (*S2C_AUCTION_SEARCH_RESULT) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_market_proto_rawDescGZIP(), []int{23}
}

func (x *S2C_AUCTION_SEARCH_RESULT) GetResult() *OperationResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *S2C_AUCTION_SEARCH_RESULT) GetRows() []*AuctionListingRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *S2C_AUCTION_SEARCH_RESULT) GetNextPageCursor() string {
	if x != nil {
		return x.NextPageCursor
	}
	return ""
}

// C2S_AUCTION_RECLAIM (740) — reclaim a cancelled/expired escrow asset.
type C2S_AUCTION_RECLAIM struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   []byte                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`         // UUID, 16 bytes
	EscrowAssetId []byte                 `protobuf:"bytes,2,opt,name=escrow_asset_id,json=escrowAssetId,proto3" json:"escrow_asset_id,omitempty"` // UUID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S_AUCTION_RECLAIM) Reset() {
	*x = C2S_AUCTION_RECLAIM{}
	mi := &file_thinhthan_v1_market_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_AUCTION_RECLAIM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_AUCTION_RECLAIM) ProtoMessage() {}

func (x *C2S_AUCTION_RECLAIM) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_market_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_AUCTION_RECLAIM.ProtoReflect.Descriptor instead.
func (*C2S_AUCTION_RECLAIM) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_market_proto_rawDescGZIP(), []int{24}
}

func (x *C2S_AUCTION_RECLAIM) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

func (x *C2S_AUCTION_RECLAIM) GetEscrowAssetId() []byte {
	if x != nil {
		return x.EscrowAssetId
	}
	return nil
}

// S2C_AUCTION_RECLAIM_RESULT (741) — INVENTORY_FULL keeps the asset in
// escrow.
type S2C_AUCTION_RECLAIM_RESULT struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *OperationResult       `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`                                      // INVENTORY_FULL | ITEM_NOT_FOUND
	EscrowAssetId []byte                 `protobuf:"bytes,2,opt,name=escrow_asset_id,json=escrowAssetId,proto3" json:"escrow_asset_id,omitempty"` // UUID
	Received      *ItemGrant             `protobuf:"bytes,3,opt,name=received,proto3" json:"received,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C_AUCTION_RECLAIM_RESULT) Reset() {
	*x = S2C_AUCTION_RECLAIM_RESULT{}
	mi := &file_thinhthan_v1_market_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_AUCTION_RECLAIM_RESULT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_AUCTION_RECLAIM_RESULT) ProtoMessage() {}

func (x *S2C_AUCTION_RECLAIM_RESULT) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_market_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_AUCTION_RECLAIM_RESULT.ProtoReflect.Descriptor instead.
func (*S2C_AUCTION_RECLAIM_RESULT) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_market_proto_rawDescGZIP(), []int{25}
}

func (x *S2C_AUCTION_RECLAIM_RESULT) GetResult() *OperationResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *S2C_AUCTION_RECLAIM_RESULT) GetEscrowAssetId() []byte {
	if x != nil {
		return x.EscrowAssetId
	}
	return nil
}

func (x *S2C_AUCTION_RECLAIM_RESULT) GetReceived() *ItemGrant {
	if x != nil {
		return x.Received
	}
	return nil
}

// C2S_AUCTION_PROCEEDS_CLAIM (742) — claim PENDING proceeds;
// CURRENCY_CAP_EXCEEDED keeps it PENDING.
type C2S_AUCTION_PROCEEDS_CLAIM struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   []byte                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"` // UUID, 16 bytes
	ProceedsId    []byte                 `protobuf:"bytes,2,opt,name=proceeds_id,json=proceedsId,proto3" json:"proceeds_id,omitempty"`    // UUID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S_AUCTION_PROCEEDS_CLAIM) Reset() {
	*x = C2S_AUCTION_PROCEEDS_CLAIM{}
	mi := &file_thinhthan_v1_market_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_AUCTION_PROCEEDS_CLAIM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_AUCTION_PROCEEDS_CLAIM) ProtoMessage() {}

func (x *C2S_AUCTION_PROCEEDS_CLAIM) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_market_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_AUCTION_PROCEEDS_CLAIM.ProtoReflect.Descriptor instead.
func (*C2S_AUCTION_PROCEEDS_CLAIM) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_market_proto_rawDescGZIP(), []int{26}
}

func (x *C2S_AUCTION_PROCEEDS_CLAIM) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

func (x *C2S_AUCTION_PROCEEDS_CLAIM) GetProceedsId() []byte {
	if x != nil {
		return x.ProceedsId
	}
	return nil
}

// S2C_AUCTION_PROCEEDS_RESULT (743).
type S2C_AUCTION_PROCEEDS_RESULT struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *OperationResult       `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`                           // CURRENCY_CAP_EXCEEDED | ITEM_NOT_FOUND
	ProceedsId    []byte                 `protobuf:"bytes,2,opt,name=proceeds_id,json=proceedsId,proto3" json:"proceeds_id,omitempty"` // UUID
	AmountCommon  int64                  `protobuf:"varint,3,opt,name=amount_common,json=amountCommon,proto3" json:"amount_common,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C_AUCTION_PROCEEDS_RESULT) Reset() {
	*x = S2C_AUCTION_PROCEEDS_RESULT{}
	mi := &file_thinhthan_v1_market_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_AUCTION_PROCEEDS_RESULT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_AUCTION_PROCEEDS_RESULT) ProtoMessage() {}

func (x *S2C_AUCTION_PROCEEDS_RESULT) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_market_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_AUCTION_PROCEEDS_RESULT.ProtoReflect.Descriptor instead.
func (*S2C_AUCTION_PROCEEDS_RESULT) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_market_proto_rawDescGZIP(), []int{27}
}

func (x *S2C_AUCTION_PROCEEDS_RESULT) GetResult() *OperationResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *S2C_AUCTION_PROCEEDS_RESULT) GetProceedsId() []byte {
	if x != nil {
		return x.ProceedsId
	}
	return nil
}

func (x *S2C_AUCTION_PROCEEDS_RESULT) GetAmountCommon() int64 {
	if x != nil {
		return x.AmountCommon
	}
	return 0
}

// MyAuctionListing — one own listing inside 744.
type MyAuctionListing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListingId     []byte                 `protobuf:"bytes,1,opt,name=listing_id,json=listingId,proto3" json:"listing_id,omitempty"` // UUID
	ItemId        string                 `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`          // content ID
	Quantity      uint32                 `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	PriceCommon   int64                  `protobuf:"varint,4,opt,name=price_common,json=priceCommon,proto3" json:"price_common,omitempty"`
	State         AuctionListingState    `protobuf:"varint,5,opt,name=state,proto3,enum=thinhthan.v1.AuctionListingState" json:"state,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // Unix ms
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MyAuctionListing) Reset() {
	*x = MyAuctionListing{}
	mi := &file_thinhthan_v1_market_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MyAuctionListing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyAuctionListing) ProtoMessage() {}

func (x *MyAuctionListing) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_market_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyAuctionListing.ProtoReflect.Descriptor instead.
func (*MyAuctionListing) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_market_proto_rawDescGZIP(), []int{28}
}

func (x *MyAuctionListing) GetListingId() []byte {
	if x != nil {
		return x.ListingId
	}
	return nil
}

func (x *MyAuctionListing) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *MyAuctionListing) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *MyAuctionListing) GetPriceCommon() int64 {
	if x != nil {
		return x.PriceCommon
	}
	return 0
}

func (x *MyAuctionListing) GetState() AuctionListingState {
	if x != nil {
		return x.State
	}
	return AuctionListingState_AUCTION_LISTING_STATE_UNSPECIFIED
}

func (x *MyAuctionListing) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

// AuctionEscrowAsset — one escrow row inside 744.
type AuctionEscrowAsset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EscrowAssetId []byte                 `protobuf:"bytes,1,opt,name=escrow_asset_id,json=escrowAssetId,proto3" json:"escrow_asset_id,omitempty"` // UUID
	ItemId        string                 `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`                        // content ID
	Quantity      uint32                 `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Reason        AuctionEscrowReason    `protobuf:"varint,4,opt,name=reason,proto3,enum=thinhthan.v1.AuctionEscrowReason" json:"reason,omitempty"`
	AutoClaimAt   int64                  `protobuf:"varint,5,opt,name=auto_claim_at,json=autoClaimAt,proto3" json:"auto_claim_at,omitempty"` // Unix ms
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuctionEscrowAsset) Reset() {
	*x = AuctionEscrowAsset{}
	mi := &file_thinhthan_v1_market_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuctionEscrowAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuctionEscrowAsset) ProtoMessage() {}

func (x *AuctionEscrowAsset) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_market_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuctionEscrowAsset.ProtoReflect.Descriptor instead.
func (*AuctionEscrowAsset) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_market_proto_rawDescGZIP(), []int{29}
}

func (x *AuctionEscrowAsset) GetEscrowAssetId() []byte {
	if x != nil {
		return x.EscrowAssetId
	}
	return nil
}

func (x *AuctionEscrowAsset) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *AuctionEscrowAsset) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *AuctionEscrowAsset) GetReason() AuctionEscrowReason {
	if x != nil {
		return x.Reason
	}
	return AuctionEscrowReason_AUCTION_ESCROW_REASON_UNSPECIFIED
}

func (x *AuctionEscrowAsset) GetAutoClaimAt() int64 {
	if x != nil {
		return x.AutoClaimAt
	}
	return 0
}

// AuctionProceeds — one proceeds row inside 744.
type AuctionProceeds struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProceedsId    []byte                 `protobuf:"bytes,1,opt,name=proceeds_id,json=proceedsId,proto3" json:"proceeds_id,omitempty"` // UUID
	AmountCommon  int64                  `protobuf:"varint,2,opt,name=amount_common,json=amountCommon,proto3" json:"amount_common,omitempty"`
	State         AuctionProceedsState   `protobuf:"varint,3,opt,name=state,proto3,enum=thinhthan.v1.AuctionProceedsState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuctionProceeds) Reset() {
	*x = AuctionProceeds{}
	mi := &file_thinhthan_v1_market_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuctionProceeds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuctionProceeds) ProtoMessage() {}

func (x *AuctionProceeds) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_market_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuctionProceeds.ProtoReflect.Descriptor instead.
func (*AuctionProceeds) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_market_proto_rawDescGZIP(), []int{30}
}

func (x *AuctionProceeds) GetProceedsId() []byte {
	if x != nil {
		return x.ProceedsId
	}
	return nil
}

func (x *AuctionProceeds) GetAmountCommon() int64 {
	if x != nil {
		return x.AmountCommon
	}
	return 0
}

func (x *AuctionProceeds) GetState() AuctionProceedsState {
	if x != nil {
		return x.State
	}
	return AuctionProceedsState_AUCTION_PROCEEDS_STATE_UNSPECIFIED
}

// S2C_AUCTION_MY_STATE (744) — REPLACEABLE_STATE own-auction snapshot.
type S2C_AUCTION_MY_STATE struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Listings      []*MyAuctionListing    `protobuf:"bytes,1,rep,name=listings,proto3" json:"listings,omitempty"`
	EscrowAssets  []*AuctionEscrowAsset  `protobuf:"bytes,2,rep,name=escrow_assets,json=escrowAssets,proto3" json:"escrow_assets,omitempty"`
	Proceeds      []*AuctionProceeds     `protobuf:"bytes,3,rep,name=proceeds,proto3" json:"proceeds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C_AUCTION_MY_STATE) Reset() {
	*x = S2C_AUCTION_MY_STATE{}
	mi := &file_thinhthan_v1_market_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_AUCTION_MY_STATE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_AUCTION_MY_STATE) ProtoMessage() {}

func (x *S2C_AUCTION_MY_STATE) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_market_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_AUCTION_MY_STATE.ProtoReflect.Descriptor instead.
func (*S2C_AUCTION_MY_STATE) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_market_proto_rawDescGZIP(), []int{31}
}

func (x *S2C_AUCTION_MY_STATE) GetListings() []*MyAuctionListing {
	if x != nil {
		return x.Listings
	}
	return nil
}

func (x *S2C_AUCTION_MY_STATE) GetEscrowAssets() []*AuctionEscrowAsset {
	if x != nil {
		return x.EscrowAssets
	}
	return nil
}

func (x *S2C_AUCTION_MY_STATE) GetProceeds() []*AuctionProceeds {
	if x != nil {
		return x.Proceeds
	}
	return nil
}

var File_thinhthan_v1_market_proto protoreflect.FileDescriptor

const file_thinhthan_v1_market_proto_rawDesc = "" +
	"\n" +
	"\x19thinhthan/v1/market.proto\x12\fthinhthan.v1\x1a\x19thinhthan/v1/common.proto\"e\n" +
	"\x10C2S_TRADE_INVITE\x12!\n" +
	"\foperation_id\x18\x01 \x01(\fR\voperationId\x12.\n" +
	"\x13target_character_id\x18\x02 \x01(\fR\x11targetCharacterId\"\xb0\x01\n" +
	"\x10S2C_TRADE_INVITE\x12\x19\n" +
	"\btrade_id\x18\x01 \x01(\fR\atradeId\x120\n" +
	"\x14inviter_character_id\x18\x02 \x01(\fR\x12inviterCharacterId\x12!\n" +
	"\finviter_name\x18\x03 \x01(\tR\vinviterName\x12,\n" +
	"\x12expires_in_seconds\x18\x04 \x01(\rR\x10expiresInSeconds\"P\n" +
	"\x10C2S_TRADE_ACCEPT\x12!\n" +
	"\foperation_id\x18\x01 \x01(\fR\voperationId\x12\x19\n" +
	"\btrade_id\x18\x02 \x01(\fR\atradeId\"P\n" +
	"\x10C2S_TRADE_CANCEL\x12!\n" +
	"\foperation_id\x18\x01 \x01(\fR\voperationId\x12\x19\n" +
	"\btrade_id\x18\x02 \x01(\fR\atradeId\"\xa1\x01\n" +
	"\x13S2C_TRADE_CANCELLED\x12\x19\n" +
	"\btrade_id\x18\x01 \x01(\fR\atradeId\x127\n" +
	"\x06reason\x18\x02 \x01(\x0e2\x1f.thinhthan.v1.TradeCancelReasonR\x06reason\x126\n" +
	"\n" +
	"error_code\x18\x03 \x01(\x0e2\x17.thinhthan.v1.ErrorCodeR\terrorCode\"V\n" +
	"\x0eTradeOfferItem\x12(\n" +
	"\x10item_instance_id\x18\x01 \x01(\fR\x0eitemInstanceId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\rR\bquantity\"\xdc\x01\n" +
	"\x16C2S_TRADE_OFFER_UPDATE\x12!\n" +
	"\foperation_id\x18\x01 \x01(\fR\voperationId\x12\x19\n" +
	"\btrade_id\x18\x02 \x01(\fR\atradeId\x12+\n" +
	"\x11expected_revision\x18\x03 \x01(\x04R\x10expectedRevision\x122\n" +
	"\x05items\x18\x04 \x03(\v2\x1c.thinhthan.v1.TradeOfferItemR\x05items\x12#\n" +
	"\rcommon_amount\x18\x05 \x01(\x03R\fcommonAmount\"\xa0\x01\n" +
	"\x12TradeOfferItemView\x12(\n" +
	"\x10item_instance_id\x18\x01 \x01(\fR\x0eitemInstanceId\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\tR\x06itemId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\rR\bquantity\x12+\n" +
	"\x11enhancement_level\x18\x04 \x01(\rR\x10enhancementLevel\"\xa9\x01\n" +
	"\tTradeSide\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\fR\vcharacterId\x126\n" +
	"\x05items\x18\x02 \x03(\v2 .thinhthan.v1.TradeOfferItemViewR\x05items\x12#\n" +
	"\rcommon_amount\x18\x03 \x01(\x03R\fcommonAmount\x12\x1c\n" +
	"\tconfirmed\x18\x04 \x01(\bR\tconfirmed\"\xd3\x01\n" +
	"\x15S2C_TRADE_OFFER_STATE\x12\x19\n" +
	"\btrade_id\x18\x01 \x01(\fR\atradeId\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\x04R\brevision\x123\n" +
	"\x05state\x18\x03 \x01(\x0e2\x1d.thinhthan.v1.TradeOfferPhaseR\x05state\x12-\n" +
	"\x05sides\x18\x04 \x03(\v2\x17.thinhthan.v1.TradeSideR\x05sides\x12\x1f\n" +
	"\vfee_preview\x18\x05 \x01(\x03R\n" +
	"feePreview\"~\n" +
	"\x11C2S_TRADE_CONFIRM\x12!\n" +
	"\foperation_id\x18\x01 \x01(\fR\voperationId\x12\x19\n" +
	"\btrade_id\x18\x02 \x01(\fR\atradeId\x12+\n" +
	"\x11expected_revision\x18\x03 \x01(\x04R\x10expectedRevision\"\x7f\n" +
	"\x12C2S_TRADE_FINALISE\x12!\n" +
	"\foperation_id\x18\x01 \x01(\fR\voperationId\x12\x19\n" +
	"\btrade_id\x18\x02 \x01(\fR\atradeId\x12+\n" +
	"\x11expected_revision\x18\x03 \x01(\x04R\x10expectedRevision\"\xf9\x01\n" +
	"\x10S2C_TRADE_RESULT\x125\n" +
	"\x06result\x18\x01 \x01(\v2\x1d.thinhthan.v1.OperationResultR\x06result\x12\x19\n" +
	"\btrade_id\x18\x02 \x01(\fR\atradeId\x12#\n" +
	"\rsettlement_id\x18\x03 \x01(\fR\fsettlementId\x123\n" +
	"\breceived\x18\x04 \x03(\v2\x17.thinhthan.v1.ItemGrantR\breceived\x12'\n" +
	"\x0fcommon_received\x18\x05 \x01(\x03R\x0ecommonReceived\x12\x10\n" +
	"\x03fee\x18\x06 \x01(\x03R\x03fee\"\x9a\x01\n" +
	"\x18S2C_TRADE_REQUEST_RESULT\x125\n" +
	"\x06result\x18\x01 \x01(\v2\x1d.thinhthan.v1.OperationResultR\x06result\x12,\n" +
	"\x12request_message_id\x18\x02 \x01(\rR\x10requestMessageId\x12\x19\n" +
	"\btrade_id\x18\x03 \x01(\fR\atradeId\"\x9e\x01\n" +
	"\x10C2S_AUCTION_LIST\x12!\n" +
	"\foperation_id\x18\x01 \x01(\fR\voperationId\x12(\n" +
	"\x10item_instance_id\x18\x02 \x01(\fR\x0eitemInstanceId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\rR\bquantity\x12!\n" +
	"\fprice_common\x18\x04 \x01(\x03R\vpriceCommon\"\xaf\x01\n" +
	"\x17S2C_AUCTION_LIST_RESULT\x125\n" +
	"\x06result\x18\x01 \x01(\v2\x1d.thinhthan.v1.OperationResultR\x06result\x12\x1d\n" +
	"\n" +
	"listing_id\x18\x02 \x01(\fR\tlistingId\x12\x1f\n" +
	"\vlisting_fee\x18\x03 \x01(\x03R\n" +
	"listingFee\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\x03R\texpiresAt\"\x87\x01\n" +
	"\x0fC2S_AUCTION_BUY\x12!\n" +
	"\foperation_id\x18\x01 \x01(\fR\voperationId\x12\x1d\n" +
	"\n" +
	"listing_id\x18\x02 \x01(\fR\tlistingId\x122\n" +
	"\x15expected_price_common\x18\x03 \x01(\x03R\x13expectedPriceCommon\"\xc6\x01\n" +
	"\x16S2C_AUCTION_BUY_RESULT\x125\n" +
	"\x06result\x18\x01 \x01(\v2\x1d.thinhthan.v1.OperationResultR\x06result\x12\x1d\n" +
	"\n" +
	"listing_id\x18\x02 \x01(\fR\tlistingId\x12!\n" +
	"\fprice_common\x18\x03 \x01(\x03R\vpriceCommon\x123\n" +
	"\breceived\x18\x04 \x01(\v2\x17.thinhthan.v1.ItemGrantR\breceived\"^\n" +
	"\x1aC2S_AUCTION_CANCEL_LISTING\x12!\n" +
	"\foperation_id\x18\x01 \x01(\fR\voperationId\x12\x1d\n" +
	"\n" +
	"listing_id\x18\x02 \x01(\fR\tlistingId\"\x99\x01\n" +
	"\x19S2C_AUCTION_CANCEL_RESULT\x125\n" +
	"\x06result\x18\x01 \x01(\v2\x1d.thinhthan.v1.OperationResultR\x06result\x12\x1d\n" +
	"\n" +
	"listing_id\x18\x02 \x01(\fR\tlistingId\x12&\n" +
	"\x0fescrow_asset_id\x18\x03 \x01(\fR\rescrowAssetId\"\xe5\x01\n" +
	"\x10S2C_AUCTION_SOLD\x12\x1d\n" +
	"\n" +
	"listing_id\x18\x01 \x01(\fR\tlistingId\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\tR\x06itemId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\rR\bquantity\x12!\n" +
	"\fprice_common\x18\x04 \x01(\x03R\vpriceCommon\x12\x10\n" +
	"\x03tax\x18\x05 \x01(\x03R\x03tax\x12\x1f\n" +
	"\vproceeds_id\x18\x06 \x01(\fR\n" +
	"proceedsId\x12'\n" +
	"\x0fproceeds_amount\x18\a \x01(\x03R\x0eproceedsAmount\"\xac\x02\n" +
	"\x12C2S_AUCTION_SEARCH\x12!\n" +
	"\foperation_id\x18\x01 \x01(\fR\voperationId\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\tR\x06itemId\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x12\n" +
	"\x04tier\x18\x04 \x01(\tR\x04tier\x12\x1b\n" +
	"\tmin_price\x18\x05 \x01(\x03R\bminPrice\x12\x1b\n" +
	"\tmax_price\x18\x06 \x01(\x03R\bmaxPrice\x122\n" +
	"\x04sort\x18\a \x01(\x0e2\x1e.thinhthan.v1.AuctionSortOrderR\x04sort\x12\x1f\n" +
	"\vpage_cursor\x18\b \x01(\tR\n" +
	"pageCursor\x12\x1b\n" +
	"\tpage_size\x18\t \x01(\rR\bpageSize\"\x86\x02\n" +
	"\x11AuctionListingRow\x12\x1d\n" +
	"\n" +
	"listing_id\x18\x01 \x01(\fR\tlistingId\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\tR\x06itemId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\rR\bquantity\x12+\n" +
	"\x11enhancement_level\x18\x04 \x01(\rR\x10enhancementLevel\x12!\n" +
	"\fprice_common\x18\x05 \x01(\x03R\vpriceCommon\x12.\n" +
	"\x13seller_display_name\x18\x06 \x01(\tR\x11sellerDisplayName\x12\x1d\n" +
	"\n" +
	"expires_at\x18\a \x01(\x03R\texpiresAt\"\xb1\x01\n" +
	"\x19S2C_AUCTION_SEARCH_RESULT\x125\n" +
	"\x06result\x18\x01 \x01(\v2\x1d.thinhthan.v1.OperationResultR\x06result\x123\n" +
	"\x04rows\x18\x02 \x03(\v2\x1f.thinhthan.v1.AuctionListingRowR\x04rows\x12(\n" +
	"\x10next_page_cursor\x18\x03 \x01(\tR\x0enextPageCursor\"`\n" +
	"\x13C2S_AUCTION_RECLAIM\x12!\n" +
	"\foperation_id\x18\x01 \x01(\fR\voperationId\x12&\n" +
	"\x0fescrow_asset_id\x18\x02 \x01(\fR\rescrowAssetId\"\xb0\x01\n" +
	"\x1aS2C_AUCTION_RECLAIM_RESULT\x125\n" +
	"\x06result\x18\x01 \x01(\v2\x1d.thinhthan.v1.OperationResultR\x06result\x12&\n" +
	"\x0fescrow_asset_id\x18\x02 \x01(\fR\rescrowAssetId\x123\n" +
	"\breceived\x18\x03 \x01(\v2\x17.thinhthan.v1.ItemGrantR\breceived\"`\n" +
	"\x1aC2S_AUCTION_PROCEEDS_CLAIM\x12!\n" +
	"\foperation_id\x18\x01 \x01(\fR\voperationId\x12\x1f\n" +
	"\vproceeds_id\x18\x02 \x01(\fR\n" +
	"proceedsId\"\x9a\x01\n" +
	"\x1bS2C_AUCTION_PROCEEDS_RESULT\x125\n" +
	"\x06result\x18\x01 \x01(\v2\x1d.thinhthan.v1.OperationResultR\x06result\x12\x1f\n" +
	"\vproceeds_id\x18\x02 \x01(\fR\n" +
	"proceedsId\x12#\n" +
	"\ramount_common\x18\x03 \x01(\x03R\famountCommon\"\xe1\x01\n" +
	"\x10MyAuctionListing\x12\x1d\n" +
	"\n" +
	"listing_id\x18\x01 \x01(\fR\tlistingId\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\tR\x06itemId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\rR\bquantity\x12!\n" +
	"\fprice_common\x18\x04 \x01(\x03R\vpriceCommon\x127\n" +
	"\x05state\x18\x05 \x01(\x0e2!.thinhthan.v1.AuctionListingStateR\x05state\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\x03R\texpiresAt\"\xd0\x01\n" +
	"\x12AuctionEscrowAsset\x12&\n" +
	"\x0fescrow_asset_id\x18\x01 \x01(\fR\rescrowAssetId\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\tR\x06itemId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\rR\bquantity\x129\n" +
	"\x06reason\x18\x04 \x01(\x0e2!.thinhthan.v1.AuctionEscrowReasonR\x06reason\x12\"\n" +
	"\rauto_claim_at\x18\x05 \x01(\x03R\vautoClaimAt\"\x91\x01\n" +
	"\x0fAuctionProceeds\x12\x1f\n" +
	"\vproceeds_id\x18\x01 \x01(\fR\n" +
	"proceedsId\x12#\n" +
	"\ramount_common\x18\x02 \x01(\x03R\famountCommon\x128\n" +
	"\x05state\x18\x03 \x01(\x0e2\".thinhthan.v1.AuctionProceedsStateR\x05state\"\xd4\x01\n" +
	"\x14S2C_AUCTION_MY_STATE\x12:\n" +
	"\blistings\x18\x01 \x03(\v2\x1e.thinhthan.v1.MyAuctionListingR\blistings\x12E\n" +
	"\rescrow_assets\x18\x02 \x03(\v2 .thinhthan.v1.AuctionEscrowAssetR\fescrowAssets\x129\n" +
	"\bproceeds\x18\x03 \x03(\v2\x1d.thinhthan.v1.AuctionProceedsR\bproceeds*\xa1\x02\n" +
	"\x11TradeCancelReason\x12#\n" +
	"\x1fTRADE_CANCEL_REASON_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cTRADE_CANCEL_REASON_DECLINED\x10\x01\x12!\n" +
	"\x1dTRADE_CANCEL_REASON_CANCELLED\x10\x02\x12\x1f\n" +
	"\x1bTRADE_CANCEL_REASON_EXPIRED\x10\x03\x12(\n" +
	"$TRADE_CANCEL_REASON_INACTIVE_TIMEOUT\x10\x04\x12,\n" +
	"(TRADE_CANCEL_REASON_PARTNER_DISCONNECTED\x10\x05\x12)\n" +
	"%TRADE_CANCEL_REASON_VALIDATION_FAILED\x10\x06*\x90\x01\n" +
	"\x0fTradeOfferPhase\x12!\n" +
	"\x1dTRADE_OFFER_PHASE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16TRADE_OFFER_PHASE_OPEN\x10\x01\x12\x1c\n" +
	"\x18TRADE_OFFER_PHASE_LOCKED\x10\x02\x12 \n" +
	"\x1cTRADE_OFFER_PHASE_COMMITTING\x10\x03*\x9a\x01\n" +
	"\x10AuctionSortOrder\x12\"\n" +
	"\x1eAUCTION_SORT_ORDER_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cAUCTION_SORT_ORDER_PRICE_ASC\x10\x01\x12!\n" +
	"\x1dAUCTION_SORT_ORDER_PRICE_DESC\x10\x02\x12\x1d\n" +
	"\x19AUCTION_SORT_ORDER_NEWEST\x10\x03*\xea\x01\n" +
	"\x13AuctionListingState\x12%\n" +
	"!AUCTION_LISTING_STATE_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cAUCTION_LISTING_STATE_ACTIVE\x10\x01\x12\"\n" +
	"\x1eAUCTION_LISTING_STATE_SETTLING\x10\x02\x12\x1e\n" +
	"\x1aAUCTION_LISTING_STATE_SOLD\x10\x03\x12#\n" +
	"\x1fAUCTION_LISTING_STATE_CANCELLED\x10\x04\x12!\n" +
	"\x1dAUCTION_LISTING_STATE_EXPIRED\x10\x05*\x84\x01\n" +
	"\x13AuctionEscrowReason\x12%\n" +
	"!AUCTION_ESCROW_REASON_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fAUCTION_ESCROW_REASON_CANCELLED\x10\x01\x12!\n" +
	"\x1dAUCTION_ESCROW_REASON_EXPIRED\x10\x02*\x86\x01\n" +
	"\x14AuctionProceedsState\x12&\n" +
	"\"AUCTION_PROCEEDS_STATE_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eAUCTION_PROCEEDS_STATE_PENDING\x10\x01\x12\"\n" +
	"\x1eAUCTION_PROCEEDS_STATE_CLAIMED\x10\x02BCZ)thinhthan/internal/protocol/v1;protocolv1\xaa\x02\x15ThinhThan.Protocol.V1b\x06proto3"

var (
	file_thinhthan_v1_market_proto_rawDescOnce sync.Once
	file_thinhthan_v1_market_proto_rawDescData []byte
)

func file_thinhthan_v1_market_proto_rawDescGZIP() []byte {
	file_thinhthan_v1_market_proto_rawDescOnce.Do(func() {
		file_thinhthan_v1_market_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_thinhthan_v1_market_proto_rawDesc), len(file_thinhthan_v1_market_proto_rawDesc)))
	})
	return file_thinhthan_v1_market_proto_rawDescData
}

var file_thinhthan_v1_market_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_thinhthan_v1_market_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_thinhthan_v1_market_proto_goTypes = []any{
	(TradeCancelReason)(0),              // 0: thinhthan.v1.TradeCancelReason
	(TradeOfferPhase)(0),                // 1: thinhthan.v1.TradeOfferPhase
	(AuctionSortOrder)(0),               // 2: thinhthan.v1.AuctionSortOrder
	(AuctionListingState)(0),            // 3: thinhthan.v1.AuctionListingState
	(AuctionEscrowReason)(0),            // 4: thinhthan.v1.AuctionEscrowReason
	(AuctionProceedsState)(0),           // 5: thinhthan.v1.AuctionProceedsState
	(*C2S_TRADE_INVITE)(nil),            // 6: thinhthan.v1.C2S_TRADE_INVITE
	(*S2C_TRADE_INVITE)(nil),            // 7: thinhthan.v1.S2C_TRADE_INVITE
	(*C2S_TRADE_ACCEPT)(nil),            // 8: thinhthan.v1.C2S_TRADE_ACCEPT
	(*C2S_TRADE_CANCEL)(nil),            // 9: thinhthan.v1.C2S_TRADE_CANCEL
	(*S2C_TRADE_CANCELLED)(nil),         // 10: thinhthan.v1.S2C_TRADE_CANCELLED
	(*TradeOfferItem)(nil),              // 11: thinhthan.v1.TradeOfferItem
	(*C2S_TRADE_OFFER_UPDATE)(nil),      // 12: thinhthan.v1.C2S_TRADE_OFFER_UPDATE
	(*TradeOfferItemView)(nil),          // 13: thinhthan.v1.TradeOfferItemView
	(*TradeSide)(nil),                   // 14: thinhthan.v1.TradeSide
	(*S2C_TRADE_OFFER_STATE)(nil),       // 15: thinhthan.v1.S2C_TRADE_OFFER_STATE
	(*C2S_TRADE_CONFIRM)(nil),           // 16: thinhthan.v1.C2S_TRADE_CONFIRM
	(*C2S_TRADE_FINALISE)(nil),          // 17: thinhthan.v1.C2S_TRADE_FINALISE
	(*S2C_TRADE_RESULT)(nil),            // 18: thinhthan.v1.S2C_TRADE_RESULT
	(*S2C_TRADE_REQUEST_RESULT)(nil),    // 19: thinhthan.v1.S2C_TRADE_REQUEST_RESULT
	(*C2S_AUCTION_LIST)(nil),            // 20: thinhthan.v1.C2S_AUCTION_LIST
	(*S2C_AUCTION_LIST_RESULT)(nil),     // 21: thinhthan.v1.S2C_AUCTION_LIST_RESULT
	(*C2S_AUCTION_BUY)(nil),             // 22: thinhthan.v1.C2S_AUCTION_BUY
	(*S2C_AUCTION_BUY_RESULT)(nil),      // 23: thinhthan.v1.S2C_AUCTION_BUY_RESULT
	(*C2S_AUCTION_CANCEL_LISTING)(nil),  // 24: thinhthan.v1.C2S_AUCTION_CANCEL_LISTING
	(*S2C_AUCTION_CANCEL_RESULT)(nil),   // 25: thinhthan.v1.S2C_AUCTION_CANCEL_RESULT
	(*S2C_AUCTION_SOLD)(nil),            // 26: thinhthan.v1.S2C_AUCTION_SOLD
	(*C2S_AUCTION_SEARCH)(nil),          // 27: thinhthan.v1.C2S_AUCTION_SEARCH
	(*AuctionListingRow)(nil),           // 28: thinhthan.v1.AuctionListingRow
	(*S2C_AUCTION_SEARCH_RESULT)(nil),   // 29: thinhthan.v1.S2C_AUCTION_SEARCH_RESULT
	(*C2S_AUCTION_RECLAIM)(nil),         // 30: thinhthan.v1.C2S_AUCTION_RECLAIM
	(*S2C_AUCTION_RECLAIM_RESULT)(nil),  // 31: thinhthan.v1.S2C_AUCTION_RECLAIM_RESULT
	(*C2S_AUCTION_PROCEEDS_CLAIM)(nil),  // 32: thinhthan.v1.C2S_AUCTION_PROCEEDS_CLAIM
	(*S2C_AUCTION_PROCEEDS_RESULT)(nil), // 33: thinhthan.v1.S2C_AUCTION_PROCEEDS_RESULT
	(*MyAuctionListing)(nil),            // 34: thinhthan.v1.MyAuctionListing
	(*AuctionEscrowAsset)(nil),          // 35: thinhthan.v1.AuctionEscrowAsset
	(*AuctionProceeds)(nil),             // 36: thinhthan.v1.AuctionProceeds
	(*S2C_AUCTION_MY_STATE)(nil),        // 37: thinhthan.v1.S2C_AUCTION_MY_STATE
	(ErrorCode)(0),                      // 38: thinhthan.v1.ErrorCode
	(*OperationResult)(nil),             // 39: thinhthan.v1.OperationResult
	(*ItemGrant)(nil),                   // 40: thinhthan.v1.ItemGrant
}
var file_thinhthan_v1_market_proto_depIdxs = []int32{
	0,  // 0: thinhthan.v1.S2C_TRADE_CANCELLED.reason:type_name -> thinhthan.v1.TradeCancelReason
	38, // 1: thinhthan.v1.S2C_TRADE_CANCELLED.error_code:type_name -> thinhthan.v1.ErrorCode
	11, // 2: thinhthan.v1.C2S_TRADE_OFFER_UPDATE.items:type_name -> thinhthan.v1.TradeOfferItem
	13, // 3: thinhthan.v1.TradeSide.items:type_name -> thinhthan.v1.TradeOfferItemView
	1,  // 4: thinhthan.v1.S2C_TRADE_OFFER_STATE.state:type_name -> thinhthan.v1.TradeOfferPhase
	14, // 5: thinhthan.v1.S2C_TRADE_OFFER_STATE.sides:type_name -> thinhthan.v1.TradeSide
	39, // 6: thinhthan.v1.S2C_TRADE_RESULT.result:type_name -> thinhthan.v1.OperationResult
	40, // 7: thinhthan.v1.S2C_TRADE_RESULT.received:type_name -> thinhthan.v1.ItemGrant
	39, // 8: thinhthan.v1.S2C_TRADE_REQUEST_RESULT.result:type_name -> thinhthan.v1.OperationResult
	39, // 9: thinhthan.v1.S2C_AUCTION_LIST_RESULT.result:type_name -> thinhthan.v1.OperationResult
	39, // 10: thinhthan.v1.S2C_AUCTION_BUY_RESULT.result:type_name -> thinhthan.v1.OperationResult
	40, // 11: thinhthan.v1.S2C_AUCTION_BUY_RESULT.received:type_name -> thinhthan.v1.ItemGrant
	39, // 12: thinhthan.v1.S2C_AUCTION_CANCEL_RESULT.result:type_name -> thinhthan.v1.OperationResult
	2,  // 13: thinhthan.v1.C2S_AUCTION_SEARCH.sort:type_name -> thinhthan.v1.AuctionSortOrder
	39, // 14: thinhthan.v1.S2C_AUCTION_SEARCH_RESULT.result:type_name -> thinhthan.v1.OperationResult
	28, // 15: thinhthan.v1.S2C_AUCTION_SEARCH_RESULT.rows:type_name -> thinhthan.v1.AuctionListingRow
	39, // 16: thinhthan.v1.S2C_AUCTION_RECLAIM_RESULT.result:type_name -> thinhthan.v1.OperationResult
	40, // 17: thinhthan.v1.S2C_AUCTION_RECLAIM_RESULT.received:type_name -> thinhthan.v1.ItemGrant
	39, // 18: thinhthan.v1.S2C_AUCTION_PROCEEDS_RESULT.result:type_name -> thinhthan.v1.OperationResult
	3,  // 19: thinhthan.v1.MyAuctionListing.state:type_name -> thinhthan.v1.AuctionListingState
	4,  // 20: thinhthan.v1.AuctionEscrowAsset.reason:type_name -> thinhthan.v1.AuctionEscrowReason
	5,  // 21: thinhthan.v1.AuctionProceeds.state:type_name -> thinhthan.v1.AuctionProceedsState
	34, // 22: thinhthan.v1.S2C_AUCTION_MY_STATE.listings:type_name -> thinhthan.v1.MyAuctionListing
	35, // 23: thinhthan.v1.S2C_AUCTION_MY_STATE.escrow_assets:type_name -> thinhthan.v1.AuctionEscrowAsset
	36, // 24: thinhthan.v1.S2C_AUCTION_MY_STATE.proceeds:type_name -> thinhthan.v1.AuctionProceeds
	25, // [25:25] is the sub-list for method output_type
	25, // [25:25] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_thinhthan_v1_market_proto_init() }
func file_thinhthan_v1_market_proto_init() {
	if File_thinhthan_v1_market_proto != nil {
		return
	}
	file_thinhthan_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_thinhthan_v1_market_proto_rawDesc), len(file_thinhthan_v1_market_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_thinhthan_v1_market_proto_goTypes,
		DependencyIndexes: file_thinhthan_v1_market_proto_depIdxs,
		EnumInfos:         file_thinhthan_v1_market_proto_enumTypes,
		MessageInfos:      file_thinhthan_v1_market_proto_msgTypes,
	}.Build()
	File_thinhthan_v1_market_proto = out.File
	file_thinhthan_v1_market_proto_goTypes = nil
	file_thinhthan_v1_market_proto_depIdxs = nil
}
