// Input / movement / channel / dungeon-entry family (message IDs 100..117).
// Field lists: docs/05_network/messages.md § Input / Movement and
// § Dungeon Entry and Exit (ADR-0038, ADR-0060, ADR-0069).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: thinhthan/v1/movement.proto

package protocolv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// InteractKind — discrete interact intent kind. PORTAL never appears in a
// C2S_INTERACT request; it appears only in S2C_INTERACT_RESULT answering
// C2S_PORTAL_USE (104).
type InteractKind int32

const (
	InteractKind_INTERACT_KIND_UNSPECIFIED  InteractKind = 0
	InteractKind_INTERACT_KIND_TALK         InteractKind = 1
	InteractKind_INTERACT_KIND_PICKUP       InteractKind = 2
	InteractKind_INTERACT_KIND_CHEST        InteractKind = 3
	InteractKind_INTERACT_KIND_CAST         InteractKind = 4
	InteractKind_INTERACT_KIND_HOOK         InteractKind = 5
	InteractKind_INTERACT_KIND_KINDLE       InteractKind = 6
	InteractKind_INTERACT_KIND_COOK         InteractKind = 7
	InteractKind_INTERACT_KIND_BONFIRE_REST InteractKind = 8
	InteractKind_INTERACT_KIND_QUEST_OBJECT InteractKind = 9
	InteractKind_INTERACT_KIND_NPC_SERVICE  InteractKind = 10
	InteractKind_INTERACT_KIND_PORTAL       InteractKind = 11
)

// Enum value maps for InteractKind.
var (
	InteractKind_name = map[int32]string{
		0:  "INTERACT_KIND_UNSPECIFIED",
		1:  "INTERACT_KIND_TALK",
		2:  "INTERACT_KIND_PICKUP",
		3:  "INTERACT_KIND_CHEST",
		4:  "INTERACT_KIND_CAST",
		5:  "INTERACT_KIND_HOOK",
		6:  "INTERACT_KIND_KINDLE",
		7:  "INTERACT_KIND_COOK",
		8:  "INTERACT_KIND_BONFIRE_REST",
		9:  "INTERACT_KIND_QUEST_OBJECT",
		10: "INTERACT_KIND_NPC_SERVICE",
		11: "INTERACT_KIND_PORTAL",
	}
	InteractKind_value = map[string]int32{
		"INTERACT_KIND_UNSPECIFIED":  0,
		"INTERACT_KIND_TALK":         1,
		"INTERACT_KIND_PICKUP":       2,
		"INTERACT_KIND_CHEST":        3,
		"INTERACT_KIND_CAST":         4,
		"INTERACT_KIND_HOOK":         5,
		"INTERACT_KIND_KINDLE":       6,
		"INTERACT_KIND_COOK":         7,
		"INTERACT_KIND_BONFIRE_REST": 8,
		"INTERACT_KIND_QUEST_OBJECT": 9,
		"INTERACT_KIND_NPC_SERVICE":  10,
		"INTERACT_KIND_PORTAL":       11,
	}
)

func (x InteractKind) Enum() *InteractKind {
	p := new(InteractKind)
	*p = x
	return p
}

func (x InteractKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InteractKind) Descriptor() protoreflect.EnumDescriptor {
	return file_thinhthan_v1_movement_proto_enumTypes[0].Descriptor()
}

func (InteractKind) Type() protoreflect.EnumType {
	return &file_thinhthan_v1_movement_proto_enumTypes[0]
}

func (x InteractKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InteractKind.Descriptor instead.
func (InteractKind) EnumDescriptor() ([]byte, []int) {
	return file_thinhthan_v1_movement_proto_rawDescGZIP(), []int{0}
}

// TransferReason — why S2C_TRANSFER_PREPARE was issued.
type TransferReason int32

const (
	TransferReason_TRANSFER_REASON_UNSPECIFIED    TransferReason = 0
	TransferReason_TRANSFER_REASON_PORTAL         TransferReason = 1
	TransferReason_TRANSFER_REASON_TRAVEL         TransferReason = 2
	TransferReason_TRANSFER_REASON_CHANNEL_SWITCH TransferReason = 3
	TransferReason_TRANSFER_REASON_DUNGEON_ENTER  TransferReason = 4
	TransferReason_TRANSFER_REASON_DUNGEON_LEAVE  TransferReason = 5
	TransferReason_TRANSFER_REASON_RESPAWN        TransferReason = 6
	TransferReason_TRANSFER_REASON_PVP            TransferReason = 7
	TransferReason_TRANSFER_REASON_RECONNECT      TransferReason = 8
	TransferReason_TRANSFER_REASON_FORCED         TransferReason = 9
)

// Enum value maps for TransferReason.
var (
	TransferReason_name = map[int32]string{
		0: "TRANSFER_REASON_UNSPECIFIED",
		1: "TRANSFER_REASON_PORTAL",
		2: "TRANSFER_REASON_TRAVEL",
		3: "TRANSFER_REASON_CHANNEL_SWITCH",
		4: "TRANSFER_REASON_DUNGEON_ENTER",
		5: "TRANSFER_REASON_DUNGEON_LEAVE",
		6: "TRANSFER_REASON_RESPAWN",
		7: "TRANSFER_REASON_PVP",
		8: "TRANSFER_REASON_RECONNECT",
		9: "TRANSFER_REASON_FORCED",
	}
	TransferReason_value = map[string]int32{
		"TRANSFER_REASON_UNSPECIFIED":    0,
		"TRANSFER_REASON_PORTAL":         1,
		"TRANSFER_REASON_TRAVEL":         2,
		"TRANSFER_REASON_CHANNEL_SWITCH": 3,
		"TRANSFER_REASON_DUNGEON_ENTER":  4,
		"TRANSFER_REASON_DUNGEON_LEAVE":  5,
		"TRANSFER_REASON_RESPAWN":        6,
		"TRANSFER_REASON_PVP":            7,
		"TRANSFER_REASON_RECONNECT":      8,
		"TRANSFER_REASON_FORCED":         9,
	}
)

func (x TransferReason) Enum() *TransferReason {
	p := new(TransferReason)
	*p = x
	return p
}

func (x TransferReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransferReason) Descriptor() protoreflect.EnumDescriptor {
	return file_thinhthan_v1_movement_proto_enumTypes[1].Descriptor()
}

func (TransferReason) Type() protoreflect.EnumType {
	return &file_thinhthan_v1_movement_proto_enumTypes[1]
}

func (x TransferReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransferReason.Descriptor instead.
func (TransferReason) EnumDescriptor() ([]byte, []int) {
	return file_thinhthan_v1_movement_proto_rawDescGZIP(), []int{1}
}

// MovementCorrectionReason — why the server overrides the predicted path
// (ADR-0069); ordinary prediction error never sends 107.
type MovementCorrectionReason int32

const (
	MovementCorrectionReason_MOVEMENT_CORRECTION_REASON_UNSPECIFIED  MovementCorrectionReason = 0
	MovementCorrectionReason_MOVEMENT_CORRECTION_REASON_ILLEGAL_MOVE MovementCorrectionReason = 1
	MovementCorrectionReason_MOVEMENT_CORRECTION_REASON_KNOCKBACK    MovementCorrectionReason = 2
	MovementCorrectionReason_MOVEMENT_CORRECTION_REASON_PORTAL       MovementCorrectionReason = 3
	MovementCorrectionReason_MOVEMENT_CORRECTION_REASON_RESPAWN      MovementCorrectionReason = 4
	MovementCorrectionReason_MOVEMENT_CORRECTION_REASON_FORCED       MovementCorrectionReason = 5
)

// Enum value maps for MovementCorrectionReason.
var (
	MovementCorrectionReason_name = map[int32]string{
		0: "MOVEMENT_CORRECTION_REASON_UNSPECIFIED",
		1: "MOVEMENT_CORRECTION_REASON_ILLEGAL_MOVE",
		2: "MOVEMENT_CORRECTION_REASON_KNOCKBACK",
		3: "MOVEMENT_CORRECTION_REASON_PORTAL",
		4: "MOVEMENT_CORRECTION_REASON_RESPAWN",
		5: "MOVEMENT_CORRECTION_REASON_FORCED",
	}
	MovementCorrectionReason_value = map[string]int32{
		"MOVEMENT_CORRECTION_REASON_UNSPECIFIED":  0,
		"MOVEMENT_CORRECTION_REASON_ILLEGAL_MOVE": 1,
		"MOVEMENT_CORRECTION_REASON_KNOCKBACK":    2,
		"MOVEMENT_CORRECTION_REASON_PORTAL":       3,
		"MOVEMENT_CORRECTION_REASON_RESPAWN":      4,
		"MOVEMENT_CORRECTION_REASON_FORCED":       5,
	}
)

func (x MovementCorrectionReason) Enum() *MovementCorrectionReason {
	p := new(MovementCorrectionReason)
	*p = x
	return p
}

func (x MovementCorrectionReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MovementCorrectionReason) Descriptor() protoreflect.EnumDescriptor {
	return file_thinhthan_v1_movement_proto_enumTypes[2].Descriptor()
}

func (MovementCorrectionReason) Type() protoreflect.EnumType {
	return &file_thinhthan_v1_movement_proto_enumTypes[2]
}

func (x MovementCorrectionReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MovementCorrectionReason.Descriptor instead.
func (MovementCorrectionReason) EnumDescriptor() ([]byte, []int) {
	return file_thinhthan_v1_movement_proto_rawDescGZIP(), []int{2}
}

// EdgeType — movement-onset edge (ADR-0038); the sole wire signal for
// direction press/release timing.
type EdgeType int32

const (
	EdgeType_EDGE_TYPE_UNSPECIFIED EdgeType = 0
	EdgeType_EDGE_TYPE_PRESS       EdgeType = 1
	EdgeType_EDGE_TYPE_RELEASE     EdgeType = 2
	EdgeType_EDGE_TYPE_FLIP        EdgeType = 3
)

// Enum value maps for EdgeType.
var (
	EdgeType_name = map[int32]string{
		0: "EDGE_TYPE_UNSPECIFIED",
		1: "EDGE_TYPE_PRESS",
		2: "EDGE_TYPE_RELEASE",
		3: "EDGE_TYPE_FLIP",
	}
	EdgeType_value = map[string]int32{
		"EDGE_TYPE_UNSPECIFIED": 0,
		"EDGE_TYPE_PRESS":       1,
		"EDGE_TYPE_RELEASE":     2,
		"EDGE_TYPE_FLIP":        3,
	}
)

func (x EdgeType) Enum() *EdgeType {
	p := new(EdgeType)
	*p = x
	return p
}

func (x EdgeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EdgeType) Descriptor() protoreflect.EnumDescriptor {
	return file_thinhthan_v1_movement_proto_enumTypes[3].Descriptor()
}

func (EdgeType) Type() protoreflect.EnumType {
	return &file_thinhthan_v1_movement_proto_enumTypes[3]
}

func (x EdgeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EdgeType.Descriptor instead.
func (EdgeType) EnumDescriptor() ([]byte, []int) {
	return file_thinhthan_v1_movement_proto_rawDescGZIP(), []int{3}
}

// Direction — horizontal direction of a movement edge.
type Direction int32

const (
	Direction_DIRECTION_UNSPECIFIED Direction = 0
	Direction_DIRECTION_LEFT        Direction = 1
	Direction_DIRECTION_RIGHT       Direction = 2
)

// Enum value maps for Direction.
var (
	Direction_name = map[int32]string{
		0: "DIRECTION_UNSPECIFIED",
		1: "DIRECTION_LEFT",
		2: "DIRECTION_RIGHT",
	}
	Direction_value = map[string]int32{
		"DIRECTION_UNSPECIFIED": 0,
		"DIRECTION_LEFT":        1,
		"DIRECTION_RIGHT":       2,
	}
)

func (x Direction) Enum() *Direction {
	p := new(Direction)
	*p = x
	return p
}

func (x Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_thinhthan_v1_movement_proto_enumTypes[4].Descriptor()
}

func (Direction) Type() protoreflect.EnumType {
	return &file_thinhthan_v1_movement_proto_enumTypes[4]
}

func (x Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Direction.Descriptor instead.
func (Direction) EnumDescriptor() ([]byte, []int) {
	return file_thinhthan_v1_movement_proto_rawDescGZIP(), []int{4}
}

// DungeonRunTag — dungeon run variant (07_content/dungeon_catalog.md).
type DungeonRunTag int32

const (
	DungeonRunTag_DUNGEON_RUN_TAG_UNSPECIFIED DungeonRunTag = 0
	DungeonRunTag_DUNGEON_RUN_TAG_NORMAL      DungeonRunTag = 1
	DungeonRunTag_DUNGEON_RUN_TAG_ENDGAME_L60 DungeonRunTag = 2
)

// Enum value maps for DungeonRunTag.
var (
	DungeonRunTag_name = map[int32]string{
		0: "DUNGEON_RUN_TAG_UNSPECIFIED",
		1: "DUNGEON_RUN_TAG_NORMAL",
		2: "DUNGEON_RUN_TAG_ENDGAME_L60",
	}
	DungeonRunTag_value = map[string]int32{
		"DUNGEON_RUN_TAG_UNSPECIFIED": 0,
		"DUNGEON_RUN_TAG_NORMAL":      1,
		"DUNGEON_RUN_TAG_ENDGAME_L60": 2,
	}
)

func (x DungeonRunTag) Enum() *DungeonRunTag {
	p := new(DungeonRunTag)
	*p = x
	return p
}

func (x DungeonRunTag) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DungeonRunTag) Descriptor() protoreflect.EnumDescriptor {
	return file_thinhthan_v1_movement_proto_enumTypes[5].Descriptor()
}

func (DungeonRunTag) Type() protoreflect.EnumType {
	return &file_thinhthan_v1_movement_proto_enumTypes[5]
}

func (x DungeonRunTag) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DungeonRunTag.Descriptor instead.
func (DungeonRunTag) EnumDescriptor() ([]byte, []int) {
	return file_thinhthan_v1_movement_proto_rawDescGZIP(), []int{5}
}

// DungeonEntryResponse — one prompted member's response inside 112.
type DungeonEntryResponse int32

const (
	DungeonEntryResponse_DUNGEON_ENTRY_RESPONSE_UNSPECIFIED DungeonEntryResponse = 0
	DungeonEntryResponse_DUNGEON_ENTRY_RESPONSE_PENDING     DungeonEntryResponse = 1
	DungeonEntryResponse_DUNGEON_ENTRY_RESPONSE_ACCEPTED    DungeonEntryResponse = 2
	DungeonEntryResponse_DUNGEON_ENTRY_RESPONSE_DECLINED    DungeonEntryResponse = 3
	DungeonEntryResponse_DUNGEON_ENTRY_RESPONSE_INELIGIBLE  DungeonEntryResponse = 4
)

// Enum value maps for DungeonEntryResponse.
var (
	DungeonEntryResponse_name = map[int32]string{
		0: "DUNGEON_ENTRY_RESPONSE_UNSPECIFIED",
		1: "DUNGEON_ENTRY_RESPONSE_PENDING",
		2: "DUNGEON_ENTRY_RESPONSE_ACCEPTED",
		3: "DUNGEON_ENTRY_RESPONSE_DECLINED",
		4: "DUNGEON_ENTRY_RESPONSE_INELIGIBLE",
	}
	DungeonEntryResponse_value = map[string]int32{
		"DUNGEON_ENTRY_RESPONSE_UNSPECIFIED": 0,
		"DUNGEON_ENTRY_RESPONSE_PENDING":     1,
		"DUNGEON_ENTRY_RESPONSE_ACCEPTED":    2,
		"DUNGEON_ENTRY_RESPONSE_DECLINED":    3,
		"DUNGEON_ENTRY_RESPONSE_INELIGIBLE":  4,
	}
)

func (x DungeonEntryResponse) Enum() *DungeonEntryResponse {
	p := new(DungeonEntryResponse)
	*p = x
	return p
}

func (x DungeonEntryResponse) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DungeonEntryResponse) Descriptor() protoreflect.EnumDescriptor {
	return file_thinhthan_v1_movement_proto_enumTypes[6].Descriptor()
}

func (DungeonEntryResponse) Type() protoreflect.EnumType {
	return &file_thinhthan_v1_movement_proto_enumTypes[6]
}

func (x DungeonEntryResponse) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DungeonEntryResponse.Descriptor instead.
func (DungeonEntryResponse) EnumDescriptor() ([]byte, []int) {
	return file_thinhthan_v1_movement_proto_rawDescGZIP(), []int{6}
}

// DungeonEntryOutcome — pending-entry lifecycle outcome.
type DungeonEntryOutcome int32

const (
	DungeonEntryOutcome_DUNGEON_ENTRY_OUTCOME_UNSPECIFIED DungeonEntryOutcome = 0
	DungeonEntryOutcome_DUNGEON_ENTRY_OUTCOME_PENDING     DungeonEntryOutcome = 1
	DungeonEntryOutcome_DUNGEON_ENTRY_OUTCOME_CREATED     DungeonEntryOutcome = 2
	DungeonEntryOutcome_DUNGEON_ENTRY_OUTCOME_CANCELLED   DungeonEntryOutcome = 3
)

// Enum value maps for DungeonEntryOutcome.
var (
	DungeonEntryOutcome_name = map[int32]string{
		0: "DUNGEON_ENTRY_OUTCOME_UNSPECIFIED",
		1: "DUNGEON_ENTRY_OUTCOME_PENDING",
		2: "DUNGEON_ENTRY_OUTCOME_CREATED",
		3: "DUNGEON_ENTRY_OUTCOME_CANCELLED",
	}
	DungeonEntryOutcome_value = map[string]int32{
		"DUNGEON_ENTRY_OUTCOME_UNSPECIFIED": 0,
		"DUNGEON_ENTRY_OUTCOME_PENDING":     1,
		"DUNGEON_ENTRY_OUTCOME_CREATED":     2,
		"DUNGEON_ENTRY_OUTCOME_CANCELLED":   3,
	}
)

func (x DungeonEntryOutcome) Enum() *DungeonEntryOutcome {
	p := new(DungeonEntryOutcome)
	*p = x
	return p
}

func (x DungeonEntryOutcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DungeonEntryOutcome) Descriptor() protoreflect.EnumDescriptor {
	return file_thinhthan_v1_movement_proto_enumTypes[7].Descriptor()
}

func (DungeonEntryOutcome) Type() protoreflect.EnumType {
	return &file_thinhthan_v1_movement_proto_enumTypes[7]
}

func (x DungeonEntryOutcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DungeonEntryOutcome.Descriptor instead.
func (DungeonEntryOutcome) EnumDescriptor() ([]byte, []int) {
	return file_thinhthan_v1_movement_proto_rawDescGZIP(), []int{7}
}

// DungeonEntryDecision — answer to a dungeon-entry prompt (113).
type DungeonEntryDecision int32

const (
	DungeonEntryDecision_DUNGEON_ENTRY_DECISION_UNSPECIFIED DungeonEntryDecision = 0
	DungeonEntryDecision_DUNGEON_ENTRY_DECISION_ACCEPT      DungeonEntryDecision = 1
	DungeonEntryDecision_DUNGEON_ENTRY_DECISION_DECLINE     DungeonEntryDecision = 2
)

// Enum value maps for DungeonEntryDecision.
var (
	DungeonEntryDecision_name = map[int32]string{
		0: "DUNGEON_ENTRY_DECISION_UNSPECIFIED",
		1: "DUNGEON_ENTRY_DECISION_ACCEPT",
		2: "DUNGEON_ENTRY_DECISION_DECLINE",
	}
	DungeonEntryDecision_value = map[string]int32{
		"DUNGEON_ENTRY_DECISION_UNSPECIFIED": 0,
		"DUNGEON_ENTRY_DECISION_ACCEPT":      1,
		"DUNGEON_ENTRY_DECISION_DECLINE":     2,
	}
)

func (x DungeonEntryDecision) Enum() *DungeonEntryDecision {
	p := new(DungeonEntryDecision)
	*p = x
	return p
}

func (x DungeonEntryDecision) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DungeonEntryDecision) Descriptor() protoreflect.EnumDescriptor {
	return file_thinhthan_v1_movement_proto_enumTypes[8].Descriptor()
}

func (DungeonEntryDecision) Type() protoreflect.EnumType {
	return &file_thinhthan_v1_movement_proto_enumTypes[8]
}

func (x DungeonEntryDecision) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DungeonEntryDecision.Descriptor instead.
func (DungeonEntryDecision) EnumDescriptor() ([]byte, []int) {
	return file_thinhthan_v1_movement_proto_rawDescGZIP(), []int{8}
}

// DungeonLeaveMode — 114 EXIT keeps re-entry; ABANDON forfeits it.
type DungeonLeaveMode int32

const (
	DungeonLeaveMode_DUNGEON_LEAVE_MODE_UNSPECIFIED DungeonLeaveMode = 0
	DungeonLeaveMode_DUNGEON_LEAVE_MODE_EXIT        DungeonLeaveMode = 1
	DungeonLeaveMode_DUNGEON_LEAVE_MODE_ABANDON     DungeonLeaveMode = 2
)

// Enum value maps for DungeonLeaveMode.
var (
	DungeonLeaveMode_name = map[int32]string{
		0: "DUNGEON_LEAVE_MODE_UNSPECIFIED",
		1: "DUNGEON_LEAVE_MODE_EXIT",
		2: "DUNGEON_LEAVE_MODE_ABANDON",
	}
	DungeonLeaveMode_value = map[string]int32{
		"DUNGEON_LEAVE_MODE_UNSPECIFIED": 0,
		"DUNGEON_LEAVE_MODE_EXIT":        1,
		"DUNGEON_LEAVE_MODE_ABANDON":     2,
	}
)

func (x DungeonLeaveMode) Enum() *DungeonLeaveMode {
	p := new(DungeonLeaveMode)
	*p = x
	return p
}

func (x DungeonLeaveMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DungeonLeaveMode) Descriptor() protoreflect.EnumDescriptor {
	return file_thinhthan_v1_movement_proto_enumTypes[9].Descriptor()
}

func (DungeonLeaveMode) Type() protoreflect.EnumType {
	return &file_thinhthan_v1_movement_proto_enumTypes[9]
}

func (x DungeonLeaveMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DungeonLeaveMode.Descriptor instead.
func (DungeonLeaveMode) EnumDescriptor() ([]byte, []int) {
	return file_thinhthan_v1_movement_proto_rawDescGZIP(), []int{9}
}

// C2S_INPUT_STATE (100) — REPLACEABLE_STATE; held-state may coalesce.
// sequence = envelope client_seq; payloads never repeat it.
type C2S_INPUT_STATE struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InputFlags    uint32                 `protobuf:"varint,1,opt,name=input_flags,json=inputFlags,proto3" json:"input_flags,omitempty"`         // bitmask of held directions/actions (movement.md)
	ClientMonoMs  uint64                 `protobuf:"varint,2,opt,name=client_mono_ms,json=clientMonoMs,proto3" json:"client_mono_ms,omitempty"` // client monotonic ms, advisory only
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S_INPUT_STATE) Reset() {
	*x = C2S_INPUT_STATE{}
	mi := &file_thinhthan_v1_movement_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_INPUT_STATE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_INPUT_STATE) ProtoMessage() {}

func (x *C2S_INPUT_STATE) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_movement_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_INPUT_STATE.ProtoReflect.Descriptor instead.
func (*C2S_INPUT_STATE) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_movement_proto_rawDescGZIP(), []int{0}
}

func (x *C2S_INPUT_STATE) GetInputFlags() uint32 {
	if x != nil {
		return x.InputFlags
	}
	return 0
}

func (x *C2S_INPUT_STATE) GetClientMonoMs() uint64 {
	if x != nil {
		return x.ClientMonoMs
	}
	return 0
}

// C2S_JUMP (101) — discrete; never merged.
type C2S_JUMP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientMonoMs  uint64                 `protobuf:"varint,1,opt,name=client_mono_ms,json=clientMonoMs,proto3" json:"client_mono_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S_JUMP) Reset() {
	*x = C2S_JUMP{}
	mi := &file_thinhthan_v1_movement_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_JUMP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_JUMP) ProtoMessage() {}

func (x *C2S_JUMP) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_movement_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_JUMP.ProtoReflect.Descriptor instead.
func (*C2S_JUMP) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_movement_proto_rawDescGZIP(), []int{1}
}

func (x *C2S_JUMP) GetClientMonoMs() uint64 {
	if x != nil {
		return x.ClientMonoMs
	}
	return 0
}

// C2S_DROP_THROUGH (102) — discrete; never merged.
type C2S_DROP_THROUGH struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientMonoMs  uint64                 `protobuf:"varint,1,opt,name=client_mono_ms,json=clientMonoMs,proto3" json:"client_mono_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S_DROP_THROUGH) Reset() {
	*x = C2S_DROP_THROUGH{}
	mi := &file_thinhthan_v1_movement_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_DROP_THROUGH) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_DROP_THROUGH) ProtoMessage() {}

func (x *C2S_DROP_THROUGH) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_movement_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_DROP_THROUGH.ProtoReflect.Descriptor instead.
func (*C2S_DROP_THROUGH) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_movement_proto_rawDescGZIP(), []int{2}
}

func (x *C2S_DROP_THROUGH) GetClientMonoMs() uint64 {
	if x != nil {
		return x.ClientMonoMs
	}
	return 0
}

// C2S_INTERACT (103) — DISCRETE_INTENT; validated individually.
type C2S_INTERACT struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	InteractKind                InteractKind           `protobuf:"varint,1,opt,name=interact_kind,json=interactKind,proto3,enum=thinhthan.v1.InteractKind" json:"interact_kind,omitempty"`
	TargetId                    string                 `protobuf:"bytes,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`                                                                // entity or interactive object ID
	OperationId                 []byte                 `protobuf:"bytes,3,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`                                                       // UUID, 16 bytes
	RecipeId                    string                 `protobuf:"bytes,4,opt,name=recipe_id,json=recipeId,proto3" json:"recipe_id,omitempty"`                                                                // required when COOK; empty otherwise
	PublicBossSpawnGenerationId []byte                 `protobuf:"bytes,5,opt,name=public_boss_spawn_generation_id,json=publicBossSpawnGenerationId,proto3" json:"public_boss_spawn_generation_id,omitempty"` // UUID; CHEST on public-boss chest only
	ServiceId                   string                 `protobuf:"bytes,6,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`                                                             // NPC_SERVICE: set_checkpoint | travel
	ServiceParam                string                 `protobuf:"bytes,7,opt,name=service_param,json=serviceParam,proto3" json:"service_param,omitempty"`                                                    // travel: destination map_id;
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *C2S_INTERACT) Reset() {
	*x = C2S_INTERACT{}
	mi := &file_thinhthan_v1_movement_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_INTERACT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_INTERACT) ProtoMessage() {}

func (x *C2S_INTERACT) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_movement_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_INTERACT.ProtoReflect.Descriptor instead.
func (*C2S_INTERACT) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_movement_proto_rawDescGZIP(), []int{3}
}

func (x *C2S_INTERACT) GetInteractKind() InteractKind {
	if x != nil {
		return x.InteractKind
	}
	return InteractKind_INTERACT_KIND_UNSPECIFIED
}

func (x *C2S_INTERACT) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *C2S_INTERACT) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

func (x *C2S_INTERACT) GetRecipeId() string {
	if x != nil {
		return x.RecipeId
	}
	return ""
}

func (x *C2S_INTERACT) GetPublicBossSpawnGenerationId() []byte {
	if x != nil {
		return x.PublicBossSpawnGenerationId
	}
	return nil
}

func (x *C2S_INTERACT) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *C2S_INTERACT) GetServiceParam() string {
	if x != nil {
		return x.ServiceParam
	}
	return ""
}

// C2S_PORTAL_USE (104) — answered by exactly one 116 with
// interact_kind = PORTAL; SUCCESS is followed by 105.
type C2S_PORTAL_USE struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   []byte                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"` // UUID, 16 bytes
	PortalId      string                 `protobuf:"bytes,2,opt,name=portal_id,json=portalId,proto3" json:"portal_id,omitempty"`          // portal object ID (02_world/maps_zones.md)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S_PORTAL_USE) Reset() {
	*x = C2S_PORTAL_USE{}
	mi := &file_thinhthan_v1_movement_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_PORTAL_USE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_PORTAL_USE) ProtoMessage() {}

func (x *C2S_PORTAL_USE) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_movement_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_PORTAL_USE.ProtoReflect.Descriptor instead.
func (*C2S_PORTAL_USE) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_movement_proto_rawDescGZIP(), []int{4}
}

func (x *C2S_PORTAL_USE) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

func (x *C2S_PORTAL_USE) GetPortalId() string {
	if x != nil {
		return x.PortalId
	}
	return ""
}

// S2C_TRANSFER_PREPARE (105) — authorizes a map/channel/instance destination;
// client replies 106 with the same transfer_id.
type S2C_TRANSFER_PREPARE struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TransferId      []byte                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"` // 16 bytes
	Reason          TransferReason         `protobuf:"varint,2,opt,name=reason,proto3,enum=thinhthan.v1.TransferReason" json:"reason,omitempty"`
	MapId           string                 `protobuf:"bytes,3,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`                       // content ID
	ChannelIndex    uint32                 `protobuf:"varint,4,opt,name=channel_index,json=channelIndex,proto3" json:"channel_index,omitempty"` // 0 for instances
	InstanceId      []byte                 `protobuf:"bytes,5,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`        // 16 bytes; empty in the normal world
	ContentRevision string                 `protobuf:"bytes,6,opt,name=content_revision,json=contentRevision,proto3" json:"content_revision,omitempty"`
	ReadyDeadlineMs uint32                 `protobuf:"varint,7,opt,name=ready_deadline_ms,json=readyDeadlineMs,proto3" json:"ready_deadline_ms,omitempty"` // TRANSFER_BUDGET_* (04_architecture/concurrency.md)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *S2C_TRANSFER_PREPARE) Reset() {
	*x = S2C_TRANSFER_PREPARE{}
	mi := &file_thinhthan_v1_movement_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_TRANSFER_PREPARE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_TRANSFER_PREPARE) ProtoMessage() {}

func (x *S2C_TRANSFER_PREPARE) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_movement_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_TRANSFER_PREPARE.ProtoReflect.Descriptor instead.
func (*S2C_TRANSFER_PREPARE) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_movement_proto_rawDescGZIP(), []int{5}
}

func (x *S2C_TRANSFER_PREPARE) GetTransferId() []byte {
	if x != nil {
		return x.TransferId
	}
	return nil
}

func (x *S2C_TRANSFER_PREPARE) GetReason() TransferReason {
	if x != nil {
		return x.Reason
	}
	return TransferReason_TRANSFER_REASON_UNSPECIFIED
}

func (x *S2C_TRANSFER_PREPARE) GetMapId() string {
	if x != nil {
		return x.MapId
	}
	return ""
}

func (x *S2C_TRANSFER_PREPARE) GetChannelIndex() uint32 {
	if x != nil {
		return x.ChannelIndex
	}
	return 0
}

func (x *S2C_TRANSFER_PREPARE) GetInstanceId() []byte {
	if x != nil {
		return x.InstanceId
	}
	return nil
}

func (x *S2C_TRANSFER_PREPARE) GetContentRevision() string {
	if x != nil {
		return x.ContentRevision
	}
	return ""
}

func (x *S2C_TRANSFER_PREPARE) GetReadyDeadlineMs() uint32 {
	if x != nil {
		return x.ReadyDeadlineMs
	}
	return 0
}

// C2S_PRESENTATION_READY (106) — client finished Addressables download.
type C2S_PRESENTATION_READY struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransferId    []byte                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"` // 16 bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S_PRESENTATION_READY) Reset() {
	*x = C2S_PRESENTATION_READY{}
	mi := &file_thinhthan_v1_movement_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_PRESENTATION_READY) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_PRESENTATION_READY) ProtoMessage() {}

func (x *C2S_PRESENTATION_READY) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_movement_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_PRESENTATION_READY.ProtoReflect.Descriptor instead.
func (*C2S_PRESENTATION_READY) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_movement_proto_rawDescGZIP(), []int{6}
}

func (x *C2S_PRESENTATION_READY) GetTransferId() []byte {
	if x != nil {
		return x.TransferId
	}
	return nil
}

// S2C_MOVEMENT_CORRECTION (107) — authoritative override; the client
// snaps/replays per synchronization.md § Local Reconciliation.
type S2C_MOVEMENT_CORRECTION struct {
	state                  protoimpl.MessageState   `protogen:"open.v1"`
	LastProcessedClientSeq uint64                   `protobuf:"varint,1,opt,name=last_processed_client_seq,json=lastProcessedClientSeq,proto3" json:"last_processed_client_seq,omitempty"`
	ServerTick             uint64                   `protobuf:"varint,2,opt,name=server_tick,json=serverTick,proto3" json:"server_tick,omitempty"`
	XMm                    int32                    `protobuf:"zigzag32,3,opt,name=x_mm,json=xMm,proto3" json:"x_mm,omitempty"`
	YMm                    int32                    `protobuf:"zigzag32,4,opt,name=y_mm,json=yMm,proto3" json:"y_mm,omitempty"`
	VxMmS                  int32                    `protobuf:"zigzag32,5,opt,name=vx_mm_s,json=vxMmS,proto3" json:"vx_mm_s,omitempty"`
	VyMmS                  int32                    `protobuf:"zigzag32,6,opt,name=vy_mm_s,json=vyMmS,proto3" json:"vy_mm_s,omitempty"`
	Facing                 Facing                   `protobuf:"varint,7,opt,name=facing,proto3,enum=thinhthan.v1.Facing" json:"facing,omitempty"`
	MovementState          MovementState            `protobuf:"varint,8,opt,name=movement_state,json=movementState,proto3,enum=thinhthan.v1.MovementState" json:"movement_state,omitempty"`
	PlatformId             string                   `protobuf:"bytes,9,opt,name=platform_id,json=platformId,proto3" json:"platform_id,omitempty"` // riding platform; empty = none
	Reason                 MovementCorrectionReason `protobuf:"varint,10,opt,name=reason,proto3,enum=thinhthan.v1.MovementCorrectionReason" json:"reason,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *S2C_MOVEMENT_CORRECTION) Reset() {
	*x = S2C_MOVEMENT_CORRECTION{}
	mi := &file_thinhthan_v1_movement_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_MOVEMENT_CORRECTION) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_MOVEMENT_CORRECTION) ProtoMessage() {}

func (x *S2C_MOVEMENT_CORRECTION) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_movement_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_MOVEMENT_CORRECTION.ProtoReflect.Descriptor instead.
func (*S2C_MOVEMENT_CORRECTION) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_movement_proto_rawDescGZIP(), []int{7}
}

func (x *S2C_MOVEMENT_CORRECTION) GetLastProcessedClientSeq() uint64 {
	if x != nil {
		return x.LastProcessedClientSeq
	}
	return 0
}

func (x *S2C_MOVEMENT_CORRECTION) GetServerTick() uint64 {
	if x != nil {
		return x.ServerTick
	}
	return 0
}

func (x *S2C_MOVEMENT_CORRECTION) GetXMm() int32 {
	if x != nil {
		return x.XMm
	}
	return 0
}

func (x *S2C_MOVEMENT_CORRECTION) GetYMm() int32 {
	if x != nil {
		return x.YMm
	}
	return 0
}

func (x *S2C_MOVEMENT_CORRECTION) GetVxMmS() int32 {
	if x != nil {
		return x.VxMmS
	}
	return 0
}

func (x *S2C_MOVEMENT_CORRECTION) GetVyMmS() int32 {
	if x != nil {
		return x.VyMmS
	}
	return 0
}

func (x *S2C_MOVEMENT_CORRECTION) GetFacing() Facing {
	if x != nil {
		return x.Facing
	}
	return Facing_FACING_UNSPECIFIED
}

func (x *S2C_MOVEMENT_CORRECTION) GetMovementState() MovementState {
	if x != nil {
		return x.MovementState
	}
	return MovementState_MOVEMENT_STATE_UNSPECIFIED
}

func (x *S2C_MOVEMENT_CORRECTION) GetPlatformId() string {
	if x != nil {
		return x.PlatformId
	}
	return ""
}

func (x *S2C_MOVEMENT_CORRECTION) GetReason() MovementCorrectionReason {
	if x != nil {
		return x.Reason
	}
	return MovementCorrectionReason_MOVEMENT_CORRECTION_REASON_UNSPECIFIED
}

// C2S_MOVEMENT_EDGE (108) — DISCRETE_INTENT; never coalesced or merged
// (ADR-0038; Just Guard timing, 01_gameplay/combat.md).
type C2S_MOVEMENT_EDGE struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EdgeType      EdgeType               `protobuf:"varint,1,opt,name=edge_type,json=edgeType,proto3,enum=thinhthan.v1.EdgeType" json:"edge_type,omitempty"`
	Direction     Direction              `protobuf:"varint,2,opt,name=direction,proto3,enum=thinhthan.v1.Direction" json:"direction,omitempty"`
	ClientMonoMs  uint64                 `protobuf:"varint,3,opt,name=client_mono_ms,json=clientMonoMs,proto3" json:"client_mono_ms,omitempty"` // advisory only
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S_MOVEMENT_EDGE) Reset() {
	*x = C2S_MOVEMENT_EDGE{}
	mi := &file_thinhthan_v1_movement_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_MOVEMENT_EDGE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_MOVEMENT_EDGE) ProtoMessage() {}

func (x *C2S_MOVEMENT_EDGE) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_movement_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_MOVEMENT_EDGE.ProtoReflect.Descriptor instead.
func (*C2S_MOVEMENT_EDGE) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_movement_proto_rawDescGZIP(), []int{8}
}

func (x *C2S_MOVEMENT_EDGE) GetEdgeType() EdgeType {
	if x != nil {
		return x.EdgeType
	}
	return EdgeType_EDGE_TYPE_UNSPECIFIED
}

func (x *C2S_MOVEMENT_EDGE) GetDirection() Direction {
	if x != nil {
		return x.Direction
	}
	return Direction_DIRECTION_UNSPECIFIED
}

func (x *C2S_MOVEMENT_EDGE) GetClientMonoMs() uint64 {
	if x != nil {
		return x.ClientMonoMs
	}
	return 0
}

// C2S_CHANNEL_SWITCH (109) — voluntary channel hop; 10 s cooldown after a
// successful switch (02_world/world_rules.md).
type C2S_CHANNEL_SWITCH struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	OperationId        []byte                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"` // UUID, 16 bytes
	TargetChannelIndex uint32                 `protobuf:"varint,2,opt,name=target_channel_index,json=targetChannelIndex,proto3" json:"target_channel_index,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *C2S_CHANNEL_SWITCH) Reset() {
	*x = C2S_CHANNEL_SWITCH{}
	mi := &file_thinhthan_v1_movement_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_CHANNEL_SWITCH) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_CHANNEL_SWITCH) ProtoMessage() {}

func (x *C2S_CHANNEL_SWITCH) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_movement_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_CHANNEL_SWITCH.ProtoReflect.Descriptor instead.
func (*C2S_CHANNEL_SWITCH) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_movement_proto_rawDescGZIP(), []int{9}
}

func (x *C2S_CHANNEL_SWITCH) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

func (x *C2S_CHANNEL_SWITCH) GetTargetChannelIndex() uint32 {
	if x != nil {
		return x.TargetChannelIndex
	}
	return 0
}

// S2C_CHANNEL_SWITCH_RESULT (110) — SUCCESS is followed by 105.
type S2C_CHANNEL_SWITCH_RESULT struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Result *OperationResult       `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"` // MAP_CAPACITY_FULL | COOLDOWN_ACTIVE |
	// IN_COMBAT | STATE_CONFLICT
	TargetChannelIndex uint32 `protobuf:"varint,2,opt,name=target_channel_index,json=targetChannelIndex,proto3" json:"target_channel_index,omitempty"`
	RetryAfterMs       uint32 `protobuf:"varint,3,opt,name=retry_after_ms,json=retryAfterMs,proto3" json:"retry_after_ms,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *S2C_CHANNEL_SWITCH_RESULT) Reset() {
	*x = S2C_CHANNEL_SWITCH_RESULT{}
	mi := &file_thinhthan_v1_movement_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_CHANNEL_SWITCH_RESULT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_CHANNEL_SWITCH_RESULT) ProtoMessage() {}

func (x *S2C_CHANNEL_SWITCH_RESULT) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_movement_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_CHANNEL_SWITCH_RESULT.ProtoReflect.Descriptor instead.
func (*S2C_CHANNEL_SWITCH_RESULT) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_movement_proto_rawDescGZIP(), []int{10}
}

func (x *S2C_CHANNEL_SWITCH_RESULT) GetResult() *OperationResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *S2C_CHANNEL_SWITCH_RESULT) GetTargetChannelIndex() uint32 {
	if x != nil {
		return x.TargetChannelIndex
	}
	return 0
}

func (x *S2C_CHANNEL_SWITCH_RESULT) GetRetryAfterMs() uint32 {
	if x != nil {
		return x.RetryAfterMs
	}
	return 0
}

// C2S_DUNGEON_ENTER_REQUEST (111) — starts an instance or prompts party
// members (02_world/dungeons.md § Entry / Membership).
type C2S_DUNGEON_ENTER_REQUEST struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   []byte                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"` // UUID, 16 bytes
	DungeonId     string                 `protobuf:"bytes,2,opt,name=dungeon_id,json=dungeonId,proto3" json:"dungeon_id,omitempty"`       // content ID
	RunTag        DungeonRunTag          `protobuf:"varint,3,opt,name=run_tag,json=runTag,proto3,enum=thinhthan.v1.DungeonRunTag" json:"run_tag,omitempty"`
	EntranceId    string                 `protobuf:"bytes,4,opt,name=entrance_id,json=entranceId,proto3" json:"entrance_id,omitempty"` // entrance object ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S_DUNGEON_ENTER_REQUEST) Reset() {
	*x = C2S_DUNGEON_ENTER_REQUEST{}
	mi := &file_thinhthan_v1_movement_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_DUNGEON_ENTER_REQUEST) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_DUNGEON_ENTER_REQUEST) ProtoMessage() {}

func (x *C2S_DUNGEON_ENTER_REQUEST) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_movement_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_DUNGEON_ENTER_REQUEST.ProtoReflect.Descriptor instead.
func (*C2S_DUNGEON_ENTER_REQUEST) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_movement_proto_rawDescGZIP(), []int{11}
}

func (x *C2S_DUNGEON_ENTER_REQUEST) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

func (x *C2S_DUNGEON_ENTER_REQUEST) GetDungeonId() string {
	if x != nil {
		return x.DungeonId
	}
	return ""
}

func (x *C2S_DUNGEON_ENTER_REQUEST) GetRunTag() DungeonRunTag {
	if x != nil {
		return x.RunTag
	}
	return DungeonRunTag_DUNGEON_RUN_TAG_UNSPECIFIED
}

func (x *C2S_DUNGEON_ENTER_REQUEST) GetEntranceId() string {
	if x != nil {
		return x.EntranceId
	}
	return ""
}

// DungeonEntryMember — one prompted party member inside 112.
type DungeonEntryMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   []byte                 `protobuf:"bytes,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"` // UUID, 16 bytes
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Response      DungeonEntryResponse   `protobuf:"varint,3,opt,name=response,proto3,enum=thinhthan.v1.DungeonEntryResponse" json:"response,omitempty"`
	ErrorCode     ErrorCode              `protobuf:"varint,4,opt,name=error_code,json=errorCode,proto3,enum=thinhthan.v1.ErrorCode" json:"error_code,omitempty"` // set when response == INELIGIBLE
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DungeonEntryMember) Reset() {
	*x = DungeonEntryMember{}
	mi := &file_thinhthan_v1_movement_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DungeonEntryMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DungeonEntryMember) ProtoMessage() {}

func (x *DungeonEntryMember) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_movement_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DungeonEntryMember.ProtoReflect.Descriptor instead.
func (*DungeonEntryMember) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_movement_proto_rawDescGZIP(), []int{12}
}

func (x *DungeonEntryMember) GetCharacterId() []byte {
	if x != nil {
		return x.CharacterId
	}
	return nil
}

func (x *DungeonEntryMember) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *DungeonEntryMember) GetResponse() DungeonEntryResponse {
	if x != nil {
		return x.Response
	}
	return DungeonEntryResponse_DUNGEON_ENTRY_RESPONSE_UNSPECIFIED
}

func (x *DungeonEntryMember) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

// S2C_DUNGEON_ENTRY_STATE (112) — pending-entry state to requester and every
// prompted member on each change.
type S2C_DUNGEON_ENTRY_STATE struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	EntryId     []byte                 `protobuf:"bytes,1,opt,name=entry_id,json=entryId,proto3" json:"entry_id,omitempty"`             // UUID, 16 bytes
	OperationId []byte                 `protobuf:"bytes,2,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"` // recipient's own 111/113/117 answered
	// by this message; empty otherwise
	Status               ResultStatus          `protobuf:"varint,3,opt,name=status,proto3,enum=thinhthan.v1.ResultStatus" json:"status,omitempty"`
	ErrorCode            ErrorCode             `protobuf:"varint,4,opt,name=error_code,json=errorCode,proto3,enum=thinhthan.v1.ErrorCode" json:"error_code,omitempty"` // rejection of that request
	DungeonId            string                `protobuf:"bytes,5,opt,name=dungeon_id,json=dungeonId,proto3" json:"dungeon_id,omitempty"`
	RunTag               DungeonRunTag         `protobuf:"varint,6,opt,name=run_tag,json=runTag,proto3,enum=thinhthan.v1.DungeonRunTag" json:"run_tag,omitempty"`
	RequesterCharacterId []byte                `protobuf:"bytes,7,opt,name=requester_character_id,json=requesterCharacterId,proto3" json:"requester_character_id,omitempty"` // UUID, 16 bytes
	Members              []*DungeonEntryMember `protobuf:"bytes,8,rep,name=members,proto3" json:"members,omitempty"`
	ExpiresInMs          uint32                `protobuf:"varint,9,opt,name=expires_in_ms,json=expiresInMs,proto3" json:"expires_in_ms,omitempty"` // entry lifetime 30000
	Outcome              DungeonEntryOutcome   `protobuf:"varint,10,opt,name=outcome,proto3,enum=thinhthan.v1.DungeonEntryOutcome" json:"outcome,omitempty"`
	CancelReasonCode     ErrorCode             `protobuf:"varint,11,opt,name=cancel_reason_code,json=cancelReasonCode,proto3,enum=thinhthan.v1.ErrorCode" json:"cancel_reason_code,omitempty"` // set when outcome == CANCELLED
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *S2C_DUNGEON_ENTRY_STATE) Reset() {
	*x = S2C_DUNGEON_ENTRY_STATE{}
	mi := &file_thinhthan_v1_movement_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_DUNGEON_ENTRY_STATE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_DUNGEON_ENTRY_STATE) ProtoMessage() {}

func (x *S2C_DUNGEON_ENTRY_STATE) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_movement_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_DUNGEON_ENTRY_STATE.ProtoReflect.Descriptor instead.
func (*S2C_DUNGEON_ENTRY_STATE) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_movement_proto_rawDescGZIP(), []int{13}
}

func (x *S2C_DUNGEON_ENTRY_STATE) GetEntryId() []byte {
	if x != nil {
		return x.EntryId
	}
	return nil
}

func (x *S2C_DUNGEON_ENTRY_STATE) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

func (x *S2C_DUNGEON_ENTRY_STATE) GetStatus() ResultStatus {
	if x != nil {
		return x.Status
	}
	return ResultStatus_RESULT_STATUS_UNSPECIFIED
}

func (x *S2C_DUNGEON_ENTRY_STATE) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

func (x *S2C_DUNGEON_ENTRY_STATE) GetDungeonId() string {
	if x != nil {
		return x.DungeonId
	}
	return ""
}

func (x *S2C_DUNGEON_ENTRY_STATE) GetRunTag() DungeonRunTag {
	if x != nil {
		return x.RunTag
	}
	return DungeonRunTag_DUNGEON_RUN_TAG_UNSPECIFIED
}

func (x *S2C_DUNGEON_ENTRY_STATE) GetRequesterCharacterId() []byte {
	if x != nil {
		return x.RequesterCharacterId
	}
	return nil
}

func (x *S2C_DUNGEON_ENTRY_STATE) GetMembers() []*DungeonEntryMember {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *S2C_DUNGEON_ENTRY_STATE) GetExpiresInMs() uint32 {
	if x != nil {
		return x.ExpiresInMs
	}
	return 0
}

func (x *S2C_DUNGEON_ENTRY_STATE) GetOutcome() DungeonEntryOutcome {
	if x != nil {
		return x.Outcome
	}
	return DungeonEntryOutcome_DUNGEON_ENTRY_OUTCOME_UNSPECIFIED
}

func (x *S2C_DUNGEON_ENTRY_STATE) GetCancelReasonCode() ErrorCode {
	if x != nil {
		return x.CancelReasonCode
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

// C2S_DUNGEON_ENTRY_RESPOND (113) — prompted member answers the pending entry.
type C2S_DUNGEON_ENTRY_RESPOND struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   []byte                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"` // UUID, 16 bytes
	EntryId       []byte                 `protobuf:"bytes,2,opt,name=entry_id,json=entryId,proto3" json:"entry_id,omitempty"`             // UUID, 16 bytes
	Decision      DungeonEntryDecision   `protobuf:"varint,3,opt,name=decision,proto3,enum=thinhthan.v1.DungeonEntryDecision" json:"decision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S_DUNGEON_ENTRY_RESPOND) Reset() {
	*x = C2S_DUNGEON_ENTRY_RESPOND{}
	mi := &file_thinhthan_v1_movement_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_DUNGEON_ENTRY_RESPOND) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_DUNGEON_ENTRY_RESPOND) ProtoMessage() {}

func (x *C2S_DUNGEON_ENTRY_RESPOND) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_movement_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_DUNGEON_ENTRY_RESPOND.ProtoReflect.Descriptor instead.
func (*C2S_DUNGEON_ENTRY_RESPOND) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_movement_proto_rawDescGZIP(), []int{14}
}

func (x *C2S_DUNGEON_ENTRY_RESPOND) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

func (x *C2S_DUNGEON_ENTRY_RESPOND) GetEntryId() []byte {
	if x != nil {
		return x.EntryId
	}
	return nil
}

func (x *C2S_DUNGEON_ENTRY_RESPOND) GetDecision() DungeonEntryDecision {
	if x != nil {
		return x.Decision
	}
	return DungeonEntryDecision_DUNGEON_ENTRY_DECISION_UNSPECIFIED
}

// C2S_DUNGEON_LEAVE (114) — EXIT keeps re-entry before terminal lock;
// ABANDON forfeits completion eligibility and re-entry.
type C2S_DUNGEON_LEAVE struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   []byte                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"` // UUID, 16 bytes
	Mode          DungeonLeaveMode       `protobuf:"varint,2,opt,name=mode,proto3,enum=thinhthan.v1.DungeonLeaveMode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S_DUNGEON_LEAVE) Reset() {
	*x = C2S_DUNGEON_LEAVE{}
	mi := &file_thinhthan_v1_movement_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_DUNGEON_LEAVE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_DUNGEON_LEAVE) ProtoMessage() {}

func (x *C2S_DUNGEON_LEAVE) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_movement_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_DUNGEON_LEAVE.ProtoReflect.Descriptor instead.
func (*C2S_DUNGEON_LEAVE) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_movement_proto_rawDescGZIP(), []int{15}
}

func (x *C2S_DUNGEON_LEAVE) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

func (x *C2S_DUNGEON_LEAVE) GetMode() DungeonLeaveMode {
	if x != nil {
		return x.Mode
	}
	return DungeonLeaveMode_DUNGEON_LEAVE_MODE_UNSPECIFIED
}

// S2C_DUNGEON_LEAVE_RESULT (115).
type S2C_DUNGEON_LEAVE_RESULT struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *OperationResult       `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"` // IN_COMBAT (EXIT only)
	Mode          DungeonLeaveMode       `protobuf:"varint,2,opt,name=mode,proto3,enum=thinhthan.v1.DungeonLeaveMode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C_DUNGEON_LEAVE_RESULT) Reset() {
	*x = S2C_DUNGEON_LEAVE_RESULT{}
	mi := &file_thinhthan_v1_movement_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_DUNGEON_LEAVE_RESULT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_DUNGEON_LEAVE_RESULT) ProtoMessage() {}

func (x *S2C_DUNGEON_LEAVE_RESULT) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_movement_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_DUNGEON_LEAVE_RESULT.ProtoReflect.Descriptor instead.
func (*S2C_DUNGEON_LEAVE_RESULT) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_movement_proto_rawDescGZIP(), []int{16}
}

func (x *S2C_DUNGEON_LEAVE_RESULT) GetResult() *OperationResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *S2C_DUNGEON_LEAVE_RESULT) GetMode() DungeonLeaveMode {
	if x != nil {
		return x.Mode
	}
	return DungeonLeaveMode_DUNGEON_LEAVE_MODE_UNSPECIFIED
}

// S2C_INTERACT_RESULT (116) — exactly one per C2S_INTERACT (103) and
// C2S_PORTAL_USE (104).
type S2C_INTERACT_RESULT struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Result *OperationResult       `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"` // OUT_OF_RANGE | IN_COMBAT | INSUFFICIENT_CURRENCY
	// | INVENTORY_FULL | CHEST_ELIGIBILITY_INVALID |
	// NOT_DISCOVERED | LEVEL_TOO_LOW |
	// MAP_CAPACITY_FULL | STATE_CONFLICT | ...
	InteractKind  InteractKind     `protobuf:"varint,2,opt,name=interact_kind,json=interactKind,proto3,enum=thinhthan.v1.InteractKind" json:"interact_kind,omitempty"`
	TargetId      string           `protobuf:"bytes,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Granted       []*ItemQuantity  `protobuf:"bytes,4,rep,name=granted,proto3" json:"granted,omitempty"`                                  // pickup/chest/cook/fishing
	CurrencyDelta []*CurrencyDelta `protobuf:"bytes,5,rep,name=currency_delta,json=currencyDelta,proto3" json:"currency_delta,omitempty"` // travel fee, rest
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C_INTERACT_RESULT) Reset() {
	*x = S2C_INTERACT_RESULT{}
	mi := &file_thinhthan_v1_movement_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_INTERACT_RESULT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_INTERACT_RESULT) ProtoMessage() {}

func (x *S2C_INTERACT_RESULT) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_movement_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_INTERACT_RESULT.ProtoReflect.Descriptor instead.
func (*S2C_INTERACT_RESULT) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_movement_proto_rawDescGZIP(), []int{17}
}

func (x *S2C_INTERACT_RESULT) GetResult() *OperationResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *S2C_INTERACT_RESULT) GetInteractKind() InteractKind {
	if x != nil {
		return x.InteractKind
	}
	return InteractKind_INTERACT_KIND_UNSPECIFIED
}

func (x *S2C_INTERACT_RESULT) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *S2C_INTERACT_RESULT) GetGranted() []*ItemQuantity {
	if x != nil {
		return x.Granted
	}
	return nil
}

func (x *S2C_INTERACT_RESULT) GetCurrencyDelta() []*CurrencyDelta {
	if x != nil {
		return x.CurrencyDelta
	}
	return nil
}

// C2S_DUNGEON_ENTRY_CANCEL (117) — requester cancels a pending entry.
type C2S_DUNGEON_ENTRY_CANCEL struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   []byte                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"` // UUID, 16 bytes
	EntryId       []byte                 `protobuf:"bytes,2,opt,name=entry_id,json=entryId,proto3" json:"entry_id,omitempty"`             // UUID, 16 bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S_DUNGEON_ENTRY_CANCEL) Reset() {
	*x = C2S_DUNGEON_ENTRY_CANCEL{}
	mi := &file_thinhthan_v1_movement_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_DUNGEON_ENTRY_CANCEL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_DUNGEON_ENTRY_CANCEL) ProtoMessage() {}

func (x *C2S_DUNGEON_ENTRY_CANCEL) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_movement_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_DUNGEON_ENTRY_CANCEL.ProtoReflect.Descriptor instead.
func (*C2S_DUNGEON_ENTRY_CANCEL) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_movement_proto_rawDescGZIP(), []int{18}
}

func (x *C2S_DUNGEON_ENTRY_CANCEL) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

func (x *C2S_DUNGEON_ENTRY_CANCEL) GetEntryId() []byte {
	if x != nil {
		return x.EntryId
	}
	return nil
}

var File_thinhthan_v1_movement_proto protoreflect.FileDescriptor

const file_thinhthan_v1_movement_proto_rawDesc = "" +
	"\n" +
	"\x1bthinhthan/v1/movement.proto\x12\fthinhthan.v1\x1a\x19thinhthan/v1/common.proto\"X\n" +
	"\x0fC2S_INPUT_STATE\x12\x1f\n" +
	"\vinput_flags\x18\x01 \x01(\rR\n" +
	"inputFlags\x12$\n" +
	"\x0eclient_mono_ms\x18\x02 \x01(\x04R\fclientMonoMs\"0\n" +
	"\bC2S_JUMP\x12$\n" +
	"\x0eclient_mono_ms\x18\x01 \x01(\x04R\fclientMonoMs\"8\n" +
	"\x10C2S_DROP_THROUGH\x12$\n" +
	"\x0eclient_mono_ms\x18\x01 \x01(\x04R\fclientMonoMs\"\xb6\x02\n" +
	"\fC2S_INTERACT\x12?\n" +
	"\rinteract_kind\x18\x01 \x01(\x0e2\x1a.thinhthan.v1.InteractKindR\finteractKind\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\tR\btargetId\x12!\n" +
	"\foperation_id\x18\x03 \x01(\fR\voperationId\x12\x1b\n" +
	"\trecipe_id\x18\x04 \x01(\tR\brecipeId\x12D\n" +
	"\x1fpublic_boss_spawn_generation_id\x18\x05 \x01(\fR\x1bpublicBossSpawnGenerationId\x12\x1d\n" +
	"\n" +
	"service_id\x18\x06 \x01(\tR\tserviceId\x12#\n" +
	"\rservice_param\x18\a \x01(\tR\fserviceParam\"P\n" +
	"\x0eC2S_PORTAL_USE\x12!\n" +
	"\foperation_id\x18\x01 \x01(\fR\voperationId\x12\x1b\n" +
	"\tportal_id\x18\x02 \x01(\tR\bportalId\"\xa1\x02\n" +
	"\x14S2C_TRANSFER_PREPARE\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\fR\n" +
	"transferId\x124\n" +
	"\x06reason\x18\x02 \x01(\x0e2\x1c.thinhthan.v1.TransferReasonR\x06reason\x12\x15\n" +
	"\x06map_id\x18\x03 \x01(\tR\x05mapId\x12#\n" +
	"\rchannel_index\x18\x04 \x01(\rR\fchannelIndex\x12\x1f\n" +
	"\vinstance_id\x18\x05 \x01(\fR\n" +
	"instanceId\x12)\n" +
	"\x10content_revision\x18\x06 \x01(\tR\x0fcontentRevision\x12*\n" +
	"\x11ready_deadline_ms\x18\a \x01(\rR\x0freadyDeadlineMs\"9\n" +
	"\x16C2S_PRESENTATION_READY\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\fR\n" +
	"transferId\"\x9e\x03\n" +
	"\x17S2C_MOVEMENT_CORRECTION\x129\n" +
	"\x19last_processed_client_seq\x18\x01 \x01(\x04R\x16lastProcessedClientSeq\x12\x1f\n" +
	"\vserver_tick\x18\x02 \x01(\x04R\n" +
	"serverTick\x12\x11\n" +
	"\x04x_mm\x18\x03 \x01(\x11R\x03xMm\x12\x11\n" +
	"\x04y_mm\x18\x04 \x01(\x11R\x03yMm\x12\x16\n" +
	"\avx_mm_s\x18\x05 \x01(\x11R\x05vxMmS\x12\x16\n" +
	"\avy_mm_s\x18\x06 \x01(\x11R\x05vyMmS\x12,\n" +
	"\x06facing\x18\a \x01(\x0e2\x14.thinhthan.v1.FacingR\x06facing\x12B\n" +
	"\x0emovement_state\x18\b \x01(\x0e2\x1b.thinhthan.v1.MovementStateR\rmovementState\x12\x1f\n" +
	"\vplatform_id\x18\t \x01(\tR\n" +
	"platformId\x12>\n" +
	"\x06reason\x18\n" +
	" \x01(\x0e2&.thinhthan.v1.MovementCorrectionReasonR\x06reason\"\xa5\x01\n" +
	"\x11C2S_MOVEMENT_EDGE\x123\n" +
	"\tedge_type\x18\x01 \x01(\x0e2\x16.thinhthan.v1.EdgeTypeR\bedgeType\x125\n" +
	"\tdirection\x18\x02 \x01(\x0e2\x17.thinhthan.v1.DirectionR\tdirection\x12$\n" +
	"\x0eclient_mono_ms\x18\x03 \x01(\x04R\fclientMonoMs\"i\n" +
	"\x12C2S_CHANNEL_SWITCH\x12!\n" +
	"\foperation_id\x18\x01 \x01(\fR\voperationId\x120\n" +
	"\x14target_channel_index\x18\x02 \x01(\rR\x12targetChannelIndex\"\xaa\x01\n" +
	"\x19S2C_CHANNEL_SWITCH_RESULT\x125\n" +
	"\x06result\x18\x01 \x01(\v2\x1d.thinhthan.v1.OperationResultR\x06result\x120\n" +
	"\x14target_channel_index\x18\x02 \x01(\rR\x12targetChannelIndex\x12$\n" +
	"\x0eretry_after_ms\x18\x03 \x01(\rR\fretryAfterMs\"\xb4\x01\n" +
	"\x19C2S_DUNGEON_ENTER_REQUEST\x12!\n" +
	"\foperation_id\x18\x01 \x01(\fR\voperationId\x12\x1d\n" +
	"\n" +
	"dungeon_id\x18\x02 \x01(\tR\tdungeonId\x124\n" +
	"\arun_tag\x18\x03 \x01(\x0e2\x1b.thinhthan.v1.DungeonRunTagR\x06runTag\x12\x1f\n" +
	"\ventrance_id\x18\x04 \x01(\tR\n" +
	"entranceId\"\xd2\x01\n" +
	"\x12DungeonEntryMember\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\fR\vcharacterId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12>\n" +
	"\bresponse\x18\x03 \x01(\x0e2\".thinhthan.v1.DungeonEntryResponseR\bresponse\x126\n" +
	"\n" +
	"error_code\x18\x04 \x01(\x0e2\x17.thinhthan.v1.ErrorCodeR\terrorCode\"\xb2\x04\n" +
	"\x17S2C_DUNGEON_ENTRY_STATE\x12\x19\n" +
	"\bentry_id\x18\x01 \x01(\fR\aentryId\x12!\n" +
	"\foperation_id\x18\x02 \x01(\fR\voperationId\x122\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1a.thinhthan.v1.ResultStatusR\x06status\x126\n" +
	"\n" +
	"error_code\x18\x04 \x01(\x0e2\x17.thinhthan.v1.ErrorCodeR\terrorCode\x12\x1d\n" +
	"\n" +
	"dungeon_id\x18\x05 \x01(\tR\tdungeonId\x124\n" +
	"\arun_tag\x18\x06 \x01(\x0e2\x1b.thinhthan.v1.DungeonRunTagR\x06runTag\x124\n" +
	"\x16requester_character_id\x18\a \x01(\fR\x14requesterCharacterId\x12:\n" +
	"\amembers\x18\b \x03(\v2 .thinhthan.v1.DungeonEntryMemberR\amembers\x12\"\n" +
	"\rexpires_in_ms\x18\t \x01(\rR\vexpiresInMs\x12;\n" +
	"\aoutcome\x18\n" +
	" \x01(\x0e2!.thinhthan.v1.DungeonEntryOutcomeR\aoutcome\x12E\n" +
	"\x12cancel_reason_code\x18\v \x01(\x0e2\x17.thinhthan.v1.ErrorCodeR\x10cancelReasonCode\"\x99\x01\n" +
	"\x19C2S_DUNGEON_ENTRY_RESPOND\x12!\n" +
	"\foperation_id\x18\x01 \x01(\fR\voperationId\x12\x19\n" +
	"\bentry_id\x18\x02 \x01(\fR\aentryId\x12>\n" +
	"\bdecision\x18\x03 \x01(\x0e2\".thinhthan.v1.DungeonEntryDecisionR\bdecision\"j\n" +
	"\x11C2S_DUNGEON_LEAVE\x12!\n" +
	"\foperation_id\x18\x01 \x01(\fR\voperationId\x122\n" +
	"\x04mode\x18\x02 \x01(\x0e2\x1e.thinhthan.v1.DungeonLeaveModeR\x04mode\"\x85\x01\n" +
	"\x18S2C_DUNGEON_LEAVE_RESULT\x125\n" +
	"\x06result\x18\x01 \x01(\v2\x1d.thinhthan.v1.OperationResultR\x06result\x122\n" +
	"\x04mode\x18\x02 \x01(\x0e2\x1e.thinhthan.v1.DungeonLeaveModeR\x04mode\"\xa4\x02\n" +
	"\x13S2C_INTERACT_RESULT\x125\n" +
	"\x06result\x18\x01 \x01(\v2\x1d.thinhthan.v1.OperationResultR\x06result\x12?\n" +
	"\rinteract_kind\x18\x02 \x01(\x0e2\x1a.thinhthan.v1.InteractKindR\finteractKind\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\tR\btargetId\x124\n" +
	"\agranted\x18\x04 \x03(\v2\x1a.thinhthan.v1.ItemQuantityR\agranted\x12B\n" +
	"\x0ecurrency_delta\x18\x05 \x03(\v2\x1b.thinhthan.v1.CurrencyDeltaR\rcurrencyDelta\"X\n" +
	"\x18C2S_DUNGEON_ENTRY_CANCEL\x12!\n" +
	"\foperation_id\x18\x01 \x01(\fR\voperationId\x12\x19\n" +
	"\bentry_id\x18\x02 \x01(\fR\aentryId*\xd3\x02\n" +
	"\fInteractKind\x12\x1d\n" +
	"\x19INTERACT_KIND_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12INTERACT_KIND_TALK\x10\x01\x12\x18\n" +
	"\x14INTERACT_KIND_PICKUP\x10\x02\x12\x17\n" +
	"\x13INTERACT_KIND_CHEST\x10\x03\x12\x16\n" +
	"\x12INTERACT_KIND_CAST\x10\x04\x12\x16\n" +
	"\x12INTERACT_KIND_HOOK\x10\x05\x12\x18\n" +
	"\x14INTERACT_KIND_KINDLE\x10\x06\x12\x16\n" +
	"\x12INTERACT_KIND_COOK\x10\a\x12\x1e\n" +
	"\x1aINTERACT_KIND_BONFIRE_REST\x10\b\x12\x1e\n" +
	"\x1aINTERACT_KIND_QUEST_OBJECT\x10\t\x12\x1d\n" +
	"\x19INTERACT_KIND_NPC_SERVICE\x10\n" +
	"\x12\x18\n" +
	"\x14INTERACT_KIND_PORTAL\x10\v*\xc4\x02\n" +
	"\x0eTransferReason\x12\x1f\n" +
	"\x1bTRANSFER_REASON_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16TRANSFER_REASON_PORTAL\x10\x01\x12\x1a\n" +
	"\x16TRANSFER_REASON_TRAVEL\x10\x02\x12\"\n" +
	"\x1eTRANSFER_REASON_CHANNEL_SWITCH\x10\x03\x12!\n" +
	"\x1dTRANSFER_REASON_DUNGEON_ENTER\x10\x04\x12!\n" +
	"\x1dTRANSFER_REASON_DUNGEON_LEAVE\x10\x05\x12\x1b\n" +
	"\x17TRANSFER_REASON_RESPAWN\x10\x06\x12\x17\n" +
	"\x13TRANSFER_REASON_PVP\x10\a\x12\x1d\n" +
	"\x19TRANSFER_REASON_RECONNECT\x10\b\x12\x1a\n" +
	"\x16TRANSFER_REASON_FORCED\x10\t*\x93\x02\n" +
	"\x18MovementCorrectionReason\x12*\n" +
	"&MOVEMENT_CORRECTION_REASON_UNSPECIFIED\x10\x00\x12+\n" +
	"'MOVEMENT_CORRECTION_REASON_ILLEGAL_MOVE\x10\x01\x12(\n" +
	"$MOVEMENT_CORRECTION_REASON_KNOCKBACK\x10\x02\x12%\n" +
	"!MOVEMENT_CORRECTION_REASON_PORTAL\x10\x03\x12&\n" +
	"\"MOVEMENT_CORRECTION_REASON_RESPAWN\x10\x04\x12%\n" +
	"!MOVEMENT_CORRECTION_REASON_FORCED\x10\x05*e\n" +
	"\bEdgeType\x12\x19\n" +
	"\x15EDGE_TYPE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fEDGE_TYPE_PRESS\x10\x01\x12\x15\n" +
	"\x11EDGE_TYPE_RELEASE\x10\x02\x12\x12\n" +
	"\x0eEDGE_TYPE_FLIP\x10\x03*O\n" +
	"\tDirection\x12\x19\n" +
	"\x15DIRECTION_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eDIRECTION_LEFT\x10\x01\x12\x13\n" +
	"\x0fDIRECTION_RIGHT\x10\x02*m\n" +
	"\rDungeonRunTag\x12\x1f\n" +
	"\x1bDUNGEON_RUN_TAG_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16DUNGEON_RUN_TAG_NORMAL\x10\x01\x12\x1f\n" +
	"\x1bDUNGEON_RUN_TAG_ENDGAME_L60\x10\x02*\xd3\x01\n" +
	"\x14DungeonEntryResponse\x12&\n" +
	"\"DUNGEON_ENTRY_RESPONSE_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eDUNGEON_ENTRY_RESPONSE_PENDING\x10\x01\x12#\n" +
	"\x1fDUNGEON_ENTRY_RESPONSE_ACCEPTED\x10\x02\x12#\n" +
	"\x1fDUNGEON_ENTRY_RESPONSE_DECLINED\x10\x03\x12%\n" +
	"!DUNGEON_ENTRY_RESPONSE_INELIGIBLE\x10\x04*\xa7\x01\n" +
	"\x13DungeonEntryOutcome\x12%\n" +
	"!DUNGEON_ENTRY_OUTCOME_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dDUNGEON_ENTRY_OUTCOME_PENDING\x10\x01\x12!\n" +
	"\x1dDUNGEON_ENTRY_OUTCOME_CREATED\x10\x02\x12#\n" +
	"\x1fDUNGEON_ENTRY_OUTCOME_CANCELLED\x10\x03*\x85\x01\n" +
	"\x14DungeonEntryDecision\x12&\n" +
	"\"DUNGEON_ENTRY_DECISION_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dDUNGEON_ENTRY_DECISION_ACCEPT\x10\x01\x12\"\n" +
	"\x1eDUNGEON_ENTRY_DECISION_DECLINE\x10\x02*s\n" +
	"\x10DungeonLeaveMode\x12\"\n" +
	"\x1eDUNGEON_LEAVE_MODE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17DUNGEON_LEAVE_MODE_EXIT\x10\x01\x12\x1e\n" +
	"\x1aDUNGEON_LEAVE_MODE_ABANDON\x10\x02BCZ)thinhthan/internal/protocol/v1;protocolv1\xaa\x02\x15ThinhThan.Protocol.V1b\x06proto3"

var (
	file_thinhthan_v1_movement_proto_rawDescOnce sync.Once
	file_thinhthan_v1_movement_proto_rawDescData []byte
)

func file_thinhthan_v1_movement_proto_rawDescGZIP() []byte {
	file_thinhthan_v1_movement_proto_rawDescOnce.Do(func() {
		file_thinhthan_v1_movement_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_thinhthan_v1_movement_proto_rawDesc), len(file_thinhthan_v1_movement_proto_rawDesc)))
	})
	return file_thinhthan_v1_movement_proto_rawDescData
}

var file_thinhthan_v1_movement_proto_enumTypes = make([]protoimpl.EnumInfo, 10)
var file_thinhthan_v1_movement_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_thinhthan_v1_movement_proto_goTypes = []any{
	(InteractKind)(0),                 // 0: thinhthan.v1.InteractKind
	(TransferReason)(0),               // 1: thinhthan.v1.TransferReason
	(MovementCorrectionReason)(0),     // 2: thinhthan.v1.MovementCorrectionReason
	(EdgeType)(0),                     // 3: thinhthan.v1.EdgeType
	(Direction)(0),                    // 4: thinhthan.v1.Direction
	(DungeonRunTag)(0),                // 5: thinhthan.v1.DungeonRunTag
	(DungeonEntryResponse)(0),         // 6: thinhthan.v1.DungeonEntryResponse
	(DungeonEntryOutcome)(0),          // 7: thinhthan.v1.DungeonEntryOutcome
	(DungeonEntryDecision)(0),         // 8: thinhthan.v1.DungeonEntryDecision
	(DungeonLeaveMode)(0),             // 9: thinhthan.v1.DungeonLeaveMode
	(*C2S_INPUT_STATE)(nil),           // 10: thinhthan.v1.C2S_INPUT_STATE
	(*C2S_JUMP)(nil),                  // 11: thinhthan.v1.C2S_JUMP
	(*C2S_DROP_THROUGH)(nil),          // 12: thinhthan.v1.C2S_DROP_THROUGH
	(*C2S_INTERACT)(nil),              // 13: thinhthan.v1.C2S_INTERACT
	(*C2S_PORTAL_USE)(nil),            // 14: thinhthan.v1.C2S_PORTAL_USE
	(*S2C_TRANSFER_PREPARE)(nil),      // 15: thinhthan.v1.S2C_TRANSFER_PREPARE
	(*C2S_PRESENTATION_READY)(nil),    // 16: thinhthan.v1.C2S_PRESENTATION_READY
	(*S2C_MOVEMENT_CORRECTION)(nil),   // 17: thinhthan.v1.S2C_MOVEMENT_CORRECTION
	(*C2S_MOVEMENT_EDGE)(nil),         // 18: thinhthan.v1.C2S_MOVEMENT_EDGE
	(*C2S_CHANNEL_SWITCH)(nil),        // 19: thinhthan.v1.C2S_CHANNEL_SWITCH
	(*S2C_CHANNEL_SWITCH_RESULT)(nil), // 20: thinhthan.v1.S2C_CHANNEL_SWITCH_RESULT
	(*C2S_DUNGEON_ENTER_REQUEST)(nil), // 21: thinhthan.v1.C2S_DUNGEON_ENTER_REQUEST
	(*DungeonEntryMember)(nil),        // 22: thinhthan.v1.DungeonEntryMember
	(*S2C_DUNGEON_ENTRY_STATE)(nil),   // 23: thinhthan.v1.S2C_DUNGEON_ENTRY_STATE
	(*C2S_DUNGEON_ENTRY_RESPOND)(nil), // 24: thinhthan.v1.C2S_DUNGEON_ENTRY_RESPOND
	(*C2S_DUNGEON_LEAVE)(nil),         // 25: thinhthan.v1.C2S_DUNGEON_LEAVE
	(*S2C_DUNGEON_LEAVE_RESULT)(nil),  // 26: thinhthan.v1.S2C_DUNGEON_LEAVE_RESULT
	(*S2C_INTERACT_RESULT)(nil),       // 27: thinhthan.v1.S2C_INTERACT_RESULT
	(*C2S_DUNGEON_ENTRY_CANCEL)(nil),  // 28: thinhthan.v1.C2S_DUNGEON_ENTRY_CANCEL
	(Facing)(0),                       // 29: thinhthan.v1.Facing
	(MovementState)(0),                // 30: thinhthan.v1.MovementState
	(*OperationResult)(nil),           // 31: thinhthan.v1.OperationResult
	(ErrorCode)(0),                    // 32: thinhthan.v1.ErrorCode
	(ResultStatus)(0),                 // 33: thinhthan.v1.ResultStatus
	(*ItemQuantity)(nil),              // 34: thinhthan.v1.ItemQuantity
	(*CurrencyDelta)(nil),             // 35: thinhthan.v1.CurrencyDelta
}
var file_thinhthan_v1_movement_proto_depIdxs = []int32{
	0,  // 0: thinhthan.v1.C2S_INTERACT.interact_kind:type_name -> thinhthan.v1.InteractKind
	1,  // 1: thinhthan.v1.S2C_TRANSFER_PREPARE.reason:type_name -> thinhthan.v1.TransferReason
	29, // 2: thinhthan.v1.S2C_MOVEMENT_CORRECTION.facing:type_name -> thinhthan.v1.Facing
	30, // 3: thinhthan.v1.S2C_MOVEMENT_CORRECTION.movement_state:type_name -> thinhthan.v1.MovementState
	2,  // 4: thinhthan.v1.S2C_MOVEMENT_CORRECTION.reason:type_name -> thinhthan.v1.MovementCorrectionReason
	3,  // 5: thinhthan.v1.C2S_MOVEMENT_EDGE.edge_type:type_name -> thinhthan.v1.EdgeType
	4,  // 6: thinhthan.v1.C2S_MOVEMENT_EDGE.direction:type_name -> thinhthan.v1.Direction
	31, // 7: thinhthan.v1.S2C_CHANNEL_SWITCH_RESULT.result:type_name -> thinhthan.v1.OperationResult
	5,  // 8: thinhthan.v1.C2S_DUNGEON_ENTER_REQUEST.run_tag:type_name -> thinhthan.v1.DungeonRunTag
	6,  // 9: thinhthan.v1.DungeonEntryMember.response:type_name -> thinhthan.v1.DungeonEntryResponse
	32, // 10: thinhthan.v1.DungeonEntryMember.error_code:type_name -> thinhthan.v1.ErrorCode
	33, // 11: thinhthan.v1.S2C_DUNGEON_ENTRY_STATE.status:type_name -> thinhthan.v1.ResultStatus
	32, // 12: thinhthan.v1.S2C_DUNGEON_ENTRY_STATE.error_code:type_name -> thinhthan.v1.ErrorCode
	5,  // 13: thinhthan.v1.S2C_DUNGEON_ENTRY_STATE.run_tag:type_name -> thinhthan.v1.DungeonRunTag
	22, // 14: thinhthan.v1.S2C_DUNGEON_ENTRY_STATE.members:type_name -> thinhthan.v1.DungeonEntryMember
	7,  // 15: thinhthan.v1.S2C_DUNGEON_ENTRY_STATE.outcome:type_name -> thinhthan.v1.DungeonEntryOutcome
	32, // 16: thinhthan.v1.S2C_DUNGEON_ENTRY_STATE.cancel_reason_code:type_name -> thinhthan.v1.ErrorCode
	8,  // 17: thinhthan.v1.C2S_DUNGEON_ENTRY_RESPOND.decision:type_name -> thinhthan.v1.DungeonEntryDecision
	9,  // 18: thinhthan.v1.C2S_DUNGEON_LEAVE.mode:type_name -> thinhthan.v1.DungeonLeaveMode
	31, // 19: thinhthan.v1.S2C_DUNGEON_LEAVE_RESULT.result:type_name -> thinhthan.v1.OperationResult
	9,  // 20: thinhthan.v1.S2C_DUNGEON_LEAVE_RESULT.mode:type_name -> thinhthan.v1.DungeonLeaveMode
	31, // 21: thinhthan.v1.S2C_INTERACT_RESULT.result:type_name -> thinhthan.v1.OperationResult
	0,  // 22: thinhthan.v1.S2C_INTERACT_RESULT.interact_kind:type_name -> thinhthan.v1.InteractKind
	34, // 23: thinhthan.v1.S2C_INTERACT_RESULT.granted:type_name -> thinhthan.v1.ItemQuantity
	35, // 24: thinhthan.v1.S2C_INTERACT_RESULT.currency_delta:type_name -> thinhthan.v1.CurrencyDelta
	25, // [25:25] is the sub-list for method output_type
	25, // [25:25] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_thinhthan_v1_movement_proto_init() }
func file_thinhthan_v1_movement_proto_init() {
	if File_thinhthan_v1_movement_proto != nil {
		return
	}
	file_thinhthan_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_thinhthan_v1_movement_proto_rawDesc), len(file_thinhthan_v1_movement_proto_rawDesc)),
			NumEnums:      10,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_thinhthan_v1_movement_proto_goTypes,
		DependencyIndexes: file_thinhthan_v1_movement_proto_depIdxs,
		EnumInfos:         file_thinhthan_v1_movement_proto_enumTypes,
		MessageInfos:      file_thinhthan_v1_movement_proto_msgTypes,
	}.Build()
	File_thinhthan_v1_movement_proto = out.File
	file_thinhthan_v1_movement_proto_goTypes = nil
	file_thinhthan_v1_movement_proto_depIdxs = nil
}
