// PvP / Sparring / Duel / Guild War family (message IDs 800..819).
// Field lists: docs/05_network/messages.md § PvP / Guild War (ADR-0023,
// ADR-0060, ADR-0069). Every C2S carries operation_id and gets exactly one
// S2C_PVP_RESULT (819); 804 / 806 / 810 / 813 / 818 are the resulting state
// events — domain outcomes never use S2C_ERROR.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: thinhthan/v1/pvp.proto

package protocolv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// QueueUpdateState — ranked queue state pushed to the client (804).
type QueueUpdateState int32

const (
	QueueUpdateState_QUEUE_UPDATE_STATE_UNSPECIFIED QueueUpdateState = 0
	QueueUpdateState_QUEUE_UPDATE_STATE_QUEUED      QueueUpdateState = 1
	QueueUpdateState_QUEUE_UPDATE_STATE_MATCHED     QueueUpdateState = 2
	QueueUpdateState_QUEUE_UPDATE_STATE_ACCEPTING   QueueUpdateState = 3
	QueueUpdateState_QUEUE_UPDATE_STATE_LEFT        QueueUpdateState = 4
)

// Enum value maps for QueueUpdateState.
var (
	QueueUpdateState_name = map[int32]string{
		0: "QUEUE_UPDATE_STATE_UNSPECIFIED",
		1: "QUEUE_UPDATE_STATE_QUEUED",
		2: "QUEUE_UPDATE_STATE_MATCHED",
		3: "QUEUE_UPDATE_STATE_ACCEPTING",
		4: "QUEUE_UPDATE_STATE_LEFT",
	}
	QueueUpdateState_value = map[string]int32{
		"QUEUE_UPDATE_STATE_UNSPECIFIED": 0,
		"QUEUE_UPDATE_STATE_QUEUED":      1,
		"QUEUE_UPDATE_STATE_MATCHED":     2,
		"QUEUE_UPDATE_STATE_ACCEPTING":   3,
		"QUEUE_UPDATE_STATE_LEFT":        4,
	}
)

func (x QueueUpdateState) Enum() *QueueUpdateState {
	p := new(QueueUpdateState)
	*p = x
	return p
}

func (x QueueUpdateState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QueueUpdateState) Descriptor() protoreflect.EnumDescriptor {
	return file_thinhthan_v1_pvp_proto_enumTypes[0].Descriptor()
}

func (QueueUpdateState) Type() protoreflect.EnumType {
	return &file_thinhthan_v1_pvp_proto_enumTypes[0]
}

func (x QueueUpdateState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QueueUpdateState.Descriptor instead.
func (QueueUpdateState) EnumDescriptor() ([]byte, []int) {
	return file_thinhthan_v1_pvp_proto_rawDescGZIP(), []int{0}
}

// MatchLifecycle — shared match lifecycle (pvp.md / guild_war.md).
type MatchLifecycle int32

const (
	MatchLifecycle_MATCH_LIFECYCLE_UNSPECIFIED MatchLifecycle = 0
	MatchLifecycle_MATCH_LIFECYCLE_QUEUED      MatchLifecycle = 1
	MatchLifecycle_MATCH_LIFECYCLE_MATCHED     MatchLifecycle = 2
	MatchLifecycle_MATCH_LIFECYCLE_ACCEPTING   MatchLifecycle = 3
	MatchLifecycle_MATCH_LIFECYCLE_PREPARING   MatchLifecycle = 4
	MatchLifecycle_MATCH_LIFECYCLE_ACTIVE      MatchLifecycle = 5
	MatchLifecycle_MATCH_LIFECYCLE_RESOLVING   MatchLifecycle = 6
	MatchLifecycle_MATCH_LIFECYCLE_COMPLETED   MatchLifecycle = 7
	MatchLifecycle_MATCH_LIFECYCLE_CANCELLED   MatchLifecycle = 8
)

// Enum value maps for MatchLifecycle.
var (
	MatchLifecycle_name = map[int32]string{
		0: "MATCH_LIFECYCLE_UNSPECIFIED",
		1: "MATCH_LIFECYCLE_QUEUED",
		2: "MATCH_LIFECYCLE_MATCHED",
		3: "MATCH_LIFECYCLE_ACCEPTING",
		4: "MATCH_LIFECYCLE_PREPARING",
		5: "MATCH_LIFECYCLE_ACTIVE",
		6: "MATCH_LIFECYCLE_RESOLVING",
		7: "MATCH_LIFECYCLE_COMPLETED",
		8: "MATCH_LIFECYCLE_CANCELLED",
	}
	MatchLifecycle_value = map[string]int32{
		"MATCH_LIFECYCLE_UNSPECIFIED": 0,
		"MATCH_LIFECYCLE_QUEUED":      1,
		"MATCH_LIFECYCLE_MATCHED":     2,
		"MATCH_LIFECYCLE_ACCEPTING":   3,
		"MATCH_LIFECYCLE_PREPARING":   4,
		"MATCH_LIFECYCLE_ACTIVE":      5,
		"MATCH_LIFECYCLE_RESOLVING":   6,
		"MATCH_LIFECYCLE_COMPLETED":   7,
		"MATCH_LIFECYCLE_CANCELLED":   8,
	}
)

func (x MatchLifecycle) Enum() *MatchLifecycle {
	p := new(MatchLifecycle)
	*p = x
	return p
}

func (x MatchLifecycle) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MatchLifecycle) Descriptor() protoreflect.EnumDescriptor {
	return file_thinhthan_v1_pvp_proto_enumTypes[1].Descriptor()
}

func (MatchLifecycle) Type() protoreflect.EnumType {
	return &file_thinhthan_v1_pvp_proto_enumTypes[1]
}

func (x MatchLifecycle) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MatchLifecycle.Descriptor instead.
func (MatchLifecycle) EnumDescriptor() ([]byte, []int) {
	return file_thinhthan_v1_pvp_proto_rawDescGZIP(), []int{1}
}

// MatchResult — the receiver's team result inside 806.
type MatchResult int32

const (
	MatchResult_MATCH_RESULT_UNSPECIFIED MatchResult = 0
	MatchResult_MATCH_RESULT_NONE        MatchResult = 1
	MatchResult_MATCH_RESULT_WIN         MatchResult = 2
	MatchResult_MATCH_RESULT_LOSS        MatchResult = 3
	MatchResult_MATCH_RESULT_DRAW        MatchResult = 4
	MatchResult_MATCH_RESULT_VOID        MatchResult = 5
)

// Enum value maps for MatchResult.
var (
	MatchResult_name = map[int32]string{
		0: "MATCH_RESULT_UNSPECIFIED",
		1: "MATCH_RESULT_NONE",
		2: "MATCH_RESULT_WIN",
		3: "MATCH_RESULT_LOSS",
		4: "MATCH_RESULT_DRAW",
		5: "MATCH_RESULT_VOID",
	}
	MatchResult_value = map[string]int32{
		"MATCH_RESULT_UNSPECIFIED": 0,
		"MATCH_RESULT_NONE":        1,
		"MATCH_RESULT_WIN":         2,
		"MATCH_RESULT_LOSS":        3,
		"MATCH_RESULT_DRAW":        4,
		"MATCH_RESULT_VOID":        5,
	}
)

func (x MatchResult) Enum() *MatchResult {
	p := new(MatchResult)
	*p = x
	return p
}

func (x MatchResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MatchResult) Descriptor() protoreflect.EnumDescriptor {
	return file_thinhthan_v1_pvp_proto_enumTypes[2].Descriptor()
}

func (MatchResult) Type() protoreflect.EnumType {
	return &file_thinhthan_v1_pvp_proto_enumTypes[2]
}

func (x MatchResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MatchResult.Descriptor instead.
func (MatchResult) EnumDescriptor() ([]byte, []int) {
	return file_thinhthan_v1_pvp_proto_rawDescGZIP(), []int{2}
}

// ReadyDecision — ready-check / duel respond decision.
type ReadyDecision int32

const (
	ReadyDecision_READY_DECISION_UNSPECIFIED ReadyDecision = 0
	ReadyDecision_READY_DECISION_ACCEPT      ReadyDecision = 1
	ReadyDecision_READY_DECISION_DECLINE     ReadyDecision = 2
)

// Enum value maps for ReadyDecision.
var (
	ReadyDecision_name = map[int32]string{
		0: "READY_DECISION_UNSPECIFIED",
		1: "READY_DECISION_ACCEPT",
		2: "READY_DECISION_DECLINE",
	}
	ReadyDecision_value = map[string]int32{
		"READY_DECISION_UNSPECIFIED": 0,
		"READY_DECISION_ACCEPT":      1,
		"READY_DECISION_DECLINE":     2,
	}
)

func (x ReadyDecision) Enum() *ReadyDecision {
	p := new(ReadyDecision)
	*p = x
	return p
}

func (x ReadyDecision) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReadyDecision) Descriptor() protoreflect.EnumDescriptor {
	return file_thinhthan_v1_pvp_proto_enumTypes[3].Descriptor()
}

func (ReadyDecision) Type() protoreflect.EnumType {
	return &file_thinhthan_v1_pvp_proto_enumTypes[3]
}

func (x ReadyDecision) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReadyDecision.Descriptor instead.
func (ReadyDecision) EnumDescriptor() ([]byte, []int) {
	return file_thinhthan_v1_pvp_proto_rawDescGZIP(), []int{3}
}

// SparringOutcome — sparring challenge outcome (813).
type SparringOutcome int32

const (
	SparringOutcome_SPARRING_OUTCOME_UNSPECIFIED SparringOutcome = 0
	SparringOutcome_SPARRING_OUTCOME_ACCEPTED    SparringOutcome = 1
	SparringOutcome_SPARRING_OUTCOME_DECLINED    SparringOutcome = 2
	SparringOutcome_SPARRING_OUTCOME_EXPIRED     SparringOutcome = 3
	SparringOutcome_SPARRING_OUTCOME_REJECTED    SparringOutcome = 4
)

// Enum value maps for SparringOutcome.
var (
	SparringOutcome_name = map[int32]string{
		0: "SPARRING_OUTCOME_UNSPECIFIED",
		1: "SPARRING_OUTCOME_ACCEPTED",
		2: "SPARRING_OUTCOME_DECLINED",
		3: "SPARRING_OUTCOME_EXPIRED",
		4: "SPARRING_OUTCOME_REJECTED",
	}
	SparringOutcome_value = map[string]int32{
		"SPARRING_OUTCOME_UNSPECIFIED": 0,
		"SPARRING_OUTCOME_ACCEPTED":    1,
		"SPARRING_OUTCOME_DECLINED":    2,
		"SPARRING_OUTCOME_EXPIRED":     3,
		"SPARRING_OUTCOME_REJECTED":    4,
	}
)

func (x SparringOutcome) Enum() *SparringOutcome {
	p := new(SparringOutcome)
	*p = x
	return p
}

func (x SparringOutcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SparringOutcome) Descriptor() protoreflect.EnumDescriptor {
	return file_thinhthan_v1_pvp_proto_enumTypes[4].Descriptor()
}

func (SparringOutcome) Type() protoreflect.EnumType {
	return &file_thinhthan_v1_pvp_proto_enumTypes[4]
}

func (x SparringOutcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SparringOutcome.Descriptor instead.
func (SparringOutcome) EnumDescriptor() ([]byte, []int) {
	return file_thinhthan_v1_pvp_proto_rawDescGZIP(), []int{4}
}

// DuelOutcome — duel challenge outcome (818).
type DuelOutcome int32

const (
	DuelOutcome_DUEL_OUTCOME_UNSPECIFIED DuelOutcome = 0
	DuelOutcome_DUEL_OUTCOME_ACCEPTED    DuelOutcome = 1
	DuelOutcome_DUEL_OUTCOME_DECLINED    DuelOutcome = 2
	DuelOutcome_DUEL_OUTCOME_CANCELLED   DuelOutcome = 3
	DuelOutcome_DUEL_OUTCOME_EXPIRED     DuelOutcome = 4
	DuelOutcome_DUEL_OUTCOME_REJECTED    DuelOutcome = 5
)

// Enum value maps for DuelOutcome.
var (
	DuelOutcome_name = map[int32]string{
		0: "DUEL_OUTCOME_UNSPECIFIED",
		1: "DUEL_OUTCOME_ACCEPTED",
		2: "DUEL_OUTCOME_DECLINED",
		3: "DUEL_OUTCOME_CANCELLED",
		4: "DUEL_OUTCOME_EXPIRED",
		5: "DUEL_OUTCOME_REJECTED",
	}
	DuelOutcome_value = map[string]int32{
		"DUEL_OUTCOME_UNSPECIFIED": 0,
		"DUEL_OUTCOME_ACCEPTED":    1,
		"DUEL_OUTCOME_DECLINED":    2,
		"DUEL_OUTCOME_CANCELLED":   3,
		"DUEL_OUTCOME_EXPIRED":     4,
		"DUEL_OUTCOME_REJECTED":    5,
	}
)

func (x DuelOutcome) Enum() *DuelOutcome {
	p := new(DuelOutcome)
	*p = x
	return p
}

func (x DuelOutcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DuelOutcome) Descriptor() protoreflect.EnumDescriptor {
	return file_thinhthan_v1_pvp_proto_enumTypes[5].Descriptor()
}

func (DuelOutcome) Type() protoreflect.EnumType {
	return &file_thinhthan_v1_pvp_proto_enumTypes[5]
}

func (x DuelOutcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DuelOutcome.Descriptor instead.
func (DuelOutcome) EnumDescriptor() ([]byte, []int) {
	return file_thinhthan_v1_pvp_proto_rawDescGZIP(), []int{5}
}

// C2S_SPARRING_REQUEST (800) — casual duel challenge to a character in the
// same channel; both stand on the Sparring Ring platform
// (pvp.mode.sparring, ADR-0023); 60 s lifetime.
type C2S_SPARRING_REQUEST struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OperationId       []byte                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`                     // UUID, 16 bytes
	TargetCharacterId []byte                 `protobuf:"bytes,2,opt,name=target_character_id,json=targetCharacterId,proto3" json:"target_character_id,omitempty"` // UUID
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *C2S_SPARRING_REQUEST) Reset() {
	*x = C2S_SPARRING_REQUEST{}
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_SPARRING_REQUEST) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_SPARRING_REQUEST) ProtoMessage() {}

func (x *C2S_SPARRING_REQUEST) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_SPARRING_REQUEST.ProtoReflect.Descriptor instead.
func (*C2S_SPARRING_REQUEST) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_pvp_proto_rawDescGZIP(), []int{0}
}

func (x *C2S_SPARRING_REQUEST) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

func (x *C2S_SPARRING_REQUEST) GetTargetCharacterId() []byte {
	if x != nil {
		return x.TargetCharacterId
	}
	return nil
}

// C2S_SPARRING_ACCEPT (801) — the target's acceptance.
type C2S_SPARRING_ACCEPT struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   []byte                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"` // UUID, 16 bytes
	ChallengeId   []byte                 `protobuf:"bytes,2,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"` // UUID — from 811
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S_SPARRING_ACCEPT) Reset() {
	*x = C2S_SPARRING_ACCEPT{}
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_SPARRING_ACCEPT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_SPARRING_ACCEPT) ProtoMessage() {}

func (x *C2S_SPARRING_ACCEPT) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_SPARRING_ACCEPT.ProtoReflect.Descriptor instead.
func (*C2S_SPARRING_ACCEPT) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_pvp_proto_rawDescGZIP(), []int{1}
}

func (x *C2S_SPARRING_ACCEPT) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

func (x *C2S_SPARRING_ACCEPT) GetChallengeId() []byte {
	if x != nil {
		return x.ChallengeId
	}
	return nil
}

// S2C_SPARRING_CHALLENGE (811) — challenge delivered to the target.
type S2C_SPARRING_CHALLENGE struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ChallengeId           []byte                 `protobuf:"bytes,1,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`                                 // UUID
	ChallengerCharacterId []byte                 `protobuf:"bytes,2,opt,name=challenger_character_id,json=challengerCharacterId,proto3" json:"challenger_character_id,omitempty"` // UUID
	ChallengerName        string                 `protobuf:"bytes,3,opt,name=challenger_name,json=challengerName,proto3" json:"challenger_name,omitempty"`
	ExpiresInSeconds      uint32                 `protobuf:"varint,4,opt,name=expires_in_seconds,json=expiresInSeconds,proto3" json:"expires_in_seconds,omitempty"` // 60
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *S2C_SPARRING_CHALLENGE) Reset() {
	*x = S2C_SPARRING_CHALLENGE{}
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_SPARRING_CHALLENGE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_SPARRING_CHALLENGE) ProtoMessage() {}

func (x *S2C_SPARRING_CHALLENGE) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_SPARRING_CHALLENGE.ProtoReflect.Descriptor instead.
func (*S2C_SPARRING_CHALLENGE) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_pvp_proto_rawDescGZIP(), []int{2}
}

func (x *S2C_SPARRING_CHALLENGE) GetChallengeId() []byte {
	if x != nil {
		return x.ChallengeId
	}
	return nil
}

func (x *S2C_SPARRING_CHALLENGE) GetChallengerCharacterId() []byte {
	if x != nil {
		return x.ChallengerCharacterId
	}
	return nil
}

func (x *S2C_SPARRING_CHALLENGE) GetChallengerName() string {
	if x != nil {
		return x.ChallengerName
	}
	return ""
}

func (x *S2C_SPARRING_CHALLENGE) GetExpiresInSeconds() uint32 {
	if x != nil {
		return x.ExpiresInSeconds
	}
	return 0
}

// C2S_SPARRING_DECLINE (812).
type C2S_SPARRING_DECLINE struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   []byte                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"` // UUID, 16 bytes
	ChallengeId   []byte                 `protobuf:"bytes,2,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"` // UUID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S_SPARRING_DECLINE) Reset() {
	*x = C2S_SPARRING_DECLINE{}
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_SPARRING_DECLINE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_SPARRING_DECLINE) ProtoMessage() {}

func (x *C2S_SPARRING_DECLINE) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_SPARRING_DECLINE.ProtoReflect.Descriptor instead.
func (*C2S_SPARRING_DECLINE) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_pvp_proto_rawDescGZIP(), []int{3}
}

func (x *C2S_SPARRING_DECLINE) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

func (x *C2S_SPARRING_DECLINE) GetChallengeId() []byte {
	if x != nil {
		return x.ChallengeId
	}
	return nil
}

// S2C_SPARRING_OUTCOME (813) — to both parties on accept, decline, expiry or
// validation rejection. *_OUTCOME messages carry no OperationResult.
type S2C_SPARRING_OUTCOME struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChallengeId   []byte                 `protobuf:"bytes,1,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"` // UUID
	Outcome       SparringOutcome        `protobuf:"varint,2,opt,name=outcome,proto3,enum=thinhthan.v1.SparringOutcome" json:"outcome,omitempty"`
	ErrorCode     ErrorCode              `protobuf:"varint,3,opt,name=error_code,json=errorCode,proto3,enum=thinhthan.v1.ErrorCode" json:"error_code,omitempty"` // REJECTED only
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C_SPARRING_OUTCOME) Reset() {
	*x = S2C_SPARRING_OUTCOME{}
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_SPARRING_OUTCOME) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_SPARRING_OUTCOME) ProtoMessage() {}

func (x *S2C_SPARRING_OUTCOME) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_SPARRING_OUTCOME.ProtoReflect.Descriptor instead.
func (*S2C_SPARRING_OUTCOME) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_pvp_proto_rawDescGZIP(), []int{4}
}

func (x *S2C_SPARRING_OUTCOME) GetChallengeId() []byte {
	if x != nil {
		return x.ChallengeId
	}
	return nil
}

func (x *S2C_SPARRING_OUTCOME) GetOutcome() SparringOutcome {
	if x != nil {
		return x.Outcome
	}
	return SparringOutcome_SPARRING_OUTCOME_UNSPECIFIED
}

func (x *S2C_SPARRING_OUTCOME) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

// C2S_RANKED_QUEUE_JOIN (802) — Arena only: the party leader queues the
// whole party atomically (with_party).
type C2S_RANKED_QUEUE_JOIN struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   []byte                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"` // UUID, 16 bytes
	PvpModeId     string                 `protobuf:"bytes,2,opt,name=pvp_mode_id,json=pvpModeId,proto3" json:"pvp_mode_id,omitempty"`     // pvp.mode.ranked_duel | pvp.mode.five_element_arena
	WithParty     bool                   `protobuf:"varint,3,opt,name=with_party,json=withParty,proto3" json:"with_party,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S_RANKED_QUEUE_JOIN) Reset() {
	*x = C2S_RANKED_QUEUE_JOIN{}
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_RANKED_QUEUE_JOIN) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_RANKED_QUEUE_JOIN) ProtoMessage() {}

func (x *C2S_RANKED_QUEUE_JOIN) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_RANKED_QUEUE_JOIN.ProtoReflect.Descriptor instead.
func (*C2S_RANKED_QUEUE_JOIN) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_pvp_proto_rawDescGZIP(), []int{5}
}

func (x *C2S_RANKED_QUEUE_JOIN) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

func (x *C2S_RANKED_QUEUE_JOIN) GetPvpModeId() string {
	if x != nil {
		return x.PvpModeId
	}
	return ""
}

func (x *C2S_RANKED_QUEUE_JOIN) GetWithParty() bool {
	if x != nil {
		return x.WithParty
	}
	return false
}

// C2S_RANKED_QUEUE_LEAVE (803) — a party member leaving removes the whole
// party entry.
type C2S_RANKED_QUEUE_LEAVE struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   []byte                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"` // UUID, 16 bytes
	PvpModeId     string                 `protobuf:"bytes,2,opt,name=pvp_mode_id,json=pvpModeId,proto3" json:"pvp_mode_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S_RANKED_QUEUE_LEAVE) Reset() {
	*x = C2S_RANKED_QUEUE_LEAVE{}
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_RANKED_QUEUE_LEAVE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_RANKED_QUEUE_LEAVE) ProtoMessage() {}

func (x *C2S_RANKED_QUEUE_LEAVE) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_RANKED_QUEUE_LEAVE.ProtoReflect.Descriptor instead.
func (*C2S_RANKED_QUEUE_LEAVE) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_pvp_proto_rawDescGZIP(), []int{6}
}

func (x *C2S_RANKED_QUEUE_LEAVE) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

func (x *C2S_RANKED_QUEUE_LEAVE) GetPvpModeId() string {
	if x != nil {
		return x.PvpModeId
	}
	return ""
}

// S2C_RANKED_QUEUE_UPDATE (804) — queue position / MATCHED / ACCEPTING.
type S2C_RANKED_QUEUE_UPDATE struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PvpModeId       string                 `protobuf:"bytes,1,opt,name=pvp_mode_id,json=pvpModeId,proto3" json:"pvp_mode_id,omitempty"`
	State           QueueUpdateState       `protobuf:"varint,2,opt,name=state,proto3,enum=thinhthan.v1.QueueUpdateState" json:"state,omitempty"`
	QueuedSeconds   uint32                 `protobuf:"varint,3,opt,name=queued_seconds,json=queuedSeconds,proto3" json:"queued_seconds,omitempty"`
	PvpMatchId      []byte                 `protobuf:"bytes,4,opt,name=pvp_match_id,json=pvpMatchId,proto3" json:"pvp_match_id,omitempty"`                 // UUID; from MATCHED
	ReadyDeadlineMs int64                  `protobuf:"varint,5,opt,name=ready_deadline_ms,json=readyDeadlineMs,proto3" json:"ready_deadline_ms,omitempty"` // absolute Unix ms; ACCEPTING
	ErrorCode       ErrorCode              `protobuf:"varint,6,opt,name=error_code,json=errorCode,proto3,enum=thinhthan.v1.ErrorCode" json:"error_code,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *S2C_RANKED_QUEUE_UPDATE) Reset() {
	*x = S2C_RANKED_QUEUE_UPDATE{}
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_RANKED_QUEUE_UPDATE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_RANKED_QUEUE_UPDATE) ProtoMessage() {}

func (x *S2C_RANKED_QUEUE_UPDATE) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_RANKED_QUEUE_UPDATE.ProtoReflect.Descriptor instead.
func (*S2C_RANKED_QUEUE_UPDATE) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_pvp_proto_rawDescGZIP(), []int{7}
}

func (x *S2C_RANKED_QUEUE_UPDATE) GetPvpModeId() string {
	if x != nil {
		return x.PvpModeId
	}
	return ""
}

func (x *S2C_RANKED_QUEUE_UPDATE) GetState() QueueUpdateState {
	if x != nil {
		return x.State
	}
	return QueueUpdateState_QUEUE_UPDATE_STATE_UNSPECIFIED
}

func (x *S2C_RANKED_QUEUE_UPDATE) GetQueuedSeconds() uint32 {
	if x != nil {
		return x.QueuedSeconds
	}
	return 0
}

func (x *S2C_RANKED_QUEUE_UPDATE) GetPvpMatchId() []byte {
	if x != nil {
		return x.PvpMatchId
	}
	return nil
}

func (x *S2C_RANKED_QUEUE_UPDATE) GetReadyDeadlineMs() int64 {
	if x != nil {
		return x.ReadyDeadlineMs
	}
	return 0
}

func (x *S2C_RANKED_QUEUE_UPDATE) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

// C2S_MATCH_READY (805) — ready-check response.
type C2S_MATCH_READY struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   []byte                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"` // UUID, 16 bytes
	MatchId       []byte                 `protobuf:"bytes,2,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`             // UUID — pvp_match_id or guild_war_match_id
	Decision      ReadyDecision          `protobuf:"varint,3,opt,name=decision,proto3,enum=thinhthan.v1.ReadyDecision" json:"decision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S_MATCH_READY) Reset() {
	*x = C2S_MATCH_READY{}
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_MATCH_READY) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_MATCH_READY) ProtoMessage() {}

func (x *C2S_MATCH_READY) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_MATCH_READY.ProtoReflect.Descriptor instead.
func (*C2S_MATCH_READY) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_pvp_proto_rawDescGZIP(), []int{8}
}

func (x *C2S_MATCH_READY) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

func (x *C2S_MATCH_READY) GetMatchId() []byte {
	if x != nil {
		return x.MatchId
	}
	return nil
}

func (x *C2S_MATCH_READY) GetDecision() ReadyDecision {
	if x != nil {
		return x.Decision
	}
	return ReadyDecision_READY_DECISION_UNSPECIFIED
}

// MatchTeamMember — one roster row inside 806.
type MatchTeamMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   []byte                 `protobuf:"bytes,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"` // UUID
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	ClassId       string                 `protobuf:"bytes,3,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"` // content ID
	Ready         bool                   `protobuf:"varint,4,opt,name=ready,proto3" json:"ready,omitempty"`
	Connected     bool                   `protobuf:"varint,5,opt,name=connected,proto3" json:"connected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchTeamMember) Reset() {
	*x = MatchTeamMember{}
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchTeamMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchTeamMember) ProtoMessage() {}

func (x *MatchTeamMember) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchTeamMember.ProtoReflect.Descriptor instead.
func (*MatchTeamMember) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_pvp_proto_rawDescGZIP(), []int{9}
}

func (x *MatchTeamMember) GetCharacterId() []byte {
	if x != nil {
		return x.CharacterId
	}
	return nil
}

func (x *MatchTeamMember) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *MatchTeamMember) GetClassId() string {
	if x != nil {
		return x.ClassId
	}
	return ""
}

func (x *MatchTeamMember) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *MatchTeamMember) GetConnected() bool {
	if x != nil {
		return x.Connected
	}
	return false
}

// MatchTeam — one team inside 806.
type MatchTeam struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamIndex     uint32                 `protobuf:"varint,1,opt,name=team_index,json=teamIndex,proto3" json:"team_index,omitempty"`
	Score         uint32                 `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	Members       []*MatchTeamMember     `protobuf:"bytes,3,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchTeam) Reset() {
	*x = MatchTeam{}
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchTeam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchTeam) ProtoMessage() {}

func (x *MatchTeam) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchTeam.ProtoReflect.Descriptor instead.
func (*MatchTeam) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_pvp_proto_rawDescGZIP(), []int{10}
}

func (x *MatchTeam) GetTeamIndex() uint32 {
	if x != nil {
		return x.TeamIndex
	}
	return 0
}

func (x *MatchTeam) GetScore() uint32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *MatchTeam) GetMembers() []*MatchTeamMember {
	if x != nil {
		return x.Members
	}
	return nil
}

// S2C_MATCH_STATE (806) — match lifecycle state; ACCEPTED creates the match
// that follows this lifecycle through 806/807.
type S2C_MATCH_STATE struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MatchId         []byte                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"` // UUID
	PvpModeId       string                 `protobuf:"bytes,2,opt,name=pvp_mode_id,json=pvpModeId,proto3" json:"pvp_mode_id,omitempty"`
	State           MatchLifecycle         `protobuf:"varint,3,opt,name=state,proto3,enum=thinhthan.v1.MatchLifecycle" json:"state,omitempty"`
	StateDeadlineMs int64                  `protobuf:"varint,4,opt,name=state_deadline_ms,json=stateDeadlineMs,proto3" json:"state_deadline_ms,omitempty"` // absolute Unix ms
	RoundNumber     uint32                 `protobuf:"varint,5,opt,name=round_number,json=roundNumber,proto3" json:"round_number,omitempty"`
	Teams           []*MatchTeam           `protobuf:"bytes,6,rep,name=teams,proto3" json:"teams,omitempty"`
	Result          MatchResult            `protobuf:"varint,7,opt,name=result,proto3,enum=thinhthan.v1.MatchResult" json:"result,omitempty"`   // receiver's team
	RatingBefore    uint32                 `protobuf:"varint,8,opt,name=rating_before,json=ratingBefore,proto3" json:"rating_before,omitempty"` // ranked only; 0 otherwise
	RatingAfter     uint32                 `protobuf:"varint,9,opt,name=rating_after,json=ratingAfter,proto3" json:"rating_after,omitempty"`    // ranked only; 0 otherwise
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *S2C_MATCH_STATE) Reset() {
	*x = S2C_MATCH_STATE{}
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_MATCH_STATE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_MATCH_STATE) ProtoMessage() {}

func (x *S2C_MATCH_STATE) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_MATCH_STATE.ProtoReflect.Descriptor instead.
func (*S2C_MATCH_STATE) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_pvp_proto_rawDescGZIP(), []int{11}
}

func (x *S2C_MATCH_STATE) GetMatchId() []byte {
	if x != nil {
		return x.MatchId
	}
	return nil
}

func (x *S2C_MATCH_STATE) GetPvpModeId() string {
	if x != nil {
		return x.PvpModeId
	}
	return ""
}

func (x *S2C_MATCH_STATE) GetState() MatchLifecycle {
	if x != nil {
		return x.State
	}
	return MatchLifecycle_MATCH_LIFECYCLE_UNSPECIFIED
}

func (x *S2C_MATCH_STATE) GetStateDeadlineMs() int64 {
	if x != nil {
		return x.StateDeadlineMs
	}
	return 0
}

func (x *S2C_MATCH_STATE) GetRoundNumber() uint32 {
	if x != nil {
		return x.RoundNumber
	}
	return 0
}

func (x *S2C_MATCH_STATE) GetTeams() []*MatchTeam {
	if x != nil {
		return x.Teams
	}
	return nil
}

func (x *S2C_MATCH_STATE) GetResult() MatchResult {
	if x != nil {
		return x.Result
	}
	return MatchResult_MATCH_RESULT_UNSPECIFIED
}

func (x *S2C_MATCH_STATE) GetRatingBefore() uint32 {
	if x != nil {
		return x.RatingBefore
	}
	return 0
}

func (x *S2C_MATCH_STATE) GetRatingAfter() uint32 {
	if x != nil {
		return x.RatingAfter
	}
	return 0
}

// C2S_MATCH_SURRENDER (807) — legal after ACTIVE (pvp.md).
type C2S_MATCH_SURRENDER struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   []byte                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"` // UUID, 16 bytes
	MatchId       []byte                 `protobuf:"bytes,2,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`             // UUID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S_MATCH_SURRENDER) Reset() {
	*x = C2S_MATCH_SURRENDER{}
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_MATCH_SURRENDER) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_MATCH_SURRENDER) ProtoMessage() {}

func (x *C2S_MATCH_SURRENDER) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_MATCH_SURRENDER.ProtoReflect.Descriptor instead.
func (*C2S_MATCH_SURRENDER) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_pvp_proto_rawDescGZIP(), []int{12}
}

func (x *C2S_MATCH_SURRENDER) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

func (x *C2S_MATCH_SURRENDER) GetMatchId() []byte {
	if x != nil {
		return x.MatchId
	}
	return nil
}

// C2S_GUILD_WAR_QUEUE_JOIN (808) — LEADER or VICE_LEADER only; roster is
// exactly 10 distinct characters (guild_war.md § Roster).
type C2S_GUILD_WAR_QUEUE_JOIN struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	OperationId        []byte                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`                        // UUID, 16 bytes
	RosterCharacterIds [][]byte               `protobuf:"bytes,2,rep,name=roster_character_ids,json=rosterCharacterIds,proto3" json:"roster_character_ids,omitempty"` // exactly 10 distinct UUIDs
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *C2S_GUILD_WAR_QUEUE_JOIN) Reset() {
	*x = C2S_GUILD_WAR_QUEUE_JOIN{}
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_GUILD_WAR_QUEUE_JOIN) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_GUILD_WAR_QUEUE_JOIN) ProtoMessage() {}

func (x *C2S_GUILD_WAR_QUEUE_JOIN) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_GUILD_WAR_QUEUE_JOIN.ProtoReflect.Descriptor instead.
func (*C2S_GUILD_WAR_QUEUE_JOIN) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_pvp_proto_rawDescGZIP(), []int{13}
}

func (x *C2S_GUILD_WAR_QUEUE_JOIN) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

func (x *C2S_GUILD_WAR_QUEUE_JOIN) GetRosterCharacterIds() [][]byte {
	if x != nil {
		return x.RosterCharacterIds
	}
	return nil
}

// C2S_GUILD_WAR_QUEUE_LEAVE (809) — cancel the guild-war queue entry.
type C2S_GUILD_WAR_QUEUE_LEAVE struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   []byte                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"` // UUID, 16 bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S_GUILD_WAR_QUEUE_LEAVE) Reset() {
	*x = C2S_GUILD_WAR_QUEUE_LEAVE{}
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_GUILD_WAR_QUEUE_LEAVE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_GUILD_WAR_QUEUE_LEAVE) ProtoMessage() {}

func (x *C2S_GUILD_WAR_QUEUE_LEAVE) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_GUILD_WAR_QUEUE_LEAVE.ProtoReflect.Descriptor instead.
func (*C2S_GUILD_WAR_QUEUE_LEAVE) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_pvp_proto_rawDescGZIP(), []int{14}
}

func (x *C2S_GUILD_WAR_QUEUE_LEAVE) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

// S2C_GUILD_WAR_STATE (810) — guild-war match/queue state.
type S2C_GUILD_WAR_STATE struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	GuildId            []byte                 `protobuf:"bytes,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`                // UUID
	State              MatchLifecycle         `protobuf:"varint,2,opt,name=state,proto3,enum=thinhthan.v1.MatchLifecycle" json:"state,omitempty"` // guild_war.md lifecycle
	RosterCharacterIds [][]byte               `protobuf:"bytes,3,rep,name=roster_character_ids,json=rosterCharacterIds,proto3" json:"roster_character_ids,omitempty"`
	GuildWarMatchId    []byte                 `protobuf:"bytes,4,opt,name=guild_war_match_id,json=guildWarMatchId,proto3" json:"guild_war_match_id,omitempty"` // UUID
	ReadyDeadlineMs    int64                  `protobuf:"varint,5,opt,name=ready_deadline_ms,json=readyDeadlineMs,proto3" json:"ready_deadline_ms,omitempty"`  // absolute Unix ms
	ErrorCode          ErrorCode              `protobuf:"varint,6,opt,name=error_code,json=errorCode,proto3,enum=thinhthan.v1.ErrorCode" json:"error_code,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *S2C_GUILD_WAR_STATE) Reset() {
	*x = S2C_GUILD_WAR_STATE{}
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_GUILD_WAR_STATE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_GUILD_WAR_STATE) ProtoMessage() {}

func (x *S2C_GUILD_WAR_STATE) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_GUILD_WAR_STATE.ProtoReflect.Descriptor instead.
func (*S2C_GUILD_WAR_STATE) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_pvp_proto_rawDescGZIP(), []int{15}
}

func (x *S2C_GUILD_WAR_STATE) GetGuildId() []byte {
	if x != nil {
		return x.GuildId
	}
	return nil
}

func (x *S2C_GUILD_WAR_STATE) GetState() MatchLifecycle {
	if x != nil {
		return x.State
	}
	return MatchLifecycle_MATCH_LIFECYCLE_UNSPECIFIED
}

func (x *S2C_GUILD_WAR_STATE) GetRosterCharacterIds() [][]byte {
	if x != nil {
		return x.RosterCharacterIds
	}
	return nil
}

func (x *S2C_GUILD_WAR_STATE) GetGuildWarMatchId() []byte {
	if x != nil {
		return x.GuildWarMatchId
	}
	return nil
}

func (x *S2C_GUILD_WAR_STATE) GetReadyDeadlineMs() int64 {
	if x != nil {
		return x.ReadyDeadlineMs
	}
	return 0
}

func (x *S2C_GUILD_WAR_STATE) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

// C2S_DUEL_CHALLENGE (814) — challenge a character to pvp.mode.duel;
// eligibility in pvp.md § Duel (level >= 10, online, not queued/matched/
// dead/transferring, social.md direct-interaction gate).
type C2S_DUEL_CHALLENGE struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OperationId       []byte                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`                     // UUID, 16 bytes
	TargetCharacterId []byte                 `protobuf:"bytes,2,opt,name=target_character_id,json=targetCharacterId,proto3" json:"target_character_id,omitempty"` // UUID
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *C2S_DUEL_CHALLENGE) Reset() {
	*x = C2S_DUEL_CHALLENGE{}
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_DUEL_CHALLENGE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_DUEL_CHALLENGE) ProtoMessage() {}

func (x *C2S_DUEL_CHALLENGE) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_DUEL_CHALLENGE.ProtoReflect.Descriptor instead.
func (*C2S_DUEL_CHALLENGE) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_pvp_proto_rawDescGZIP(), []int{16}
}

func (x *C2S_DUEL_CHALLENGE) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

func (x *C2S_DUEL_CHALLENGE) GetTargetCharacterId() []byte {
	if x != nil {
		return x.TargetCharacterId
	}
	return nil
}

// S2C_DUEL_CHALLENGE (815) — challenge delivered to the target.
type S2C_DUEL_CHALLENGE struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ChallengeId           []byte                 `protobuf:"bytes,1,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`                                 // UUID
	ChallengerCharacterId []byte                 `protobuf:"bytes,2,opt,name=challenger_character_id,json=challengerCharacterId,proto3" json:"challenger_character_id,omitempty"` // UUID
	ChallengerName        string                 `protobuf:"bytes,3,opt,name=challenger_name,json=challengerName,proto3" json:"challenger_name,omitempty"`
	ExpiresInSeconds      uint32                 `protobuf:"varint,4,opt,name=expires_in_seconds,json=expiresInSeconds,proto3" json:"expires_in_seconds,omitempty"` // 60
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *S2C_DUEL_CHALLENGE) Reset() {
	*x = S2C_DUEL_CHALLENGE{}
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_DUEL_CHALLENGE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_DUEL_CHALLENGE) ProtoMessage() {}

func (x *S2C_DUEL_CHALLENGE) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_DUEL_CHALLENGE.ProtoReflect.Descriptor instead.
func (*S2C_DUEL_CHALLENGE) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_pvp_proto_rawDescGZIP(), []int{17}
}

func (x *S2C_DUEL_CHALLENGE) GetChallengeId() []byte {
	if x != nil {
		return x.ChallengeId
	}
	return nil
}

func (x *S2C_DUEL_CHALLENGE) GetChallengerCharacterId() []byte {
	if x != nil {
		return x.ChallengerCharacterId
	}
	return nil
}

func (x *S2C_DUEL_CHALLENGE) GetChallengerName() string {
	if x != nil {
		return x.ChallengerName
	}
	return ""
}

func (x *S2C_DUEL_CHALLENGE) GetExpiresInSeconds() uint32 {
	if x != nil {
		return x.ExpiresInSeconds
	}
	return 0
}

// C2S_DUEL_RESPOND (816).
type C2S_DUEL_RESPOND struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   []byte                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`         // UUID, 16 bytes
	ChallengeId   []byte                 `protobuf:"bytes,2,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`         // UUID
	Decision      ReadyDecision          `protobuf:"varint,3,opt,name=decision,proto3,enum=thinhthan.v1.ReadyDecision" json:"decision,omitempty"` // ACCEPT | DECLINE
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S_DUEL_RESPOND) Reset() {
	*x = C2S_DUEL_RESPOND{}
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_DUEL_RESPOND) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_DUEL_RESPOND) ProtoMessage() {}

func (x *C2S_DUEL_RESPOND) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_DUEL_RESPOND.ProtoReflect.Descriptor instead.
func (*C2S_DUEL_RESPOND) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_pvp_proto_rawDescGZIP(), []int{18}
}

func (x *C2S_DUEL_RESPOND) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

func (x *C2S_DUEL_RESPOND) GetChallengeId() []byte {
	if x != nil {
		return x.ChallengeId
	}
	return nil
}

func (x *C2S_DUEL_RESPOND) GetDecision() ReadyDecision {
	if x != nil {
		return x.Decision
	}
	return ReadyDecision_READY_DECISION_UNSPECIFIED
}

// C2S_DUEL_CANCEL (817) — challenger cancels a pending challenge.
type C2S_DUEL_CANCEL struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   []byte                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"` // UUID, 16 bytes
	ChallengeId   []byte                 `protobuf:"bytes,2,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"` // UUID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S_DUEL_CANCEL) Reset() {
	*x = C2S_DUEL_CANCEL{}
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_DUEL_CANCEL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_DUEL_CANCEL) ProtoMessage() {}

func (x *C2S_DUEL_CANCEL) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_DUEL_CANCEL.ProtoReflect.Descriptor instead.
func (*C2S_DUEL_CANCEL) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_pvp_proto_rawDescGZIP(), []int{19}
}

func (x *C2S_DUEL_CANCEL) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

func (x *C2S_DUEL_CANCEL) GetChallengeId() []byte {
	if x != nil {
		return x.ChallengeId
	}
	return nil
}

// S2C_DUEL_OUTCOME (818) — to both parties. *_OUTCOME messages carry no
// OperationResult.
type S2C_DUEL_OUTCOME struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChallengeId   []byte                 `protobuf:"bytes,1,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"` // UUID
	Outcome       DuelOutcome            `protobuf:"varint,2,opt,name=outcome,proto3,enum=thinhthan.v1.DuelOutcome" json:"outcome,omitempty"`
	ErrorCode     ErrorCode              `protobuf:"varint,3,opt,name=error_code,json=errorCode,proto3,enum=thinhthan.v1.ErrorCode" json:"error_code,omitempty"` // REJECTED only
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C_DUEL_OUTCOME) Reset() {
	*x = S2C_DUEL_OUTCOME{}
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_DUEL_OUTCOME) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_DUEL_OUTCOME) ProtoMessage() {}

func (x *S2C_DUEL_OUTCOME) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_DUEL_OUTCOME.ProtoReflect.Descriptor instead.
func (*S2C_DUEL_OUTCOME) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_pvp_proto_rawDescGZIP(), []int{20}
}

func (x *S2C_DUEL_OUTCOME) GetChallengeId() []byte {
	if x != nil {
		return x.ChallengeId
	}
	return nil
}

func (x *S2C_DUEL_OUTCOME) GetOutcome() DuelOutcome {
	if x != nil {
		return x.Outcome
	}
	return DuelOutcome_DUEL_OUTCOME_UNSPECIFIED
}

func (x *S2C_DUEL_OUTCOME) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

// S2C_PVP_RESULT (819) — typed result for every PvP / Guild War C2S
// request: 800 | 801 | 802 | 803 | 805 | 807 | 808 | 809 | 812 | 814 | 816 |
// 817.
type S2C_PVP_RESULT struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Result *OperationResult       `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"` // LEVEL_TOO_LOW | STATE_CONFLICT |
	// COOLDOWN_ACTIVE | PERMISSION_DENIED |
	// TARGET_INVALID | ...
	RequestMessageId uint32 `protobuf:"varint,2,opt,name=request_message_id,json=requestMessageId,proto3" json:"request_message_id,omitempty"`
	ReferenceId      []byte `protobuf:"bytes,3,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"` // challenge_id or match_id UUID; empty
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *S2C_PVP_RESULT) Reset() {
	*x = S2C_PVP_RESULT{}
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_PVP_RESULT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_PVP_RESULT) ProtoMessage() {}

func (x *S2C_PVP_RESULT) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_PVP_RESULT.ProtoReflect.Descriptor instead.
func (*S2C_PVP_RESULT) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_pvp_proto_rawDescGZIP(), []int{21}
}

func (x *S2C_PVP_RESULT) GetResult() *OperationResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *S2C_PVP_RESULT) GetRequestMessageId() uint32 {
	if x != nil {
		return x.RequestMessageId
	}
	return 0
}

func (x *S2C_PVP_RESULT) GetReferenceId() []byte {
	if x != nil {
		return x.ReferenceId
	}
	return nil
}

var File_thinhthan_v1_pvp_proto protoreflect.FileDescriptor

const file_thinhthan_v1_pvp_proto_rawDesc = "" +
	"\n" +
	"\x16thinhthan/v1/pvp.proto\x12\fthinhthan.v1\x1a\x19thinhthan/v1/common.proto\"i\n" +
	"\x14C2S_SPARRING_REQUEST\x12!\n" +
	"\foperation_id\x18\x01 \x01(\fR\voperationId\x12.\n" +
	"\x13target_character_id\x18\x02 \x01(\fR\x11targetCharacterId\"[\n" +
	"\x13C2S_SPARRING_ACCEPT\x12!\n" +
	"\foperation_id\x18\x01 \x01(\fR\voperationId\x12!\n" +
	"\fchallenge_id\x18\x02 \x01(\fR\vchallengeId\"\xca\x01\n" +
	"\x16S2C_SPARRING_CHALLENGE\x12!\n" +
	"\fchallenge_id\x18\x01 \x01(\fR\vchallengeId\x126\n" +
	"\x17challenger_character_id\x18\x02 \x01(\fR\x15challengerCharacterId\x12'\n" +
	"\x0fchallenger_name\x18\x03 \x01(\tR\x0echallengerName\x12,\n" +
	"\x12expires_in_seconds\x18\x04 \x01(\rR\x10expiresInSeconds\"\\\n" +
	"\x14C2S_SPARRING_DECLINE\x12!\n" +
	"\foperation_id\x18\x01 \x01(\fR\voperationId\x12!\n" +
	"\fchallenge_id\x18\x02 \x01(\fR\vchallengeId\"\xaa\x01\n" +
	"\x14S2C_SPARRING_OUTCOME\x12!\n" +
	"\fchallenge_id\x18\x01 \x01(\fR\vchallengeId\x127\n" +
	"\aoutcome\x18\x02 \x01(\x0e2\x1d.thinhthan.v1.SparringOutcomeR\aoutcome\x126\n" +
	"\n" +
	"error_code\x18\x03 \x01(\x0e2\x17.thinhthan.v1.ErrorCodeR\terrorCode\"y\n" +
	"\x15C2S_RANKED_QUEUE_JOIN\x12!\n" +
	"\foperation_id\x18\x01 \x01(\fR\voperationId\x12\x1e\n" +
	"\vpvp_mode_id\x18\x02 \x01(\tR\tpvpModeId\x12\x1d\n" +
	"\n" +
	"with_party\x18\x03 \x01(\bR\twithParty\"[\n" +
	"\x16C2S_RANKED_QUEUE_LEAVE\x12!\n" +
	"\foperation_id\x18\x01 \x01(\fR\voperationId\x12\x1e\n" +
	"\vpvp_mode_id\x18\x02 \x01(\tR\tpvpModeId\"\x9c\x02\n" +
	"\x17S2C_RANKED_QUEUE_UPDATE\x12\x1e\n" +
	"\vpvp_mode_id\x18\x01 \x01(\tR\tpvpModeId\x124\n" +
	"\x05state\x18\x02 \x01(\x0e2\x1e.thinhthan.v1.QueueUpdateStateR\x05state\x12%\n" +
	"\x0equeued_seconds\x18\x03 \x01(\rR\rqueuedSeconds\x12 \n" +
	"\fpvp_match_id\x18\x04 \x01(\fR\n" +
	"pvpMatchId\x12*\n" +
	"\x11ready_deadline_ms\x18\x05 \x01(\x03R\x0freadyDeadlineMs\x126\n" +
	"\n" +
	"error_code\x18\x06 \x01(\x0e2\x17.thinhthan.v1.ErrorCodeR\terrorCode\"\x88\x01\n" +
	"\x0fC2S_MATCH_READY\x12!\n" +
	"\foperation_id\x18\x01 \x01(\fR\voperationId\x12\x19\n" +
	"\bmatch_id\x18\x02 \x01(\fR\amatchId\x127\n" +
	"\bdecision\x18\x03 \x01(\x0e2\x1b.thinhthan.v1.ReadyDecisionR\bdecision\"\xa6\x01\n" +
	"\x0fMatchTeamMember\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\fR\vcharacterId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x19\n" +
	"\bclass_id\x18\x03 \x01(\tR\aclassId\x12\x14\n" +
	"\x05ready\x18\x04 \x01(\bR\x05ready\x12\x1c\n" +
	"\tconnected\x18\x05 \x01(\bR\tconnected\"y\n" +
	"\tMatchTeam\x12\x1d\n" +
	"\n" +
	"team_index\x18\x01 \x01(\rR\tteamIndex\x12\x14\n" +
	"\x05score\x18\x02 \x01(\rR\x05score\x127\n" +
	"\amembers\x18\x03 \x03(\v2\x1d.thinhthan.v1.MatchTeamMemberR\amembers\"\xf9\x02\n" +
	"\x0fS2C_MATCH_STATE\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\fR\amatchId\x12\x1e\n" +
	"\vpvp_mode_id\x18\x02 \x01(\tR\tpvpModeId\x122\n" +
	"\x05state\x18\x03 \x01(\x0e2\x1c.thinhthan.v1.MatchLifecycleR\x05state\x12*\n" +
	"\x11state_deadline_ms\x18\x04 \x01(\x03R\x0fstateDeadlineMs\x12!\n" +
	"\fround_number\x18\x05 \x01(\rR\vroundNumber\x12-\n" +
	"\x05teams\x18\x06 \x03(\v2\x17.thinhthan.v1.MatchTeamR\x05teams\x121\n" +
	"\x06result\x18\a \x01(\x0e2\x19.thinhthan.v1.MatchResultR\x06result\x12#\n" +
	"\rrating_before\x18\b \x01(\rR\fratingBefore\x12!\n" +
	"\frating_after\x18\t \x01(\rR\vratingAfter\"S\n" +
	"\x13C2S_MATCH_SURRENDER\x12!\n" +
	"\foperation_id\x18\x01 \x01(\fR\voperationId\x12\x19\n" +
	"\bmatch_id\x18\x02 \x01(\fR\amatchId\"o\n" +
	"\x18C2S_GUILD_WAR_QUEUE_JOIN\x12!\n" +
	"\foperation_id\x18\x01 \x01(\fR\voperationId\x120\n" +
	"\x14roster_character_ids\x18\x02 \x03(\fR\x12rosterCharacterIds\">\n" +
	"\x19C2S_GUILD_WAR_QUEUE_LEAVE\x12!\n" +
	"\foperation_id\x18\x01 \x01(\fR\voperationId\"\xa7\x02\n" +
	"\x13S2C_GUILD_WAR_STATE\x12\x19\n" +
	"\bguild_id\x18\x01 \x01(\fR\aguildId\x122\n" +
	"\x05state\x18\x02 \x01(\x0e2\x1c.thinhthan.v1.MatchLifecycleR\x05state\x120\n" +
	"\x14roster_character_ids\x18\x03 \x03(\fR\x12rosterCharacterIds\x12+\n" +
	"\x12guild_war_match_id\x18\x04 \x01(\fR\x0fguildWarMatchId\x12*\n" +
	"\x11ready_deadline_ms\x18\x05 \x01(\x03R\x0freadyDeadlineMs\x126\n" +
	"\n" +
	"error_code\x18\x06 \x01(\x0e2\x17.thinhthan.v1.ErrorCodeR\terrorCode\"g\n" +
	"\x12C2S_DUEL_CHALLENGE\x12!\n" +
	"\foperation_id\x18\x01 \x01(\fR\voperationId\x12.\n" +
	"\x13target_character_id\x18\x02 \x01(\fR\x11targetCharacterId\"\xc6\x01\n" +
	"\x12S2C_DUEL_CHALLENGE\x12!\n" +
	"\fchallenge_id\x18\x01 \x01(\fR\vchallengeId\x126\n" +
	"\x17challenger_character_id\x18\x02 \x01(\fR\x15challengerCharacterId\x12'\n" +
	"\x0fchallenger_name\x18\x03 \x01(\tR\x0echallengerName\x12,\n" +
	"\x12expires_in_seconds\x18\x04 \x01(\rR\x10expiresInSeconds\"\x91\x01\n" +
	"\x10C2S_DUEL_RESPOND\x12!\n" +
	"\foperation_id\x18\x01 \x01(\fR\voperationId\x12!\n" +
	"\fchallenge_id\x18\x02 \x01(\fR\vchallengeId\x127\n" +
	"\bdecision\x18\x03 \x01(\x0e2\x1b.thinhthan.v1.ReadyDecisionR\bdecision\"W\n" +
	"\x0fC2S_DUEL_CANCEL\x12!\n" +
	"\foperation_id\x18\x01 \x01(\fR\voperationId\x12!\n" +
	"\fchallenge_id\x18\x02 \x01(\fR\vchallengeId\"\xa2\x01\n" +
	"\x10S2C_DUEL_OUTCOME\x12!\n" +
	"\fchallenge_id\x18\x01 \x01(\fR\vchallengeId\x123\n" +
	"\aoutcome\x18\x02 \x01(\x0e2\x19.thinhthan.v1.DuelOutcomeR\aoutcome\x126\n" +
	"\n" +
	"error_code\x18\x03 \x01(\x0e2\x17.thinhthan.v1.ErrorCodeR\terrorCode\"\x98\x01\n" +
	"\x0eS2C_PVP_RESULT\x125\n" +
	"\x06result\x18\x01 \x01(\v2\x1d.thinhthan.v1.OperationResultR\x06result\x12,\n" +
	"\x12request_message_id\x18\x02 \x01(\rR\x10requestMessageId\x12!\n" +
	"\freference_id\x18\x03 \x01(\fR\vreferenceId*\xb4\x01\n" +
	"\x10QueueUpdateState\x12\"\n" +
	"\x1eQUEUE_UPDATE_STATE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19QUEUE_UPDATE_STATE_QUEUED\x10\x01\x12\x1e\n" +
	"\x1aQUEUE_UPDATE_STATE_MATCHED\x10\x02\x12 \n" +
	"\x1cQUEUE_UPDATE_STATE_ACCEPTING\x10\x03\x12\x1b\n" +
	"\x17QUEUE_UPDATE_STATE_LEFT\x10\x04*\xa1\x02\n" +
	"\x0eMatchLifecycle\x12\x1f\n" +
	"\x1bMATCH_LIFECYCLE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16MATCH_LIFECYCLE_QUEUED\x10\x01\x12\x1b\n" +
	"\x17MATCH_LIFECYCLE_MATCHED\x10\x02\x12\x1d\n" +
	"\x19MATCH_LIFECYCLE_ACCEPTING\x10\x03\x12\x1d\n" +
	"\x19MATCH_LIFECYCLE_PREPARING\x10\x04\x12\x1a\n" +
	"\x16MATCH_LIFECYCLE_ACTIVE\x10\x05\x12\x1d\n" +
	"\x19MATCH_LIFECYCLE_RESOLVING\x10\x06\x12\x1d\n" +
	"\x19MATCH_LIFECYCLE_COMPLETED\x10\a\x12\x1d\n" +
	"\x19MATCH_LIFECYCLE_CANCELLED\x10\b*\x9d\x01\n" +
	"\vMatchResult\x12\x1c\n" +
	"\x18MATCH_RESULT_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11MATCH_RESULT_NONE\x10\x01\x12\x14\n" +
	"\x10MATCH_RESULT_WIN\x10\x02\x12\x15\n" +
	"\x11MATCH_RESULT_LOSS\x10\x03\x12\x15\n" +
	"\x11MATCH_RESULT_DRAW\x10\x04\x12\x15\n" +
	"\x11MATCH_RESULT_VOID\x10\x05*f\n" +
	"\rReadyDecision\x12\x1e\n" +
	"\x1aREADY_DECISION_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15READY_DECISION_ACCEPT\x10\x01\x12\x1a\n" +
	"\x16READY_DECISION_DECLINE\x10\x02*\xae\x01\n" +
	"\x0fSparringOutcome\x12 \n" +
	"\x1cSPARRING_OUTCOME_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19SPARRING_OUTCOME_ACCEPTED\x10\x01\x12\x1d\n" +
	"\x19SPARRING_OUTCOME_DECLINED\x10\x02\x12\x1c\n" +
	"\x18SPARRING_OUTCOME_EXPIRED\x10\x03\x12\x1d\n" +
	"\x19SPARRING_OUTCOME_REJECTED\x10\x04*\xb2\x01\n" +
	"\vDuelOutcome\x12\x1c\n" +
	"\x18DUEL_OUTCOME_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15DUEL_OUTCOME_ACCEPTED\x10\x01\x12\x19\n" +
	"\x15DUEL_OUTCOME_DECLINED\x10\x02\x12\x1a\n" +
	"\x16DUEL_OUTCOME_CANCELLED\x10\x03\x12\x18\n" +
	"\x14DUEL_OUTCOME_EXPIRED\x10\x04\x12\x19\n" +
	"\x15DUEL_OUTCOME_REJECTED\x10\x05BCZ)thinhthan/internal/protocol/v1;protocolv1\xaa\x02\x15ThinhThan.Protocol.V1b\x06proto3"

var (
	file_thinhthan_v1_pvp_proto_rawDescOnce sync.Once
	file_thinhthan_v1_pvp_proto_rawDescData []byte
)

func file_thinhthan_v1_pvp_proto_rawDescGZIP() []byte {
	file_thinhthan_v1_pvp_proto_rawDescOnce.Do(func() {
		file_thinhthan_v1_pvp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_thinhthan_v1_pvp_proto_rawDesc), len(file_thinhthan_v1_pvp_proto_rawDesc)))
	})
	return file_thinhthan_v1_pvp_proto_rawDescData
}

var file_thinhthan_v1_pvp_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_thinhthan_v1_pvp_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_thinhthan_v1_pvp_proto_goTypes = []any{
	(QueueUpdateState)(0),             // 0: thinhthan.v1.QueueUpdateState
	(MatchLifecycle)(0),               // 1: thinhthan.v1.MatchLifecycle
	(MatchResult)(0),                  // 2: thinhthan.v1.MatchResult
	(ReadyDecision)(0),                // 3: thinhthan.v1.ReadyDecision
	(SparringOutcome)(0),              // 4: thinhthan.v1.SparringOutcome
	(DuelOutcome)(0),                  // 5: thinhthan.v1.DuelOutcome
	(*C2S_SPARRING_REQUEST)(nil),      // 6: thinhthan.v1.C2S_SPARRING_REQUEST
	(*C2S_SPARRING_ACCEPT)(nil),       // 7: thinhthan.v1.C2S_SPARRING_ACCEPT
	(*S2C_SPARRING_CHALLENGE)(nil),    // 8: thinhthan.v1.S2C_SPARRING_CHALLENGE
	(*C2S_SPARRING_DECLINE)(nil),      // 9: thinhthan.v1.C2S_SPARRING_DECLINE
	(*S2C_SPARRING_OUTCOME)(nil),      // 10: thinhthan.v1.S2C_SPARRING_OUTCOME
	(*C2S_RANKED_QUEUE_JOIN)(nil),     // 11: thinhthan.v1.C2S_RANKED_QUEUE_JOIN
	(*C2S_RANKED_QUEUE_LEAVE)(nil),    // 12: thinhthan.v1.C2S_RANKED_QUEUE_LEAVE
	(*S2C_RANKED_QUEUE_UPDATE)(nil),   // 13: thinhthan.v1.S2C_RANKED_QUEUE_UPDATE
	(*C2S_MATCH_READY)(nil),           // 14: thinhthan.v1.C2S_MATCH_READY
	(*MatchTeamMember)(nil),           // 15: thinhthan.v1.MatchTeamMember
	(*MatchTeam)(nil),                 // 16: thinhthan.v1.MatchTeam
	(*S2C_MATCH_STATE)(nil),           // 17: thinhthan.v1.S2C_MATCH_STATE
	(*C2S_MATCH_SURRENDER)(nil),       // 18: thinhthan.v1.C2S_MATCH_SURRENDER
	(*C2S_GUILD_WAR_QUEUE_JOIN)(nil),  // 19: thinhthan.v1.C2S_GUILD_WAR_QUEUE_JOIN
	(*C2S_GUILD_WAR_QUEUE_LEAVE)(nil), // 20: thinhthan.v1.C2S_GUILD_WAR_QUEUE_LEAVE
	(*S2C_GUILD_WAR_STATE)(nil),       // 21: thinhthan.v1.S2C_GUILD_WAR_STATE
	(*C2S_DUEL_CHALLENGE)(nil),        // 22: thinhthan.v1.C2S_DUEL_CHALLENGE
	(*S2C_DUEL_CHALLENGE)(nil),        // 23: thinhthan.v1.S2C_DUEL_CHALLENGE
	(*C2S_DUEL_RESPOND)(nil),          // 24: thinhthan.v1.C2S_DUEL_RESPOND
	(*C2S_DUEL_CANCEL)(nil),           // 25: thinhthan.v1.C2S_DUEL_CANCEL
	(*S2C_DUEL_OUTCOME)(nil),          // 26: thinhthan.v1.S2C_DUEL_OUTCOME
	(*S2C_PVP_RESULT)(nil),            // 27: thinhthan.v1.S2C_PVP_RESULT
	(ErrorCode)(0),                    // 28: thinhthan.v1.ErrorCode
	(*OperationResult)(nil),           // 29: thinhthan.v1.OperationResult
}
var file_thinhthan_v1_pvp_proto_depIdxs = []int32{
	4,  // 0: thinhthan.v1.S2C_SPARRING_OUTCOME.outcome:type_name -> thinhthan.v1.SparringOutcome
	28, // 1: thinhthan.v1.S2C_SPARRING_OUTCOME.error_code:type_name -> thinhthan.v1.ErrorCode
	0,  // 2: thinhthan.v1.S2C_RANKED_QUEUE_UPDATE.state:type_name -> thinhthan.v1.QueueUpdateState
	28, // 3: thinhthan.v1.S2C_RANKED_QUEUE_UPDATE.error_code:type_name -> thinhthan.v1.ErrorCode
	3,  // 4: thinhthan.v1.C2S_MATCH_READY.decision:type_name -> thinhthan.v1.ReadyDecision
	15, // 5: thinhthan.v1.MatchTeam.members:type_name -> thinhthan.v1.MatchTeamMember
	1,  // 6: thinhthan.v1.S2C_MATCH_STATE.state:type_name -> thinhthan.v1.MatchLifecycle
	16, // 7: thinhthan.v1.S2C_MATCH_STATE.teams:type_name -> thinhthan.v1.MatchTeam
	2,  // 8: thinhthan.v1.S2C_MATCH_STATE.result:type_name -> thinhthan.v1.MatchResult
	1,  // 9: thinhthan.v1.S2C_GUILD_WAR_STATE.state:type_name -> thinhthan.v1.MatchLifecycle
	28, // 10: thinhthan.v1.S2C_GUILD_WAR_STATE.error_code:type_name -> thinhthan.v1.ErrorCode
	3,  // 11: thinhthan.v1.C2S_DUEL_RESPOND.decision:type_name -> thinhthan.v1.ReadyDecision
	5,  // 12: thinhthan.v1.S2C_DUEL_OUTCOME.outcome:type_name -> thinhthan.v1.DuelOutcome
	28, // 13: thinhthan.v1.S2C_DUEL_OUTCOME.error_code:type_name -> thinhthan.v1.ErrorCode
	29, // 14: thinhthan.v1.S2C_PVP_RESULT.result:type_name -> thinhthan.v1.OperationResult
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_thinhthan_v1_pvp_proto_init() }
func file_thinhthan_v1_pvp_proto_init() {
	if File_thinhthan_v1_pvp_proto != nil {
		return
	}
	file_thinhthan_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_thinhthan_v1_pvp_proto_rawDesc), len(file_thinhthan_v1_pvp_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_thinhthan_v1_pvp_proto_goTypes,
		DependencyIndexes: file_thinhthan_v1_pvp_proto_depIdxs,
		EnumInfos:         file_thinhthan_v1_pvp_proto_enumTypes,
		MessageInfos:      file_thinhthan_v1_pvp_proto_msgTypes,
	}.Build()
	File_thinhthan_v1_pvp_proto = out.File
	file_thinhthan_v1_pvp_proto_goTypes = nil
	file_thinhthan_v1_pvp_proto_depIdxs = nil
}
