// Connection / session family (message IDs 1..16).
// Handshake order: HTTPS bootstrap -> wss -> C2S_HELLO -> S2C_HELLO_OK ->
// attach -> realtime traffic (docs/05_network/protocol.md § Handshake).
// Field lists: docs/05_network/messages.md § Connection / Session (ADR-0064,
// ADR-0069).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: thinhthan/v1/session.proto

package protocolv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SessionPlatform — client platform declared at HELLO.
type SessionPlatform int32

const (
	SessionPlatform_SESSION_PLATFORM_UNSPECIFIED SessionPlatform = 0
	SessionPlatform_SESSION_PLATFORM_WINDOWS     SessionPlatform = 1
	SessionPlatform_SESSION_PLATFORM_ANDROID     SessionPlatform = 2
)

// Enum value maps for SessionPlatform.
var (
	SessionPlatform_name = map[int32]string{
		0: "SESSION_PLATFORM_UNSPECIFIED",
		1: "SESSION_PLATFORM_WINDOWS",
		2: "SESSION_PLATFORM_ANDROID",
	}
	SessionPlatform_value = map[string]int32{
		"SESSION_PLATFORM_UNSPECIFIED": 0,
		"SESSION_PLATFORM_WINDOWS":     1,
		"SESSION_PLATFORM_ANDROID":     2,
	}
)

func (x SessionPlatform) Enum() *SessionPlatform {
	p := new(SessionPlatform)
	*p = x
	return p
}

func (x SessionPlatform) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionPlatform) Descriptor() protoreflect.EnumDescriptor {
	return file_thinhthan_v1_session_proto_enumTypes[0].Descriptor()
}

func (SessionPlatform) Type() protoreflect.EnumType {
	return &file_thinhthan_v1_session_proto_enumTypes[0]
}

func (x SessionPlatform) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionPlatform.Descriptor instead.
func (SessionPlatform) EnumDescriptor() ([]byte, []int) {
	return file_thinhthan_v1_session_proto_rawDescGZIP(), []int{0}
}

// SessionReplacedReason — why a session was superseded (ADR-0030).
type SessionReplacedReason int32

const (
	SessionReplacedReason_SESSION_REPLACED_REASON_UNSPECIFIED   SessionReplacedReason = 0
	SessionReplacedReason_SESSION_REPLACED_REASON_NEWER_SESSION SessionReplacedReason = 1
	SessionReplacedReason_SESSION_REPLACED_REASON_REVOKED       SessionReplacedReason = 2
)

// Enum value maps for SessionReplacedReason.
var (
	SessionReplacedReason_name = map[int32]string{
		0: "SESSION_REPLACED_REASON_UNSPECIFIED",
		1: "SESSION_REPLACED_REASON_NEWER_SESSION",
		2: "SESSION_REPLACED_REASON_REVOKED",
	}
	SessionReplacedReason_value = map[string]int32{
		"SESSION_REPLACED_REASON_UNSPECIFIED":   0,
		"SESSION_REPLACED_REASON_NEWER_SESSION": 1,
		"SESSION_REPLACED_REASON_REVOKED":       2,
	}
)

func (x SessionReplacedReason) Enum() *SessionReplacedReason {
	p := new(SessionReplacedReason)
	*p = x
	return p
}

func (x SessionReplacedReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionReplacedReason) Descriptor() protoreflect.EnumDescriptor {
	return file_thinhthan_v1_session_proto_enumTypes[1].Descriptor()
}

func (SessionReplacedReason) Type() protoreflect.EnumType {
	return &file_thinhthan_v1_session_proto_enumTypes[1]
}

func (x SessionReplacedReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionReplacedReason.Descriptor instead.
func (SessionReplacedReason) EnumDescriptor() ([]byte, []int) {
	return file_thinhthan_v1_session_proto_rawDescGZIP(), []int{1}
}

// ServerDrainingReason — why the server is draining.
type ServerDrainingReason int32

const (
	ServerDrainingReason_SERVER_DRAINING_REASON_UNSPECIFIED ServerDrainingReason = 0
	ServerDrainingReason_SERVER_DRAINING_REASON_MAINTENANCE ServerDrainingReason = 1
)

// Enum value maps for ServerDrainingReason.
var (
	ServerDrainingReason_name = map[int32]string{
		0: "SERVER_DRAINING_REASON_UNSPECIFIED",
		1: "SERVER_DRAINING_REASON_MAINTENANCE",
	}
	ServerDrainingReason_value = map[string]int32{
		"SERVER_DRAINING_REASON_UNSPECIFIED": 0,
		"SERVER_DRAINING_REASON_MAINTENANCE": 1,
	}
)

func (x ServerDrainingReason) Enum() *ServerDrainingReason {
	p := new(ServerDrainingReason)
	*p = x
	return p
}

func (x ServerDrainingReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServerDrainingReason) Descriptor() protoreflect.EnumDescriptor {
	return file_thinhthan_v1_session_proto_enumTypes[2].Descriptor()
}

func (ServerDrainingReason) Type() protoreflect.EnumType {
	return &file_thinhthan_v1_session_proto_enumTypes[2]
}

func (x ServerDrainingReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServerDrainingReason.Descriptor instead.
func (ServerDrainingReason) EnumDescriptor() ([]byte, []int) {
	return file_thinhthan_v1_session_proto_rawDescGZIP(), []int{2}
}

// PlacementPendingReason — which placement is waiting for a forced-placement
// slot (02_world/world_rules.md § Forced Placement).
type PlacementPendingReason int32

const (
	PlacementPendingReason_PLACEMENT_PENDING_REASON_UNSPECIFIED     PlacementPendingReason = 0
	PlacementPendingReason_PLACEMENT_PENDING_REASON_RESPAWN         PlacementPendingReason = 1
	PlacementPendingReason_PLACEMENT_PENDING_REASON_INSTANCE_RETURN PlacementPendingReason = 2
	PlacementPendingReason_PLACEMENT_PENDING_REASON_RECONNECT       PlacementPendingReason = 3
	PlacementPendingReason_PLACEMENT_PENDING_REASON_FIRST_LOGIN     PlacementPendingReason = 4
)

// Enum value maps for PlacementPendingReason.
var (
	PlacementPendingReason_name = map[int32]string{
		0: "PLACEMENT_PENDING_REASON_UNSPECIFIED",
		1: "PLACEMENT_PENDING_REASON_RESPAWN",
		2: "PLACEMENT_PENDING_REASON_INSTANCE_RETURN",
		3: "PLACEMENT_PENDING_REASON_RECONNECT",
		4: "PLACEMENT_PENDING_REASON_FIRST_LOGIN",
	}
	PlacementPendingReason_value = map[string]int32{
		"PLACEMENT_PENDING_REASON_UNSPECIFIED":     0,
		"PLACEMENT_PENDING_REASON_RESPAWN":         1,
		"PLACEMENT_PENDING_REASON_INSTANCE_RETURN": 2,
		"PLACEMENT_PENDING_REASON_RECONNECT":       3,
		"PLACEMENT_PENDING_REASON_FIRST_LOGIN":     4,
	}
)

func (x PlacementPendingReason) Enum() *PlacementPendingReason {
	p := new(PlacementPendingReason)
	*p = x
	return p
}

func (x PlacementPendingReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlacementPendingReason) Descriptor() protoreflect.EnumDescriptor {
	return file_thinhthan_v1_session_proto_enumTypes[3].Descriptor()
}

func (PlacementPendingReason) Type() protoreflect.EnumType {
	return &file_thinhthan_v1_session_proto_enumTypes[3]
}

func (x PlacementPendingReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlacementPendingReason.Descriptor instead.
func (PlacementPendingReason) EnumDescriptor() ([]byte, []int) {
	return file_thinhthan_v1_session_proto_rawDescGZIP(), []int{3}
}

// C2S_HELLO (1) declares the version tuple (envelope protocol_major/minor)
// and presents a credential: the gameplay ticket from POST
// /api/v1/gameplay/ticket, or the resume credential of a live session.
// Envelope: session_epoch = 0, client_seq = 1.
type C2S_HELLO struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Credential:
	//
	//	*C2S_HELLO_GameplayTicket
	//	*C2S_HELLO_ResumeCredential
	Credential      isC2S_HELLO_Credential `protobuf_oneof:"credential"`
	ClientBuild     string                 `protobuf:"bytes,3,opt,name=client_build,json=clientBuild,proto3" json:"client_build,omitempty"`             // client build identifier
	Platform        SessionPlatform        `protobuf:"varint,4,opt,name=platform,proto3,enum=thinhthan.v1.SessionPlatform" json:"platform,omitempty"`   // WINDOWS | ANDROID
	ContentRevision string                 `protobuf:"bytes,5,opt,name=content_revision,json=contentRevision,proto3" json:"content_revision,omitempty"` // content catalog revision
	DeviceId        []byte                 `protobuf:"bytes,6,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`                      // 16 bytes (07_security/auth.md § Device ID)
	Locale          string                 `protobuf:"bytes,7,opt,name=locale,proto3" json:"locale,omitempty"`                                          // vi-VN | en-US
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *C2S_HELLO) Reset() {
	*x = C2S_HELLO{}
	mi := &file_thinhthan_v1_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_HELLO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_HELLO) ProtoMessage() {}

func (x *C2S_HELLO) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_HELLO.ProtoReflect.Descriptor instead.
func (*C2S_HELLO) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_session_proto_rawDescGZIP(), []int{0}
}

func (x *C2S_HELLO) GetCredential() isC2S_HELLO_Credential {
	if x != nil {
		return x.Credential
	}
	return nil
}

func (x *C2S_HELLO) GetGameplayTicket() string {
	if x != nil {
		if x, ok := x.Credential.(*C2S_HELLO_GameplayTicket); ok {
			return x.GameplayTicket
		}
	}
	return ""
}

func (x *C2S_HELLO) GetResumeCredential() string {
	if x != nil {
		if x, ok := x.Credential.(*C2S_HELLO_ResumeCredential); ok {
			return x.ResumeCredential
		}
	}
	return ""
}

func (x *C2S_HELLO) GetClientBuild() string {
	if x != nil {
		return x.ClientBuild
	}
	return ""
}

func (x *C2S_HELLO) GetPlatform() SessionPlatform {
	if x != nil {
		return x.Platform
	}
	return SessionPlatform_SESSION_PLATFORM_UNSPECIFIED
}

func (x *C2S_HELLO) GetContentRevision() string {
	if x != nil {
		return x.ContentRevision
	}
	return ""
}

func (x *C2S_HELLO) GetDeviceId() []byte {
	if x != nil {
		return x.DeviceId
	}
	return nil
}

func (x *C2S_HELLO) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

type isC2S_HELLO_Credential interface {
	isC2S_HELLO_Credential()
}

type C2S_HELLO_GameplayTicket struct {
	GameplayTicket string `protobuf:"bytes,1,opt,name=gameplay_ticket,json=gameplayTicket,proto3,oneof"` // short-lived ticket (07_security/auth.md)
}

type C2S_HELLO_ResumeCredential struct {
	ResumeCredential string `protobuf:"bytes,2,opt,name=resume_credential,json=resumeCredential,proto3,oneof"` // sliding resume credential (S2C_HELLO_OK / 16)
}

func (*C2S_HELLO_GameplayTicket) isC2S_HELLO_Credential() {}

func (*C2S_HELLO_ResumeCredential) isC2S_HELLO_Credential() {}

// S2C_HELLO_OK (2) returns the authoritative session epoch and connection
// parameters accepted by the server.
type S2C_HELLO_OK struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	SessionId           []byte                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // UUID, 16 bytes
	SessionEpoch        uint64                 `protobuf:"varint,2,opt,name=session_epoch,json=sessionEpoch,proto3" json:"session_epoch,omitempty"`
	AccountId           []byte                 `protobuf:"bytes,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`                                  // UUID, 16 bytes
	ServerTimeMs        int64                  `protobuf:"varint,4,opt,name=server_time_ms,json=serverTimeMs,proto3" json:"server_time_ms,omitempty"`                      // Unix ms
	HeartbeatIntervalMs uint32                 `protobuf:"varint,5,opt,name=heartbeat_interval_ms,json=heartbeatIntervalMs,proto3" json:"heartbeat_interval_ms,omitempty"` // 5000
	ConnectionTimeoutMs uint32                 `protobuf:"varint,6,opt,name=connection_timeout_ms,json=connectionTimeoutMs,proto3" json:"connection_timeout_ms,omitempty"` // 15000
	ResumeCredential    string                 `protobuf:"bytes,7,opt,name=resume_credential,json=resumeCredential,proto3" json:"resume_credential,omitempty"`             // sliding resume credential
	ResumeExpiresAtMs   int64                  `protobuf:"varint,8,opt,name=resume_expires_at_ms,json=resumeExpiresAtMs,proto3" json:"resume_expires_at_ms,omitempty"`     // Unix ms
	ProtocolMinor       uint32                 `protobuf:"varint,9,opt,name=protocol_minor,json=protocolMinor,proto3" json:"protocol_minor,omitempty"`                     // server protocol minor
	ContentRevision     string                 `protobuf:"bytes,10,opt,name=content_revision,json=contentRevision,proto3" json:"content_revision,omitempty"`
	PendingDeletion     bool                   `protobuf:"varint,11,opt,name=pending_deletion,json=pendingDeletion,proto3" json:"pending_deletion,omitempty"`           // ACCOUNT_PENDING_DELETION flow (07_security/data_protection.md)
	ResumedCharacterId  []byte                 `protobuf:"bytes,12,opt,name=resumed_character_id,json=resumedCharacterId,proto3" json:"resumed_character_id,omitempty"` // 16 bytes; set when resume or superseding
	// HELLO re-attached the account's live
	// character (7 follows without a 6)
	ResumeRotateIntervalMs uint32 `protobuf:"varint,13,opt,name=resume_rotate_interval_ms,json=resumeRotateIntervalMs,proto3" json:"resume_rotate_interval_ms,omitempty"` // 300000
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *S2C_HELLO_OK) Reset() {
	*x = S2C_HELLO_OK{}
	mi := &file_thinhthan_v1_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_HELLO_OK) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_HELLO_OK) ProtoMessage() {}

func (x *S2C_HELLO_OK) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_HELLO_OK.ProtoReflect.Descriptor instead.
func (*S2C_HELLO_OK) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_session_proto_rawDescGZIP(), []int{1}
}

func (x *S2C_HELLO_OK) GetSessionId() []byte {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *S2C_HELLO_OK) GetSessionEpoch() uint64 {
	if x != nil {
		return x.SessionEpoch
	}
	return 0
}

func (x *S2C_HELLO_OK) GetAccountId() []byte {
	if x != nil {
		return x.AccountId
	}
	return nil
}

func (x *S2C_HELLO_OK) GetServerTimeMs() int64 {
	if x != nil {
		return x.ServerTimeMs
	}
	return 0
}

func (x *S2C_HELLO_OK) GetHeartbeatIntervalMs() uint32 {
	if x != nil {
		return x.HeartbeatIntervalMs
	}
	return 0
}

func (x *S2C_HELLO_OK) GetConnectionTimeoutMs() uint32 {
	if x != nil {
		return x.ConnectionTimeoutMs
	}
	return 0
}

func (x *S2C_HELLO_OK) GetResumeCredential() string {
	if x != nil {
		return x.ResumeCredential
	}
	return ""
}

func (x *S2C_HELLO_OK) GetResumeExpiresAtMs() int64 {
	if x != nil {
		return x.ResumeExpiresAtMs
	}
	return 0
}

func (x *S2C_HELLO_OK) GetProtocolMinor() uint32 {
	if x != nil {
		return x.ProtocolMinor
	}
	return 0
}

func (x *S2C_HELLO_OK) GetContentRevision() string {
	if x != nil {
		return x.ContentRevision
	}
	return ""
}

func (x *S2C_HELLO_OK) GetPendingDeletion() bool {
	if x != nil {
		return x.PendingDeletion
	}
	return false
}

func (x *S2C_HELLO_OK) GetResumedCharacterId() []byte {
	if x != nil {
		return x.ResumedCharacterId
	}
	return nil
}

func (x *S2C_HELLO_OK) GetResumeRotateIntervalMs() uint32 {
	if x != nil {
		return x.ResumeRotateIntervalMs
	}
	return 0
}

// S2C_ERROR (3) is the typed protocol/session failure surface.
// Envelope correlation_id = client_seq of the rejected frame (0 if none).
type S2C_ERROR struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode      ErrorCode              `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3,enum=thinhthan.v1.ErrorCode" json:"error_code,omitempty"`
	Retryability   Retryability           `protobuf:"varint,2,opt,name=retryability,proto3,enum=thinhthan.v1.Retryability" json:"retryability,omitempty"`
	RetryAfterMs   uint32                 `protobuf:"varint,3,opt,name=retry_after_ms,json=retryAfterMs,proto3" json:"retry_after_ms,omitempty"`
	QueuePosition  uint32                 `protobuf:"varint,4,opt,name=queue_position,json=queuePosition,proto3" json:"queue_position,omitempty"`     // login queue only
	SafeMessageKey string                 `protobuf:"bytes,5,opt,name=safe_message_key,json=safeMessageKey,proto3" json:"safe_message_key,omitempty"` // localization key; never internal text
	CloseAfter     bool                   `protobuf:"varint,6,opt,name=close_after,json=closeAfter,proto3" json:"close_after,omitempty"`              // server closes the socket after sending
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *S2C_ERROR) Reset() {
	*x = S2C_ERROR{}
	mi := &file_thinhthan_v1_session_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_ERROR) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_ERROR) ProtoMessage() {}

func (x *S2C_ERROR) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_session_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_ERROR.ProtoReflect.Descriptor instead.
func (*S2C_ERROR) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_session_proto_rawDescGZIP(), []int{2}
}

func (x *S2C_ERROR) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

func (x *S2C_ERROR) GetRetryability() Retryability {
	if x != nil {
		return x.Retryability
	}
	return Retryability_RETRYABILITY_UNSPECIFIED
}

func (x *S2C_ERROR) GetRetryAfterMs() uint32 {
	if x != nil {
		return x.RetryAfterMs
	}
	return 0
}

func (x *S2C_ERROR) GetQueuePosition() uint32 {
	if x != nil {
		return x.QueuePosition
	}
	return 0
}

func (x *S2C_ERROR) GetSafeMessageKey() string {
	if x != nil {
		return x.SafeMessageKey
	}
	return ""
}

func (x *S2C_ERROR) GetCloseAfter() bool {
	if x != nil {
		return x.CloseAfter
	}
	return false
}

// C2S_HEARTBEAT (4) — application heartbeat; RTT sample = server receive time
// - echo_server_ms when non-zero (protocol.md § Heartbeat).
type C2S_HEARTBEAT struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientMonoMs  uint64                 `protobuf:"varint,1,opt,name=client_mono_ms,json=clientMonoMs,proto3" json:"client_mono_ms,omitempty"` // client monotonic ms, advisory only
	EchoServerMs  uint64                 `protobuf:"varint,2,opt,name=echo_server_ms,json=echoServerMs,proto3" json:"echo_server_ms,omitempty"` // last S2C_HEARTBEAT.server_ms; 0 = none yet
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S_HEARTBEAT) Reset() {
	*x = C2S_HEARTBEAT{}
	mi := &file_thinhthan_v1_session_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_HEARTBEAT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_HEARTBEAT) ProtoMessage() {}

func (x *C2S_HEARTBEAT) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_session_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_HEARTBEAT.ProtoReflect.Descriptor instead.
func (*C2S_HEARTBEAT) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_session_proto_rawDescGZIP(), []int{3}
}

func (x *C2S_HEARTBEAT) GetClientMonoMs() uint64 {
	if x != nil {
		return x.ClientMonoMs
	}
	return 0
}

func (x *C2S_HEARTBEAT) GetEchoServerMs() uint64 {
	if x != nil {
		return x.EchoServerMs
	}
	return 0
}

// S2C_HEARTBEAT (5) acknowledges liveness with authoritative server time.
type S2C_HEARTBEAT struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerMs      uint64                 `protobuf:"varint,1,opt,name=server_ms,json=serverMs,proto3" json:"server_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C_HEARTBEAT) Reset() {
	*x = S2C_HEARTBEAT{}
	mi := &file_thinhthan_v1_session_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_HEARTBEAT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_HEARTBEAT) ProtoMessage() {}

func (x *S2C_HEARTBEAT) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_session_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_HEARTBEAT.ProtoReflect.Descriptor instead.
func (*S2C_HEARTBEAT) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_session_proto_rawDescGZIP(), []int{4}
}

func (x *S2C_HEARTBEAT) GetServerMs() uint64 {
	if x != nil {
		return x.ServerMs
	}
	return 0
}

// C2S_CHARACTER_ATTACH (6) attaches one character to this session.
// Rejections use S2C_ERROR (CHARACTER_ALREADY_ACTIVE, NOT_OWNER,
// ACCOUNT_PENDING_DELETION); a forced-placement wait answers with 15.
type C2S_CHARACTER_ATTACH struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   []byte                 `protobuf:"bytes,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"` // UUID, 16 bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S_CHARACTER_ATTACH) Reset() {
	*x = C2S_CHARACTER_ATTACH{}
	mi := &file_thinhthan_v1_session_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_CHARACTER_ATTACH) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_CHARACTER_ATTACH) ProtoMessage() {}

func (x *C2S_CHARACTER_ATTACH) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_session_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_CHARACTER_ATTACH.ProtoReflect.Descriptor instead.
func (*C2S_CHARACTER_ATTACH) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_session_proto_rawDescGZIP(), []int{5}
}

func (x *C2S_CHARACTER_ATTACH) GetCharacterId() []byte {
	if x != nil {
		return x.CharacterId
	}
	return nil
}

// S2C_CHARACTER_ATTACH_OK (7) confirms the attach; realtime messages become
// legal only after this point. Followed by S2C_WORLD_BASELINE (300) and every
// state push (432..438, 515, 607, 616, 619, 628).
type S2C_CHARACTER_ATTACH_OK struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CharacterId     []byte                 `protobuf:"bytes,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"` // UUID, 16 bytes
	OwnershipEpoch  uint64                 `protobuf:"varint,2,opt,name=ownership_epoch,json=ownershipEpoch,proto3" json:"ownership_epoch,omitempty"`
	MapId           string                 `protobuf:"bytes,3,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"` // content ID
	ChannelIndex    uint32                 `protobuf:"varint,4,opt,name=channel_index,json=channelIndex,proto3" json:"channel_index,omitempty"`
	InstanceId      []byte                 `protobuf:"bytes,5,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"` // 16 bytes; empty in the normal world
	ContentRevision string                 `protobuf:"bytes,6,opt,name=content_revision,json=contentRevision,proto3" json:"content_revision,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *S2C_CHARACTER_ATTACH_OK) Reset() {
	*x = S2C_CHARACTER_ATTACH_OK{}
	mi := &file_thinhthan_v1_session_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_CHARACTER_ATTACH_OK) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_CHARACTER_ATTACH_OK) ProtoMessage() {}

func (x *S2C_CHARACTER_ATTACH_OK) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_session_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_CHARACTER_ATTACH_OK.ProtoReflect.Descriptor instead.
func (*S2C_CHARACTER_ATTACH_OK) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_session_proto_rawDescGZIP(), []int{6}
}

func (x *S2C_CHARACTER_ATTACH_OK) GetCharacterId() []byte {
	if x != nil {
		return x.CharacterId
	}
	return nil
}

func (x *S2C_CHARACTER_ATTACH_OK) GetOwnershipEpoch() uint64 {
	if x != nil {
		return x.OwnershipEpoch
	}
	return 0
}

func (x *S2C_CHARACTER_ATTACH_OK) GetMapId() string {
	if x != nil {
		return x.MapId
	}
	return ""
}

func (x *S2C_CHARACTER_ATTACH_OK) GetChannelIndex() uint32 {
	if x != nil {
		return x.ChannelIndex
	}
	return 0
}

func (x *S2C_CHARACTER_ATTACH_OK) GetInstanceId() []byte {
	if x != nil {
		return x.InstanceId
	}
	return nil
}

func (x *S2C_CHARACTER_ATTACH_OK) GetContentRevision() string {
	if x != nil {
		return x.ContentRevision
	}
	return ""
}

// S2C_SESSION_REPLACED (8) notifies the replaced side; the server closes the
// socket after sending.
type S2C_SESSION_REPLACED struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        SessionReplacedReason  `protobuf:"varint,1,opt,name=reason,proto3,enum=thinhthan.v1.SessionReplacedReason" json:"reason,omitempty"` // NEWER_SESSION | REVOKED
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C_SESSION_REPLACED) Reset() {
	*x = S2C_SESSION_REPLACED{}
	mi := &file_thinhthan_v1_session_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_SESSION_REPLACED) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_SESSION_REPLACED) ProtoMessage() {}

func (x *S2C_SESSION_REPLACED) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_session_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_SESSION_REPLACED.ProtoReflect.Descriptor instead.
func (*S2C_SESSION_REPLACED) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_session_proto_rawDescGZIP(), []int{7}
}

func (x *S2C_SESSION_REPLACED) GetReason() SessionReplacedReason {
	if x != nil {
		return x.Reason
	}
	return SessionReplacedReason_SESSION_REPLACED_REASON_UNSPECIFIED
}

// S2C_SERVER_DRAINING (9) announces a draining window; retryability RECONNECT.
type S2C_SERVER_DRAINING struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Reason           ServerDrainingReason   `protobuf:"varint,1,opt,name=reason,proto3,enum=thinhthan.v1.ServerDrainingReason" json:"reason,omitempty"`     // MAINTENANCE
	DrainDeadlineMs  int64                  `protobuf:"varint,2,opt,name=drain_deadline_ms,json=drainDeadlineMs,proto3" json:"drain_deadline_ms,omitempty"` // absolute Unix ms
	ReconnectAfterMs uint32                 `protobuf:"varint,3,opt,name=reconnect_after_ms,json=reconnectAfterMs,proto3" json:"reconnect_after_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *S2C_SERVER_DRAINING) Reset() {
	*x = S2C_SERVER_DRAINING{}
	mi := &file_thinhthan_v1_session_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_SERVER_DRAINING) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_SERVER_DRAINING) ProtoMessage() {}

func (x *S2C_SERVER_DRAINING) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_session_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_SERVER_DRAINING.ProtoReflect.Descriptor instead.
func (*S2C_SERVER_DRAINING) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_session_proto_rawDescGZIP(), []int{8}
}

func (x *S2C_SERVER_DRAINING) GetReason() ServerDrainingReason {
	if x != nil {
		return x.Reason
	}
	return ServerDrainingReason_SERVER_DRAINING_REASON_UNSPECIFIED
}

func (x *S2C_SERVER_DRAINING) GetDrainDeadlineMs() int64 {
	if x != nil {
		return x.DrainDeadlineMs
	}
	return 0
}

func (x *S2C_SERVER_DRAINING) GetReconnectAfterMs() uint32 {
	if x != nil {
		return x.ReconnectAfterMs
	}
	return 0
}

// C2S_CHARACTER_DETACH (10) returns the attached character to OFFLINE.
type C2S_CHARACTER_DETACH struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S_CHARACTER_DETACH) Reset() {
	*x = C2S_CHARACTER_DETACH{}
	mi := &file_thinhthan_v1_session_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_CHARACTER_DETACH) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_CHARACTER_DETACH) ProtoMessage() {}

func (x *C2S_CHARACTER_DETACH) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_session_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_CHARACTER_DETACH.ProtoReflect.Descriptor instead.
func (*C2S_CHARACTER_DETACH) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_session_proto_rawDescGZIP(), []int{9}
}

// S2C_CHARACTER_DETACH_OK (11) confirms the detach; followed by 14.
type S2C_CHARACTER_DETACH_OK struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   []byte                 `protobuf:"bytes,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"` // UUID, 16 bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C_CHARACTER_DETACH_OK) Reset() {
	*x = S2C_CHARACTER_DETACH_OK{}
	mi := &file_thinhthan_v1_session_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_CHARACTER_DETACH_OK) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_CHARACTER_DETACH_OK) ProtoMessage() {}

func (x *S2C_CHARACTER_DETACH_OK) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_session_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_CHARACTER_DETACH_OK.ProtoReflect.Descriptor instead.
func (*S2C_CHARACTER_DETACH_OK) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_session_proto_rawDescGZIP(), []int{10}
}

func (x *S2C_CHARACTER_DETACH_OK) GetCharacterId() []byte {
	if x != nil {
		return x.CharacterId
	}
	return nil
}

// C2S_CHARACTER_CREATE (12) creates a character; legal only while no
// character is attached.
type C2S_CHARACTER_CREATE struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   []byte                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`       // UUID, 16 bytes — idempotency key
	CharacterName string                 `protobuf:"bytes,2,opt,name=character_name,json=characterName,proto3" json:"character_name,omitempty"` // 01_gameplay/character.md § Name; 06_data/text.md
	ClassId       string                 `protobuf:"bytes,3,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`                   // class.kim | class.moc | class.thuy | class.hoa | class.tho
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S_CHARACTER_CREATE) Reset() {
	*x = C2S_CHARACTER_CREATE{}
	mi := &file_thinhthan_v1_session_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_CHARACTER_CREATE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_CHARACTER_CREATE) ProtoMessage() {}

func (x *C2S_CHARACTER_CREATE) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_session_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_CHARACTER_CREATE.ProtoReflect.Descriptor instead.
func (*C2S_CHARACTER_CREATE) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_session_proto_rawDescGZIP(), []int{11}
}

func (x *C2S_CHARACTER_CREATE) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

func (x *C2S_CHARACTER_CREATE) GetCharacterName() string {
	if x != nil {
		return x.CharacterName
	}
	return ""
}

func (x *C2S_CHARACTER_CREATE) GetClassId() string {
	if x != nil {
		return x.ClassId
	}
	return ""
}

// S2C_CHARACTER_CREATE_RESULT (13) answers 12; followed by 14 on success.
type S2C_CHARACTER_CREATE_RESULT struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Result *OperationResult       `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"` // CHARACTER_NAME_INVALID |
	// CHARACTER_NAME_TAKEN |
	// CHARACTER_SLOTS_FULL | TARGET_INVALID
	Character     *CharacterSummary `protobuf:"bytes,2,opt,name=character,proto3" json:"character,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C_CHARACTER_CREATE_RESULT) Reset() {
	*x = S2C_CHARACTER_CREATE_RESULT{}
	mi := &file_thinhthan_v1_session_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_CHARACTER_CREATE_RESULT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_CHARACTER_CREATE_RESULT) ProtoMessage() {}

func (x *S2C_CHARACTER_CREATE_RESULT) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_session_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_CHARACTER_CREATE_RESULT.ProtoReflect.Descriptor instead.
func (*S2C_CHARACTER_CREATE_RESULT) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_session_proto_rawDescGZIP(), []int{12}
}

func (x *S2C_CHARACTER_CREATE_RESULT) GetResult() *OperationResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *S2C_CHARACTER_CREATE_RESULT) GetCharacter() *CharacterSummary {
	if x != nil {
		return x.Character
	}
	return nil
}

// S2C_CHARACTER_LIST (14) — REPLACEABLE_STATE snapshot; sent after 2 (when no
// character was resumed), after 11, and after a successful 12.
type S2C_CHARACTER_LIST struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Characters     []*CharacterSummary    `protobuf:"bytes,1,rep,name=characters,proto3" json:"characters,omitempty"`
	CharacterSlots uint32                 `protobuf:"varint,2,opt,name=character_slots,json=characterSlots,proto3" json:"character_slots,omitempty"` // 3 (03_systems/monetization.md)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *S2C_CHARACTER_LIST) Reset() {
	*x = S2C_CHARACTER_LIST{}
	mi := &file_thinhthan_v1_session_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_CHARACTER_LIST) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_CHARACTER_LIST) ProtoMessage() {}

func (x *S2C_CHARACTER_LIST) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_session_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_CHARACTER_LIST.ProtoReflect.Descriptor instead.
func (*S2C_CHARACTER_LIST) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_session_proto_rawDescGZIP(), []int{13}
}

func (x *S2C_CHARACTER_LIST) GetCharacters() []*CharacterSummary {
	if x != nil {
		return x.Characters
	}
	return nil
}

func (x *S2C_CHARACTER_LIST) GetCharacterSlots() uint32 {
	if x != nil {
		return x.CharacterSlots
	}
	return 0
}

// S2C_PLACEMENT_PENDING (15) — a placement waits for a forced-placement slot;
// the server keeps retrying and later sends 7 / 207 / 105. Never an error.
type S2C_PLACEMENT_PENDING struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RequestMessageId uint32                 `protobuf:"varint,1,opt,name=request_message_id,json=requestMessageId,proto3" json:"request_message_id,omitempty"` // 6 | 208 | 0 for server-initiated transfers
	Reason           PlacementPendingReason `protobuf:"varint,2,opt,name=reason,proto3,enum=thinhthan.v1.PlacementPendingReason" json:"reason,omitempty"`
	RetryAfterMs     uint32                 `protobuf:"varint,3,opt,name=retry_after_ms,json=retryAfterMs,proto3" json:"retry_after_ms,omitempty"` // 5000
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *S2C_PLACEMENT_PENDING) Reset() {
	*x = S2C_PLACEMENT_PENDING{}
	mi := &file_thinhthan_v1_session_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_PLACEMENT_PENDING) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_PLACEMENT_PENDING) ProtoMessage() {}

func (x *S2C_PLACEMENT_PENDING) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_session_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_PLACEMENT_PENDING.ProtoReflect.Descriptor instead.
func (*S2C_PLACEMENT_PENDING) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_session_proto_rawDescGZIP(), []int{14}
}

func (x *S2C_PLACEMENT_PENDING) GetRequestMessageId() uint32 {
	if x != nil {
		return x.RequestMessageId
	}
	return 0
}

func (x *S2C_PLACEMENT_PENDING) GetReason() PlacementPendingReason {
	if x != nil {
		return x.Reason
	}
	return PlacementPendingReason_PLACEMENT_PENDING_REASON_UNSPECIFIED
}

func (x *S2C_PLACEMENT_PENDING) GetRetryAfterMs() uint32 {
	if x != nil {
		return x.RetryAfterMs
	}
	return 0
}

// S2C_RESUME_CREDENTIAL (16) — AUTHORITATIVE_EVENT; sent every 300 s while the
// session is live (sliding rotation, 07_security/session.md § Resume). The
// previous credential stays valid until the new one is first presented or it
// expires.
type S2C_RESUME_CREDENTIAL struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ResumeCredential  string                 `protobuf:"bytes,1,opt,name=resume_credential,json=resumeCredential,proto3" json:"resume_credential,omitempty"`
	ResumeExpiresAtMs int64                  `protobuf:"varint,2,opt,name=resume_expires_at_ms,json=resumeExpiresAtMs,proto3" json:"resume_expires_at_ms,omitempty"` // Unix ms
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *S2C_RESUME_CREDENTIAL) Reset() {
	*x = S2C_RESUME_CREDENTIAL{}
	mi := &file_thinhthan_v1_session_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_RESUME_CREDENTIAL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_RESUME_CREDENTIAL) ProtoMessage() {}

func (x *S2C_RESUME_CREDENTIAL) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_session_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_RESUME_CREDENTIAL.ProtoReflect.Descriptor instead.
func (*S2C_RESUME_CREDENTIAL) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_session_proto_rawDescGZIP(), []int{15}
}

func (x *S2C_RESUME_CREDENTIAL) GetResumeCredential() string {
	if x != nil {
		return x.ResumeCredential
	}
	return ""
}

func (x *S2C_RESUME_CREDENTIAL) GetResumeExpiresAtMs() int64 {
	if x != nil {
		return x.ResumeExpiresAtMs
	}
	return 0
}

var File_thinhthan_v1_session_proto protoreflect.FileDescriptor

const file_thinhthan_v1_session_proto_rawDesc = "" +
	"\n" +
	"\x1athinhthan/v1/session.proto\x12\fthinhthan.v1\x1a\x19thinhthan/v1/common.proto\"\xb1\x02\n" +
	"\tC2S_HELLO\x12)\n" +
	"\x0fgameplay_ticket\x18\x01 \x01(\tH\x00R\x0egameplayTicket\x12-\n" +
	"\x11resume_credential\x18\x02 \x01(\tH\x00R\x10resumeCredential\x12!\n" +
	"\fclient_build\x18\x03 \x01(\tR\vclientBuild\x129\n" +
	"\bplatform\x18\x04 \x01(\x0e2\x1d.thinhthan.v1.SessionPlatformR\bplatform\x12)\n" +
	"\x10content_revision\x18\x05 \x01(\tR\x0fcontentRevision\x12\x1b\n" +
	"\tdevice_id\x18\x06 \x01(\fR\bdeviceId\x12\x16\n" +
	"\x06locale\x18\a \x01(\tR\x06localeB\f\n" +
	"\n" +
	"credential\"\xc7\x04\n" +
	"\fS2C_HELLO_OK\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\fR\tsessionId\x12#\n" +
	"\rsession_epoch\x18\x02 \x01(\x04R\fsessionEpoch\x12\x1d\n" +
	"\n" +
	"account_id\x18\x03 \x01(\fR\taccountId\x12$\n" +
	"\x0eserver_time_ms\x18\x04 \x01(\x03R\fserverTimeMs\x122\n" +
	"\x15heartbeat_interval_ms\x18\x05 \x01(\rR\x13heartbeatIntervalMs\x122\n" +
	"\x15connection_timeout_ms\x18\x06 \x01(\rR\x13connectionTimeoutMs\x12+\n" +
	"\x11resume_credential\x18\a \x01(\tR\x10resumeCredential\x12/\n" +
	"\x14resume_expires_at_ms\x18\b \x01(\x03R\x11resumeExpiresAtMs\x12%\n" +
	"\x0eprotocol_minor\x18\t \x01(\rR\rprotocolMinor\x12)\n" +
	"\x10content_revision\x18\n" +
	" \x01(\tR\x0fcontentRevision\x12)\n" +
	"\x10pending_deletion\x18\v \x01(\bR\x0fpendingDeletion\x120\n" +
	"\x14resumed_character_id\x18\f \x01(\fR\x12resumedCharacterId\x129\n" +
	"\x19resume_rotate_interval_ms\x18\r \x01(\rR\x16resumeRotateIntervalMs\"\x9b\x02\n" +
	"\tS2C_ERROR\x126\n" +
	"\n" +
	"error_code\x18\x01 \x01(\x0e2\x17.thinhthan.v1.ErrorCodeR\terrorCode\x12>\n" +
	"\fretryability\x18\x02 \x01(\x0e2\x1a.thinhthan.v1.RetryabilityR\fretryability\x12$\n" +
	"\x0eretry_after_ms\x18\x03 \x01(\rR\fretryAfterMs\x12%\n" +
	"\x0equeue_position\x18\x04 \x01(\rR\rqueuePosition\x12(\n" +
	"\x10safe_message_key\x18\x05 \x01(\tR\x0esafeMessageKey\x12\x1f\n" +
	"\vclose_after\x18\x06 \x01(\bR\n" +
	"closeAfter\"[\n" +
	"\rC2S_HEARTBEAT\x12$\n" +
	"\x0eclient_mono_ms\x18\x01 \x01(\x04R\fclientMonoMs\x12$\n" +
	"\x0eecho_server_ms\x18\x02 \x01(\x04R\fechoServerMs\",\n" +
	"\rS2C_HEARTBEAT\x12\x1b\n" +
	"\tserver_ms\x18\x01 \x01(\x04R\bserverMs\"9\n" +
	"\x14C2S_CHARACTER_ATTACH\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\fR\vcharacterId\"\xed\x01\n" +
	"\x17S2C_CHARACTER_ATTACH_OK\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\fR\vcharacterId\x12'\n" +
	"\x0fownership_epoch\x18\x02 \x01(\x04R\x0eownershipEpoch\x12\x15\n" +
	"\x06map_id\x18\x03 \x01(\tR\x05mapId\x12#\n" +
	"\rchannel_index\x18\x04 \x01(\rR\fchannelIndex\x12\x1f\n" +
	"\vinstance_id\x18\x05 \x01(\fR\n" +
	"instanceId\x12)\n" +
	"\x10content_revision\x18\x06 \x01(\tR\x0fcontentRevision\"S\n" +
	"\x14S2C_SESSION_REPLACED\x12;\n" +
	"\x06reason\x18\x01 \x01(\x0e2#.thinhthan.v1.SessionReplacedReasonR\x06reason\"\xab\x01\n" +
	"\x13S2C_SERVER_DRAINING\x12:\n" +
	"\x06reason\x18\x01 \x01(\x0e2\".thinhthan.v1.ServerDrainingReasonR\x06reason\x12*\n" +
	"\x11drain_deadline_ms\x18\x02 \x01(\x03R\x0fdrainDeadlineMs\x12,\n" +
	"\x12reconnect_after_ms\x18\x03 \x01(\rR\x10reconnectAfterMs\"\x16\n" +
	"\x14C2S_CHARACTER_DETACH\"<\n" +
	"\x17S2C_CHARACTER_DETACH_OK\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\fR\vcharacterId\"{\n" +
	"\x14C2S_CHARACTER_CREATE\x12!\n" +
	"\foperation_id\x18\x01 \x01(\fR\voperationId\x12%\n" +
	"\x0echaracter_name\x18\x02 \x01(\tR\rcharacterName\x12\x19\n" +
	"\bclass_id\x18\x03 \x01(\tR\aclassId\"\x92\x01\n" +
	"\x1bS2C_CHARACTER_CREATE_RESULT\x125\n" +
	"\x06result\x18\x01 \x01(\v2\x1d.thinhthan.v1.OperationResultR\x06result\x12<\n" +
	"\tcharacter\x18\x02 \x01(\v2\x1e.thinhthan.v1.CharacterSummaryR\tcharacter\"}\n" +
	"\x12S2C_CHARACTER_LIST\x12>\n" +
	"\n" +
	"characters\x18\x01 \x03(\v2\x1e.thinhthan.v1.CharacterSummaryR\n" +
	"characters\x12'\n" +
	"\x0fcharacter_slots\x18\x02 \x01(\rR\x0echaracterSlots\"\xa9\x01\n" +
	"\x15S2C_PLACEMENT_PENDING\x12,\n" +
	"\x12request_message_id\x18\x01 \x01(\rR\x10requestMessageId\x12<\n" +
	"\x06reason\x18\x02 \x01(\x0e2$.thinhthan.v1.PlacementPendingReasonR\x06reason\x12$\n" +
	"\x0eretry_after_ms\x18\x03 \x01(\rR\fretryAfterMs\"u\n" +
	"\x15S2C_RESUME_CREDENTIAL\x12+\n" +
	"\x11resume_credential\x18\x01 \x01(\tR\x10resumeCredential\x12/\n" +
	"\x14resume_expires_at_ms\x18\x02 \x01(\x03R\x11resumeExpiresAtMs*o\n" +
	"\x0fSessionPlatform\x12 \n" +
	"\x1cSESSION_PLATFORM_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18SESSION_PLATFORM_WINDOWS\x10\x01\x12\x1c\n" +
	"\x18SESSION_PLATFORM_ANDROID\x10\x02*\x90\x01\n" +
	"\x15SessionReplacedReason\x12'\n" +
	"#SESSION_REPLACED_REASON_UNSPECIFIED\x10\x00\x12)\n" +
	"%SESSION_REPLACED_REASON_NEWER_SESSION\x10\x01\x12#\n" +
	"\x1fSESSION_REPLACED_REASON_REVOKED\x10\x02*f\n" +
	"\x14ServerDrainingReason\x12&\n" +
	"\"SERVER_DRAINING_REASON_UNSPECIFIED\x10\x00\x12&\n" +
	"\"SERVER_DRAINING_REASON_MAINTENANCE\x10\x01*\xe8\x01\n" +
	"\x16PlacementPendingReason\x12(\n" +
	"$PLACEMENT_PENDING_REASON_UNSPECIFIED\x10\x00\x12$\n" +
	" PLACEMENT_PENDING_REASON_RESPAWN\x10\x01\x12,\n" +
	"(PLACEMENT_PENDING_REASON_INSTANCE_RETURN\x10\x02\x12&\n" +
	"\"PLACEMENT_PENDING_REASON_RECONNECT\x10\x03\x12(\n" +
	"$PLACEMENT_PENDING_REASON_FIRST_LOGIN\x10\x04BCZ)thinhthan/internal/protocol/v1;protocolv1\xaa\x02\x15ThinhThan.Protocol.V1b\x06proto3"

var (
	file_thinhthan_v1_session_proto_rawDescOnce sync.Once
	file_thinhthan_v1_session_proto_rawDescData []byte
)

func file_thinhthan_v1_session_proto_rawDescGZIP() []byte {
	file_thinhthan_v1_session_proto_rawDescOnce.Do(func() {
		file_thinhthan_v1_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_thinhthan_v1_session_proto_rawDesc), len(file_thinhthan_v1_session_proto_rawDesc)))
	})
	return file_thinhthan_v1_session_proto_rawDescData
}

var file_thinhthan_v1_session_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_thinhthan_v1_session_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_thinhthan_v1_session_proto_goTypes = []any{
	(SessionPlatform)(0),                // 0: thinhthan.v1.SessionPlatform
	(SessionReplacedReason)(0),          // 1: thinhthan.v1.SessionReplacedReason
	(ServerDrainingReason)(0),           // 2: thinhthan.v1.ServerDrainingReason
	(PlacementPendingReason)(0),         // 3: thinhthan.v1.PlacementPendingReason
	(*C2S_HELLO)(nil),                   // 4: thinhthan.v1.C2S_HELLO
	(*S2C_HELLO_OK)(nil),                // 5: thinhthan.v1.S2C_HELLO_OK
	(*S2C_ERROR)(nil),                   // 6: thinhthan.v1.S2C_ERROR
	(*C2S_HEARTBEAT)(nil),               // 7: thinhthan.v1.C2S_HEARTBEAT
	(*S2C_HEARTBEAT)(nil),               // 8: thinhthan.v1.S2C_HEARTBEAT
	(*C2S_CHARACTER_ATTACH)(nil),        // 9: thinhthan.v1.C2S_CHARACTER_ATTACH
	(*S2C_CHARACTER_ATTACH_OK)(nil),     // 10: thinhthan.v1.S2C_CHARACTER_ATTACH_OK
	(*S2C_SESSION_REPLACED)(nil),        // 11: thinhthan.v1.S2C_SESSION_REPLACED
	(*S2C_SERVER_DRAINING)(nil),         // 12: thinhthan.v1.S2C_SERVER_DRAINING
	(*C2S_CHARACTER_DETACH)(nil),        // 13: thinhthan.v1.C2S_CHARACTER_DETACH
	(*S2C_CHARACTER_DETACH_OK)(nil),     // 14: thinhthan.v1.S2C_CHARACTER_DETACH_OK
	(*C2S_CHARACTER_CREATE)(nil),        // 15: thinhthan.v1.C2S_CHARACTER_CREATE
	(*S2C_CHARACTER_CREATE_RESULT)(nil), // 16: thinhthan.v1.S2C_CHARACTER_CREATE_RESULT
	(*S2C_CHARACTER_LIST)(nil),          // 17: thinhthan.v1.S2C_CHARACTER_LIST
	(*S2C_PLACEMENT_PENDING)(nil),       // 18: thinhthan.v1.S2C_PLACEMENT_PENDING
	(*S2C_RESUME_CREDENTIAL)(nil),       // 19: thinhthan.v1.S2C_RESUME_CREDENTIAL
	(ErrorCode)(0),                      // 20: thinhthan.v1.ErrorCode
	(Retryability)(0),                   // 21: thinhthan.v1.Retryability
	(*OperationResult)(nil),             // 22: thinhthan.v1.OperationResult
	(*CharacterSummary)(nil),            // 23: thinhthan.v1.CharacterSummary
}
var file_thinhthan_v1_session_proto_depIdxs = []int32{
	0,  // 0: thinhthan.v1.C2S_HELLO.platform:type_name -> thinhthan.v1.SessionPlatform
	20, // 1: thinhthan.v1.S2C_ERROR.error_code:type_name -> thinhthan.v1.ErrorCode
	21, // 2: thinhthan.v1.S2C_ERROR.retryability:type_name -> thinhthan.v1.Retryability
	1,  // 3: thinhthan.v1.S2C_SESSION_REPLACED.reason:type_name -> thinhthan.v1.SessionReplacedReason
	2,  // 4: thinhthan.v1.S2C_SERVER_DRAINING.reason:type_name -> thinhthan.v1.ServerDrainingReason
	22, // 5: thinhthan.v1.S2C_CHARACTER_CREATE_RESULT.result:type_name -> thinhthan.v1.OperationResult
	23, // 6: thinhthan.v1.S2C_CHARACTER_CREATE_RESULT.character:type_name -> thinhthan.v1.CharacterSummary
	23, // 7: thinhthan.v1.S2C_CHARACTER_LIST.characters:type_name -> thinhthan.v1.CharacterSummary
	3,  // 8: thinhthan.v1.S2C_PLACEMENT_PENDING.reason:type_name -> thinhthan.v1.PlacementPendingReason
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_thinhthan_v1_session_proto_init() }
func file_thinhthan_v1_session_proto_init() {
	if File_thinhthan_v1_session_proto != nil {
		return
	}
	file_thinhthan_v1_common_proto_init()
	file_thinhthan_v1_session_proto_msgTypes[0].OneofWrappers = []any{
		(*C2S_HELLO_GameplayTicket)(nil),
		(*C2S_HELLO_ResumeCredential)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_thinhthan_v1_session_proto_rawDesc), len(file_thinhthan_v1_session_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_thinhthan_v1_session_proto_goTypes,
		DependencyIndexes: file_thinhthan_v1_session_proto_depIdxs,
		EnumInfos:         file_thinhthan_v1_session_proto_enumTypes,
		MessageInfos:      file_thinhthan_v1_session_proto_msgTypes,
	}.Build()
	File_thinhthan_v1_session_proto = out.File
	file_thinhthan_v1_session_proto_goTypes = nil
	file_thinhthan_v1_session_proto_depIdxs = nil
}
